### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by pymomo** [nschloe/pygmsh#108]
Dear pygmsh users,

I have just tried to run the first example on the pygmsh website, but I am getting the following error:
```
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
I am using Anaconda3 and running the code via Spyder.

Could you please advise how I can fix this issue?

The code I am trying to run is as follows:
```python
import pygmsh
import numpy as np

geom = pygmsh.built_in.Geometry()

# Draw a cross.
poly = geom.add_polygon([
    [0.0,   0.5, 0.0],
    [-0.1,  0.1, 0.0],
    [-0.5,  0.0, 0.0],
    [-0.1, -0.1, 0.0],
    [0.0,  -0.5, 0.0],
    [0.1,  -0.1, 0.0],
    [0.5,   0.0, 0.0],
    [0.1,   0.1, 0.0]
    ],
    lcar=0.05
    )

axis = [0, 0, 1]

geom.extrude(
    poly,
    translation_axis=axis,
    rotation_axis=axis,
    point_on_axis=[0, 0, 0],
    angle=2.0 / 6.0 * np.pi
    )

points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)
```

Thanks!

**Comment by nschloe** [comment]
Puh, no idea. It's too bad that the error message doesn't specify _which_ file it cannot find.
Perhaps `gmsh`? Have you installed gmsh and is it available in your system path? You could play with the `gmsh_path` keyword of `generate_mesh`.

**Comment by pymomo** [comment]
Thanks for your response. Actually it says, here is the whole error message:


  File "<ipython-input-1-6d10652b9d5f>", line 1, in <module>
    runfile('C:/Users/JackMorten/Documents/Data/CFD/pygmsh/test_circle.py', wdir='C:/Users/JackMorten/Documents/Data/CFD/pygmsh')

  File "C:\Users\JackMorten\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\Users\JackMorten\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/JackMorten/Documents/Data/CFD/pygmsh/test_circle.py", line 26, in <module>
    points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)

  File "C:\Users\JackMorten\AppData\Local\Continuum\Anaconda3\lib\site-packages\pygmsh\helpers.py", line 111, in generate_mesh
    gmsh_major_version = get_gmsh_major_version(gmsh_executable)

  File "C:\Users\JackMorten\AppData\Local\Continuum\Anaconda3\lib\site-packages\pygmsh\helpers.py", line 81, in get_gmsh_major_version
    stderr=subprocess.STDOUT

  File "C:\Users\JackMorten\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout

  File "C:\Users\JackMorten\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\JackMorten\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)

  File "C:\Users\JackMorten\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified



Could you please share your opinion on this?
Thanks

**Comment by nschloe** [comment]
Jup, apparently it cannot find gmsh. Like I said: Check out with the `gmsh_path` keyword of `generate_mesh`.

**Comment by pymomo** [comment]
Yes indeed, it works now!  Thanks!
But I have two more errors:
1. when trying to write the mesh with the following command
meshio.write('test.vtu', points, cells, cell_data=cell_data)

I get the following error:

  File "C:\Users\nly41664\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\Users\nly41664\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/nly41664/Documents/Data/CFD/pygmsh/test_circle.py", line 39, in <module>
    meshio.write('test.vtu', points, cells, cell_data=cell_data)

  File "C:\Users\nly41664\AppData\Local\Continuum\Anaconda3\lib\site-packages\meshio\helpers.py", line 196, in write
    field_data=field_data

  File "C:\Users\nly41664\AppData\Local\Continuum\Anaconda3\lib\site-packages\meshio\vtk_io.py", line 159, in write
    import vtk

ImportError: No module named 'vtk'


I tried to install vtk for python from (https://anaconda.org/anaconda/vtk) but it failed because I have python 3.5 and it seems it needs python 2.7.

Do I need to install python 2.7 to be able to use pygmsh or is this problem can be solved in another way?

2. While running some other examples on (https://github.com/nschloe/pygmsh/tree/master/test/), I get another error regarding "from helpers import compute_volume". It cannot find helpers:


  File "C:\Users\nly41664\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\Users\nly41664\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/nly41664/Documents/Data/CFD/pygmsh/test_rectangle.py", line 3, in <module>
    from helpers import compute_volume

ImportError: No module named 'helpers'

I appreciate your advice on this.

**Comment by nschloe** [comment]
> I tried to install vtk for python from (https://anaconda.org/anaconda/vtk) but it failed because I have python 3.5 and it seems it needs python 2.7.

If you want to write vtk, vtu, exodus, or xdmf, you'll need VTK. Unfortunately, this dependency is huge, and has caused trouble for others before. I'm currently working on implementing I/O for those data types myself, but it'll probably be a while before it's usable.

Till then, you'll have to make sure to have VTK7 or later installed with Python 3 support if you want to use Python 3.

> `ImportError: No module named 'helpers'`

Try running the file while in the same folder. You can also comment out this import, it's only needed for tests.

**Comment by pymomo** [comment]
Thanks for the tips.

**Comment by akegalj** [comment]
@pymomo 
> Yes indeed, it works now! Thanks!

can you expand on how did you make it work? My understanding is that you have downloaded gmsh from gmsh.info and you have set `gmsh_path` to the extracted directory of gmsh ?

**Comment by nschloe** [comment]
Alright, glad you got it to work!

**Comment by akegalj** [comment]
@nschloe Sorry for bothering. I have manged to make it work but then I have stuck on the same effort as @pymomo did with 
```
meshio.write('test.vtu', points, cells, cell_data=cell_data)
```
and error:
```
ImportError: No module named 'vtk'
```
I am using python version 3.6 but I have tried and ended up with the same error with python-2.7 . Did I understood you correctly
> Till then, you'll have to make sure to have VTK7 or later installed with Python 3 support if you want to use Python 3.

that it should be easier with python-2.7 ? If so, can you give me some tips.

**Comment by nschloe** [comment]
You'll have to install VTK with Python. No idea how to do it in Windows, but traditionally this has been a hassle. It's even not that straightforward in Linux. VTK has landed Python 3 support in version 7 which was released long while ago, so perhaps you'll manage to install it.

To reiterate, I'm currently working on getting rid of the vtk dependency, but as you can imagine this is a major task: The entire I/O for vtk, vtu, exodus, xdmf has to be rewritten.

**Comment by tady57** [comment]
@nschloe hi , sorry for bothering . I  have succeeded and connected pygmsh, vtk files,paraview , python and gmsh. My question is how to connect .igs file with python. Inside of that file I have geometry which I have to use to create mesh. I do not know what all text in .igs file mean so I have not tried to read line by line from .igs file yet. 

Thank you ,
tady57

**Comment by nschloe** [comment]
@tady57 

Never heard of igs, sorry.
(In the future, if you have an issue and it doesn't appear in the issue list yet, please open a new one.)

**Comment by tady57** [comment]
@nschloe  
 
  Do you know solution to the same question with .std file instead of .igs file? I am sorry, I will open new issue topic next time. 

Thank you for your time

**Comment by nschloe** [comment]
@tady57 Never heard of std either.

**Comment by tady57** [comment]
@nschloe  I am sorry , stp file - not std

**Comment by gdmcbain** [comment]
Re .igs, see #122; no further comment here.

**Comment by NoelleHarte** [comment]
> 
> 
> Jup, apparently it cannot find gmsh. Like I said: Check out with the `gmsh_path` keyword of `generate_mesh`.

E.g. for Windows:
mesh = pygmsh.generate_mesh(geom, gmsh_path = 'C:/Users/.../gmsh-4.5.1-Windows64/gmsh-4.5.1-Windows64/gmsh.exe')
