### ISSUE TITLE
Recombine Surface

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#115]
I tried to create a quadrilateral two-dimensional mesh by inserting 

```
Recombine Surface {s0};
```

into the Gmsh .geo code to be emitted, but it didn't seem to work.

Specifically, I started a branch [recsurf](https://github.com/gdmcbain/pygmsh/blob/recsurf) and  in [test](https://github.com/gdmcbain/pygmsh/blob/recsurf/test) copied and modified [test_rectangle.py](https://github.com/gdmcbain/pygmsh/blob/recsurf/test/test_rectangle.py) to [test_quads.py](https://github.com/gdmcbain/pygmsh/blob/recsurf/test/test_quads.py) by:
* catching the `Polygon` returned by `add_rectangle`
* putting its `surface.id` into `Recombine Surface` using `add_raw_code` (for the moment, with the idea of maybe adding a specialized method later)
* saving the output of `get_code`

```python
    rectangle = geom.add_rectangle(...)
    geom.add_raw_code('Recombine Surface {%s};' % rectangle.surface.id)
    with open('quads.geo', 'w') as fgeo:
        fgeo.write(geom.get_code())
```

Then on comparing the meshes generated by
  * `pygmsh.generate_mesh` and `meshio.write`, as in `test_rectangle.py` and
  * running Gmsh manually on the quads.geo file
  
I find that the latter has quadrilaterals but the former only triangles.

Is the directive to Recombine Surface ignored or lost in going via meshio.read and meshio.write?

Is there a more direct way to get unstructured quadrilateral surface meshes?

(One application of this is to combine it with the `extrude(layers=...)` option added in #109 to get hexahedral meshes on extrusions of fairly arbitrary surfaces.)

**Comment by nschloe** [comment]
Alright, so first off, I created an optional argument `geo_filename` to `generate_mesh` which writes the geo file to wherever location you specify, and preserves it there for debugging.

This should help us figure out exactly why `pygmsh.generate_mesh` produces triangles, and running gmsh on the geo file produces quads. Note also that `verbose=True` (which is the default) prints the exact gmsh line.

**Comment by gdmcbain** [comment]
Thank you.  That's probably a useful feature to have anyway.  

I'll also try stepping through the call to `meshio.read` from `generate_mesh` with `pdb`.

**Comment by gdmcbain** [comment]
I found that it's the Gmsh command-line option `-optimize_lloyd 10` added by `generate_mesh` by default unless its option `num_quad_lloyd_steps` isn't > 0.  

With the default `num_quad_lloyd_steps=10`, `cells.keys() == ['triangle']` but on passing `num_quad_lloyd_steps=0`, it's ['vertex', 'line', 'quad'].  The following 

```python
    assert abs(compute_volume(points, cells) - ref) < 1.0e-2 * ref
```

then fails with

```
KeyError: 'triangle'
```

**Comment by gdmcbain** [comment]
So 

```python
    points, cells, _, _, _ = pygmsh.generate_mesh(geom,
                                                  dim=2,
                                                  num_quad_lloyd_steps=0,
                                                  geo_filename='quads.geo')
```

produces `cells` with `quad` instead of `triangle`.  This follows from that suppressing the passing of `-optimize_lloyd 10` as a default command-line argument to Gmsh in `generate_mesh`.

This then fails when `compute_volume` fails to find either `tetra` or `triangle` in `cells`, raising `KeyError('triangle',)`.  If the line 

```python
 assert abs(compute_volume(points, cells) - ref) < 1.0e-2 * ref
```

is skipped, `meshio.write('quads.vtu', points, cells)`, does the right thing, producing a two-dimensional unstructured mesh of quadrilaterals.

I'm not sure what the way forward is here:
* Is it necessary to both 
  * get `Recombine Surface` into the `_GMSH_CODE` and 
  * pass `num_quad_lloyd_steps=0` to `generate_mesh`?
* Should `compute_volume` be augmented to handle quadrilateral elements or should a different test used for this case?

**Comment by gdmcbain** [comment]
If I modify `generate_mesh` to check the code for `Recombine Surface`:

```python
  if num_quad_lloyd_steps > 0 and ('Recombine Surface'
                                     not in geo_object.get_code()):
        cmd += ['-optimize_lloyd', str(num_quad_lloyd_steps)]
```

then the unwanted command-line option is omitted and `num_quad_lloyd_steps=0` doesn't have to be passed in, so it's just:

```python
    points, cells, _, _, _ = pygmsh.generate_mesh(geom, dim=2)
```

Is that reasonable?  The Gmsh documentation on Lloyd-optimization is terse; I'm not sure quite what it does besides defeating the recombination.

**Comment by nschloe** [comment]
> Should compute_volume be augmented to handle quadrilateral elements or should a different test used for this case?

I'm on this right now.

**Comment by nschloe** [comment]
Alright, quad volume computation is in master now.

Let's make sure that pygmsh can actually generate quad meshes now. (Great idea btw!) I'm baffled by the fact that `-optimize_lloyd` should prevent recombination. In fact, this very function was _created_ to make quad recombination easier! (It rearranges the mesh such that pairs of triangles form approximate quads.) Hm. Perhaps we'll have to reread documentation on this again.

**Comment by gdmcbain** [comment]
Thanks for #119 , that enabled me to re-enable the standard compute_volume test in test_quads.py in 7fff6cf0fddf1cda5728b6116d8f0cfbb339d7b7.

So master pygmsh can generate quad meshes now: just pass `num_quad_lloyd_steps=0` to `generate_mesh`, but yes it would be nice to obviate that, and probably not by the kludge currently in pygmsh/helpers.py in 154e8f1747b03f40d48522c33d68502953e769ae, only enabling `-optimize_lloyd` if

```python
    'Recombine Surface' not in geo_object.get_code()
```

Shouldn't take too long to reread the [Gmsh documentation](http://gmsh.info/doc/texinfo/gmsh.html), I think it's just:

[`-optimize_lloyd`](http://gmsh.info/doc/texinfo/gmsh.html#index-_002doptimize_005flloyd) 

>     Optimize 2D meshes using Lloyd algorithm 
> 

and

[`Mesh.Lloyd`](http://gmsh.info/doc/texinfo/gmsh.html#index-Mesh_002eLloyd)
 
>     Apply lloyd optimization on surface meshes
>     Default value: 0
>     Saved in: `General.OptionsFileName`

but there are [several references in the mailing list archive](http://onelab.info/search/search.cgi?q=lloyd&ps=10&ul=%2Fpipermail%2Fgmsh); I'll sift through them and then post a query there or file a bug.

**Comment by nschloe** [comment]
> So master pygmsh can generate quad meshes now:

Alright, let's get it in then; if only in form of a test. I think this would be a nice addition, perhaps even worthy of the main readme.

**Comment by gdmcbain** [comment]
Some notes from the mailing list on Lloyd-optimization.

* C. Geuzaine on ‘Lloyd mesh optimization for extruded geometry’ ([2013-01-31](http://onelab.info/pipermail/gmsh/2013/007823.html)):

> don't use optimize_lloyd yet--it's very, well, how should I say... experimental ;-) ?

* J. Assael on ‘Auto 2D Mesh CellSize Optimization’ ([2014-02-25](http://onelab.info/pipermail/gmsh/2014/008834.html)):

> …but didnt manage to get it working with also the lloyd optimization option.

* C. Guezaine on ‘Optimize High Quality 2D Mesh’ ([2014-03-02](http://onelab.info/pipermail/gmsh/2014/008846.html)):

> Lloyd smoothing is still quite experimental.

* N. Schlömer on ‘mesh smoothing, voropy’ ([2017-02-23](http://onelab.info/pipermail/gmsh/2017/011113.html)):

> I spent some time getting a Lloyd-type smoother for 2D meshes to work, it's now part of voropy…It's substantially faster than Gmsh's smoother. … In any case, I was able to improve all of the 2D
meshes that come out of Gmsh.

* C. Geuzaine on ‘Lloyd smoothing broken?’ ([2017-03-08](http://onelab.info/pipermail/gmsh/2017/011147.html)):

> It's not a bug, it's a feature (for quad mesh generation). See http://link.springer.com/chapter/10.1007%2F978-3-642-24734-7_26 for some context.

* C. Geuzaine on ‘Segfault with Lloyd optimization’ ([2017-04-13](http://onelab.info/pipermail/gmsh/2017/011254.html)):

> But don't use LLoyd: it's experimental and only for generating quad-meshes.

Hmm, not sure whether I'm any the wiser for that; I'll write the list.

**Comment by gdmcbain** [comment]
http://onelab.info/pipermail/gmsh/2017/011814.html

**Comment by nschloe** [comment]
Great, thanks for the good work!

I'll hold out a day or two for a reply on the mailing list until I merge the PR.

**Comment by nschloe** [comment]
I've merged this now; let's follow up on the optimize-lloyd issue [here](https://github.com/nschloe/pygmsh/issues/124).
