### ISSUE TITLE
Is Gmsh version 3 required to use opencascade features?

### ISSUE THREAD

**Issue by Chaztikov** [nschloe/pygmsh#125]
Hi again,

First, quickly: do we need gmsh version 3 to use pygmsh?

I ran pytest and received:
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/chaztikov/anaconda3/pkgs/pygmsh, inifile:
collected 32 items                                                             

test/test_airfoil.py F                                                   [  3%]
test/test_boundary_layers.py F                                           [  6%]
test/test_bsplines.py F                                                  [  9%]
test/test_circle.py F                                                    [ 12%]
test/test_cube.py *** Error in `gmsh': free(): invalid pointer: 0x00007fba2f71a348 ***
======= Backtrace: =========

Not sure if this is an issue with my gmsh install or pygmsh, but I was wondering if you might have some insight?

My original question:

As far as I know I have opencascade and gmsh (installed from Synaptic Package Manager) and pygmsh (installed through anaconda I believe) and I get this error not only when trying to use the opencascade feature, but also when I try to create something simple, say, an ellipsoid without opencascade features.

In particular, when I run test_opencascade_ball.py I get

Info    : Running 'gmsh -3 -bin /tmp/tmp50u0hdt8.geo -o /tmp/tmp4pnhhetn.msh -optimize -optimize_lloyd 10' [Gmsh 2.10.1, 1 node, max. 1 thread]
Info    : Started on Fri Dec 15 20:58:53 2017
Info    : Reading '/tmp/tmp50u0hdt8.geo'...
Error   : '/tmp/tmp50u0hdt8.geo', line 2 : syntax error (")
Error   : '/tmp/tmp50u0hdt8.geo', line 4 : Sphere 1 has to be defined using 2 points (center + any point) and not 7
Warning : '/tmp/tmp50u0hdt8.geo', line 5 : Unknown volume 1
Error   : '/tmp/tmp50u0hdt8.geo', line 5 : Unknown command on multiple shapes: 'PointsOf'
Info    : Done reading '/tmp/tmp50u0hdt8.geo'
Info    : Meshing 1D...
Info    : Done meshing 1D (0 s)
Info    : Meshing 2D...
Info    : Done meshing 2D (5.96046e-06 s)
Info    : Meshing 3D...
Info    : Done meshing 3D (0 s)
Info    : 0 vertices 0 elements
Info    : Writing '/tmp/tmp4pnhhetn.msh'...
Info    : Done writing '/tmp/tmp4pnhhetn.msh'
Info    : Stopped on Fri Dec 15 20:58:53 2017
Traceback (most recent call last):
  File "test_opencascade_ball.py", line 31, in <module>
    meshio.write('opencascade_ball.vtu', *test())
  File "test_opencascade_ball.py", line 24, in test
    points, cells, _, _, _ = pygmsh.generate_mesh(geom)
  File "/usr/local/lib/python3.5/dist-packages/pygmsh/helpers.py", line 131, in generate_mesh
    'Gmsh exited with error (return code {}).'.format(p.returncode)
AssertionError: Gmsh exited with error (return code 1).
  

Insight is appreciated, thanks!

Update: it seems there is a greater issue at hand, 
pytest result :
======================================================================= 18 failed, 1 passed, 13 skipped, 1 warnings in 66.57 seconds =======================================================================

**Comment by nschloe** [comment]
Yep, you'll need gmsh 3 for opencascade. Also, older gmsh versions are prone to this kind of memory errors. Best upgrade an try again.

**Comment by Chaztikov** [comment]
Thanks for your swift response, I installed gmesh 3.0.7 and also
(re)installed opencascade.  Trying to be safe, I sudo apt-get updated,
deleted my pygmsh build and rebuilt and installed and pip installed it with
anaconda activated

I tried running the test_opencascade_ball.py and I got:


Info    : Running 'gmsh -3 -bin /tmp/tmphosm8q4c.geo -o
/tmp/tmp7noy33he.msh -optimize_lloyd 10' [Gmsh 3.0.7, 1 node, max. 1 thread]
Info    : Started on Sat Dec 16 12:57:27 2017
Info    : Reading '/tmp/tmphosm8q4c.geo'...
*Error   : Gmsh requires OpenCASCADE to add sphere*
*Error   : '/tmp/tmphosm8q4c.geo', line 4 : Could not add sphere*
*Error   : Unknown model region with tag 1*
*Error   : '/tmp/tmphosm8q4c.geo', line 5 : Could not apply operation on
shapes*
Info    : Done reading '/tmp/tmphosm8q4c.geo'
Info    : Meshing 1D...
Info    : Done meshing 1D (0 s)
Info    : Meshing 2D...
Info    : Done meshing 2D (0 s)
Info    : Meshing 3D...
Info    : Done meshing 3D (0 s)
Info    : 0 vertices 0 elements
Info    : Writing '/tmp/tmp7noy33he.msh'...
Info    : Done writing '/tmp/tmp7noy33he.msh'
Info    : Stopped on Sat Dec 16 12:57:27 2017
Info    : No current model available: creating one
Traceback (most recent call last):
  File "test_opencascade_ball.py", line 26, in <module>
    meshio.write('opencascade_ball.vtu', *test())
  File "test_opencascade_ball.py", line 18, in test
    pygmsh.generate_mesh(geom)
  File
"/home/chaztikov/anaconda3/lib/python3.6/site-packages/pygmsh/helpers.py",
line 131, in generate_mesh
    'Gmsh exited with error (return code {}).'.format(p.returncode)
AssertionError: Gmsh exited with error (return code 1).

Any idea why this might be?

I also ran it with pytest:


chaztikov@liberty-desktop:~/Documents/code/learn_libmesh/my_examples/pygmsh_generate$
pytest test_opencascade_ball.py
===========================================================================================
test session starts
============================================================================================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir:
/home/chaztikov/Documents/code/learn_libmesh/my_examples/pygmsh_generate,
inifile:
collected 1 item



test_opencascade_ball.py F

=================================================================================================
FAILURES
=================================================================================================
___________________________________________________________________________________________________
test
___________________________________________________________________________________________________

    def test():
        geom = pygmsh.opencascade.Geometry()

        geom.add_ball(
            [0.0, 0.0, 0.0], 1.0, x0=-0.9, x1=+0.9,
            alpha=0.5*pi,
            char_length=0.1
            )

        ref = 0.976088698545
>       pygmsh.generate_mesh(geom)

test_opencascade_ball.py:18:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

geo_object = <pygmsh.opencascade.geometry.Geometry object at
0x7f16b7c05e80>, optimize = True, num_quad_lloyd_steps = 10,
num_lloyd_steps = 1000, verbose = True, dim = 3, prune_vertices = True
gmsh_path = None

    def generate_mesh(
            geo_object,
            optimize=True,
            num_quad_lloyd_steps=10,
            num_lloyd_steps=1000,
            verbose=True,
            dim=3,
            prune_vertices=True,
            gmsh_path=None
            ):
        handle, geo_filename = tempfile.mkstemp(suffix='.geo')
        os.write(handle, geo_object.get_code().encode())
        os.close(handle)

        handle, msh_filename = tempfile.mkstemp(suffix='.msh')
        os.close(handle)

        gmsh_executable = gmsh_path if gmsh_path is not None else
_get_gmsh_exe()

        cmd = [
            gmsh_executable,
            '-{}'.format(dim), '-bin', geo_filename, '-o', msh_filename
            ]

        gmsh_major_version = get_gmsh_major_version(gmsh_executable)
        if gmsh_major_version < 3 and optimize:
            cmd += ['-optimize']

        if num_quad_lloyd_steps > 0:
            cmd += ['-optimize_lloyd', str(num_quad_lloyd_steps)]

        # http://stackoverflow.com/a/803421/353337
        p = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
            )
        if verbose:
            while True:
                line = p.stdout.readline()
                if not line:
                    break
                print(line.decode('utf-8'), end='')

        p.communicate()
        assert p.returncode == 0, \
>           'Gmsh exited with error (return code {}).'.format(p.returncode)
E       AssertionError: Gmsh exited with error (return code 1).

../../../../../anaconda3/lib/python3.6/site-packages/pygmsh/helpers.py:131:
AssertionError
-------------------------------------------------------------------------------------------
Captured stdout call
-------------------------------------------------------------------------------------------
Info    : Running 'gmsh -3 -bin /tmp/tmpc_zb8xzn.geo -o
/tmp/tmp3xwp_ke5.msh -optimize_lloyd 10' [Gmsh 3.0.7, 1 node, max. 1 thread]
Info    : Started on Sat Dec 16 13:01:13 2017
Info    : Reading '/tmp/tmpc_zb8xzn.geo'...
Error   : Gmsh requires OpenCASCADE to add sphere
Error   : '/tmp/tmpc_zb8xzn.geo', line 4 : Could not add sphere
Error   : Unknown model region with tag 1
Error   : '/tmp/tmpc_zb8xzn.geo', line 5 : Could not apply operation on
shapes
Info    : Done reading '/tmp/tmpc_zb8xzn.geo'
Info    : Meshing 1D...
Info    : Done meshing 1D (0 s)
Info    : Meshing 2D...
Info    : Done meshing 2D (0 s)
Info    : Meshing 3D...
Info    : Done meshing 3D (0 s)
Info    : 0 vertices 0 elements
Info    : Writing '/tmp/tmp3xwp_ke5.msh'...
Info    : Done writing '/tmp/tmp3xwp_ke5.msh'
Info    : Stopped on Sat Dec 16 13:01:13 2017
Info    : No current model available: creating one
=========================================================================================
1 failed in 0.74 seconds
=========================================================================================
chaztikov@liberty-desktop
:~/Documents/code/learn_libmesh/my_examples/pygmsh_generate$

**Comment by nschloe** [comment]
Well, the error message says it all:
```
*Error   : Gmsh requires OpenCASCADE to add sphere*
```

**Comment by Chaztikov** [comment]
Good point, it seems I installed these in the wrong order, I'll give it
another try.  Thanks!

**Comment by Chaztikov** [comment]
Sorry, I hate to be a bother, but I'm really intent on using your code!

I reinstalled gmsh and specified opencascade, it seems to have detected it
during installation

I reinstalled pygmsh, but I am still getting errors:

chaztikov@liberty-desktop:~/anaconda3/pkgs/pygmsh/test$ python3
test_circle.py
Info    : Running 'gmsh -3 -bin /tmp/tmpmmow2dgv.geo -o
/tmp/tmphjuc33d9.msh -optimize_lloyd 10' [Gmsh 3.0.7, 1 node, max. 1 thread]
Info    : Started on Sun Dec 17 23:17:46 2017
Info    : Reading '/tmp/tmpmmow2dgv.geo'...
Error   : '/tmp/tmpmmow2dgv.geo', line 21 : Compounds entities are
deprecated: use Compound meshing constraints instead
Error   : Unknown curve 5
Info    : Done reading '/tmp/tmpmmow2dgv.geo'
Info    : Meshing 1D...
Info    : Meshing curve 1 (Circle)
Info    : Meshing curve 2 (Circle)
Info    : Meshing curve 3 (Circle)
Info    : Meshing curve 4 (Circle)
Info    : Done meshing 1D (0 s)
Info    : Meshing 2D...
Info    : Meshing surface 6 (Plane, Delaunay)
Warning : Mesh Generation of Model Face 6 Skipped: Only 0 mesh vertices on
the contours
Warning : Surface 6 consists of no elements
Info    : Done meshing 2D (0 s)
Info    : Meshing 3D...
Info    : Done meshing 3D (0 s)
Info    : 65 vertices 69 elements
Warning : ------------------------------
Warning : Mesh generation error summary
Warning :     2 warnings
Warning :     0 errors
Warning : Check the full log for details
Warning : ------------------------------
Info    : Writing '/tmp/tmphjuc33d9.msh'...
Info    : Done writing '/tmp/tmphjuc33d9.msh'
Info    : Stopped on Sun Dec 17 23:17:46 2017
Info    : No current model available: creating one
Traceback (most recent call last):
  File "test_circle.py", line 30, in <module>
    meshio.write('circle.vtk', *test())
  File "test_circle.py", line 23, in test
    points, cells, _, _, _ = pygmsh.generate_mesh(geom)
  File
"/home/chaztikov/anaconda3/lib/python3.6/site-packages/pygmsh/helpers.py",
line 144, in generate_mesh
    'Gmsh exited with error (return code {}).'.format(p.returncode)
AssertionError: Gmsh exited with error (return code 1).

I can't seem to find the obvious issue here, any ideas?

Thanks again

**Comment by nschloe** [comment]
You're using a pre-release version of gmsh that breaks the API; hence the failure. Use 3.0.6.

**Comment by Chaztikov** [comment]
Aha, thank you Nico! I'll let you know how it goes this time.

**Comment by Chaztikov** [comment]
Sorry, again, I bring more trouble it seems:

chaztikov@liberty-desktop:~/anaconda3/pkgs/pygmsh/test$ python3
test_circle.py
Info    : Running 'gmsh -3 -bin /tmp/tmpm5jl5lh8.geo -o
/tmp/tmpjx43r73f.msh -optimize_lloyd 10' [Gmsh 3.0.6, 1 node, max. 1 thread]
Info    : Started on Mon Dec 18 12:29:01 2017
Info    : Reading '/tmp/tmpm5jl5lh8.geo'...
Info    : Done reading '/tmp/tmpm5jl5lh8.geo'
Info    : Finalized high order topology of periodic connections
Info    : Meshing 1D...
Info    : Meshing curve 1 (Circle)
Info    : Meshing curve 2 (Circle)
Info    : Meshing curve 3 (Circle)
Info    : Meshing curve 4 (Circle)
Info    : Meshing curve 5 (Compound curve)
Info    : Done meshing 1D (0 s)
Info    : Meshing 2D...
Info    : Meshing surface 7 (Plane, Delaunay)
Error   : Could not open file 'LloydInit.pos'
Lloyd: 0 11.771
Lloyd: 1 17.286
Lloyd: 2 20.248
Lloyd: 3 21.887
Lloyd: 4 22.286
Lloyd: 5 23.485
Lloyd: 6 24.065
Lloyd: 7 24.742
Lloyd: 8 24.263
Lloyd: 9 25.192
Lloyd: 10 25.832
Lloyd: 11 26.231
Lloyd: 12 26.877
Lloyd: 13 27.316
Lloyd: 14 27.952
Lloyd: 15 28.248
Lloyd: 16 29.027
Lloyd: 17 29.164
Info    : Meshing surface 7 (Plane, MeshAdapt)
Info    : Done meshing 2D (0.76 s)
Info    : Meshing 3D...
Info    : Done meshing 3D (0 s)
Warning : Could not orient normal of surface 7
Info    : 525 vertices 989 elements
Error   : ------------------------------
Error   : Mesh generation error summary
Error   :     1 warning
Error   :     1 error
Error   : Check the full log for details
Error   : ------------------------------
Info    : Writing '/tmp/tmpjx43r73f.msh'...
Info    : Done writing '/tmp/tmpjx43r73f.msh'
Info    : Stopped on Mon Dec 18 12:29:01 2017
Info    : No current model available: creating one
Traceback (most recent call last):
  File "test_circle.py", line 30, in <module>
    meshio.write('circle.vtk', *test())
  File "test_circle.py", line 23, in test
    points, cells, _, _, _ = pygmsh.generate_mesh(geom)
  File
"/home/chaztikov/anaconda3/lib/python3.6/site-packages/pygmsh/helpers.py",
line 144, in generate_mesh
    'Gmsh exited with error (return code {}).'.format(p.returncode)
AssertionError: Gmsh exited with error (return code 1).
chaztikov@liberty-desktop:~/anaconda3/pkgs/pygmsh/test$ ls
helpers.py               test_cube.py
test_meshio_logo.py          test_opencascade_cylinder.py
test_pipes.py                test_subdomains.py
test_airfoil.py          test_ellipsoid.py
test_opencascade_ball.py     test_opencascade_extrude.py
test_quads.py                test_swiss_cheese.py
test_boundary_layers.py  test_hole_in_square.py
test_opencascade_boolean.py  test_opencascade_torus.py
test_rectangle.py            test_tori.py
test_bsplines.py         test_layers.py
test_opencascade_box.py      test_opencascade_wedge.py
test_rectangle_with_hole.py  test_torus_crowd.py
test_circle.py           test_logo.py
test_opencascade_cone.py     test_pacman.py
test_screw.py                test_volume.py
chaztikov@liberty-desktop:~/anaconda3/pkgs/pygmsh/test$ sudo python3
test_opencascade_ball.py
Traceback (most recent call last):
  File "test_opencascade_ball.py", line 11, in <module>
    pygmsh.get_gmsh_major_version() < 3,
  File "/usr/local/lib/python3.5/dist-packages/pygmsh/helpers.py", line 81,
in get_gmsh_major_version
    stderr=subprocess.STDOUT
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['gmsh', '--version']' returned
non-zero exit status 127

**Comment by nschloe** [comment]
Just copy-and-pasting from the output:
```
Error   : Could not open file 'LloydInit.pos'
```

**Comment by Chaztikov** [comment]
Strange, I ran the ellipse test in another directory and it worked, I think
we can consider this solved, many thanks!

**Comment by nschloe** [comment]
Yup, you probably didn't have write access in the directory.
