### ISSUE TITLE
holes no longer respected in extrusion

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#129]
`Geometry.extrude` of a surface with a hole, as in `test_layers.py` or `test_screw.py`, doesn't quite respect the hole anymore.  The volume is toroidal but the far surface is simply connected.

This isn't caught by the test using `compute_volume`.

**Comment by capitalaslash** [comment]
this is not a problem of the extrusion, the simply connected face is the original one, see #131

**Comment by gdmcbain** [comment]
Quite so.  Silly me.  Thank you.
