### ISSUE TITLE
Spline not BSpline for built_in

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#135]
Often an interpolating spline is desired.  In Gmsh, with the default built-in factor, this is provided by [`Spline`](http://gmsh.info/doc/texinfo/gmsh.html#index-Spline-_0028-expression-_0029-_003d-_007b-expression_002dlist-_007d_003b) rather than [`BSpline`](http://gmsh.info/doc/texinfo/gmsh.html#index-BSpline-_0028-expression-_0029-_003d-_007b-expression_002dlist-_007d_003b); however, [`pygmsh/built_in`](pygmsh/built_in) currently only provides the latter.

As the .geo syntax is identical, this should be a straightforward addition.

This is a counterpart to #91 ‘Spline (not BSpline) for OpenCascade’.

**Comment by nschloe** [comment]
Thanks, fixed by #136.
