### ISSUE TITLE
built_in spline faulty assert

### ISSUE THREAD

**Issue by phbphy** [nschloe/pygmsh#150]
In built_in/spline.py:13, a check is made more than 3 points were passed as input. However, gmsh's spline works also with 3 (or even 2) points.

**Comment by nschloe** [comment]
Fixed now, thanks for the report.

**Comment by gdmcbain** [comment]
The offending [assert](https://github.com/nschloe/pygmsh/commit/ac86d0424c4e1ca160409cbc214fce34061d33c0#diff-f8ecdc6beebbf20e356448bc4833e938R13) was copied along with the rest of the class from [`pygmsh.built_in.Bspline`](https://github.com/nschloe/pygmsh/blob/ac86d0424c4e1ca160409cbc214fce34061d33c0/pygmsh/built_in/bspline.py).  Does it matter there?

I note that one can also define a BSpline in Gmsh with two points.

```C++
Point(1) = {0., 0., 0., 1.};
Point(2) = {1., 0., 0., 1.};
BSpline(1) = {1, 2};
```

But not one; that crashes Gmsh.  A one-point Spline is also invalid but gives an error without crashing.

**Comment by nschloe** [comment]
Alright, let's reintroduce the assert with `> 1` for both. I'll commit this one of these days. Thanks Geordie for following this up!
