### ISSUE TITLE
New versions of gmsh don't support -optimize_lloyd

### ISSUE THREAD

**Issue by kitchenknif** [nschloe/pygmsh#153]
New versions of gmsh have removed the "-optimize_lloyd" option, which breaks the default behavior of pygmsh (e.g. the two examples in README.md don't run without modification).

**Comment by nschloe** [comment]
What version of gmsh are you using?

**Comment by nschloe** [comment]
I'm guessing this must have changed sometime between the latest release 3.0.6 (against which we're testing) and current master. Yeah, so let's just remove it from pygmsh too.

**Comment by nschloe** [comment]
Alright, fixed now. Thanks for the report!
