### ISSUE TITLE
Getting structured square cells in mesh

### ISSUE THREAD

**Issue by tady57** [nschloe/pygmsh#155]
Hi, 

this is my python code (the important part):
`with open('proba.txt', 'r') as myfile:
	for line in myfile:
		if 'Surface' in line:
			
			Surface.append(find_id(line))
			geom.add_raw_code(line)
		
		else:
			geom.add_raw_code(line)

myfile.close() 

geom.add_raw_code('Mesh.Algorithm=8;')

for i in Surface:
	
	geom.add_raw_code('Recombine Surface {%s}=0;' %i)

points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)

meshio.write('test8.vtu', points, cells, cell_data=cell_data)
 
` 
And the pictures of  mesh I get: 
![nova4](https://user-images.githubusercontent.com/32203616/37094289-b4f59cea-2212-11e8-9c35-8a8b449cb333.PNG)

![nova5](https://user-images.githubusercontent.com/32203616/37094292-b9b7d7ac-2212-11e8-94cb-62f6f18139d0.PNG)

The problem is that I have to have all squares or rectangles in my mesh and I am not able to get squares and rectangles at some surfaces(picture above).  Do you have any advice how to repare that, which (py)gmsh command to use?

**Comment by nschloe** [comment]
Once again, let me refer you to https://guides.github.com/features/mastering-markdown/ for how to style code in GitHub markdown.

**Comment by nschloe** [comment]
Also, please read https://stackoverflow.com/help/mcve on how to create a verifiable example. Feel free to reopen with a code example that can be verified without `proba.txt`.

**Comment by tady57** [comment]
[proba.txt](https://github.com/nschloe/pygmsh/files/1789679/proba.txt) Here is the proba.txt file. It is basically copy paste .geo file with points, lines and surfaces (which I get from gmsh). Here is the whole python code:  

```python
import pygmsh
import numpy as np
import meshio
from math import pow
import string
import sys
import traceback
import helpers
import scipy


def find_id(s):
	string_helper=''
	if'Surface' in s:
		s=s[8:]
		for i in s:
			if not i==')':
				string_helper=string_helper+i
			else:break
	string_helper=int(string_helper)		
	return string_helper

geom = pygmsh.built_in.Geometry()

Surface=[]

with open('proba.txt', 'r') as myfile:
	for line in myfile:
		if 'Surface' in line:
			
			Surface.append(find_id(line))
			geom.add_raw_code(line)
		
		else:
			geom.add_raw_code(line)

myfile.close() 

geom.add_raw_code('Mesh.Algorithm=8;')


for i in Surface:
	
	geom.add_raw_code('Recombine Surface {%s}=0;' %i)


points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)

meshio.write('test8.vtu', points, cells, cell_data=cell_data)
```

**Comment by nschloe** [comment]
>>  [...] without proba.txt.
>
> Here is the proba.txt file. 

You're attaching a 2000-line data file? Good luck expecting anyone to dig through that. I certainly won't.

**Comment by tady57** [comment]
haha of course not. Nobody expecting you to go through that. It is fixed file with data from my professor. It must not be changed and it is here just to put geometry inside python code through geom.add_raw_code function. I put it here so you or someone else could compile my code and see the mesh. The problem is that on small examples it is very easy to get structed square mesh so my code's logic work perfectly. Maybe I should asked question like this: With fixed geometry and huge data what can I do to fix mesh - which algorithms to use, how to seperate surfaces so one algorithm works at one  surface and other algorithm at some other surface? I have the problem with the exact surface (from picture above). It creates some funny deformed triangular / quadrilateral mesh. 
Thank you for you time, I am sorry for my imprecision.

**Comment by nschloe** [comment]
> The problem is that on small examples it is very easy to get structed square mesh so my code's logic work perfectly. 

Well, if it works for small meshes but doesn't for "huge", then there must be one smallest mesh for which is it doesn't. It's your job then to isolate this case. And frankly speaking: I don't think it depends of the size of the mesh.

**Comment by nschloe** [comment]
Also, I got to say that you're using pygmsh very weirdly. I mean: You already have a geo-file, right? Why don't you just create the mesh with it? Instead of your whole code above, you just append a bunch of `Recombine Surface`s your geo file and be done with it.

**Comment by tady57** [comment]
@nschloe Yes I know it is very easy way,  but my professor gave me this .geo file and insists I have to use python

@phbphy  Thank you, I will try that

**Comment by nschloe** [comment]
> Yes I know it is very easy way, but my professor gave me this .geo file and insists I have to use python

I would be very interested to know why he makes you do that. To me, your code examples make no sense in pygmsh whatsoever.

**Comment by tady57** [comment]
Ok, I will talk to him and explane situation. I will let you know the answer. 

Thank you and have a nice evening

**Comment by tady57** [comment]
Hi, 
I talked with him and he was not very interested in how to use pygmsh properly-the only condition is to use pygmsh. I am new in all this so its hard to just find solution. But to have meaningfull code I decided to create my own geometry with data given to me. On this example I am not able to create quad mesh on the cube surface. How can I change geom.add_raw_code('Recombine Surface {%s};' %cube) to work?

```python
from helpers import compute_volume
import pygmsh
import numpy as np
import meshio
from math import pow
import string
import sys
import traceback
import helpers
import scipy

def test():
	lcar=pow(10,22)

    
	geom = pygmsh.built_in.Geometry()
	cube=geom.add_box(0, 1200, 0, 1200, 0, 1000, lcar)
	geom.add_raw_code('Recombine Surface {%s};' %cube)
	
	ref = 1.0
	points, cells, _, _, _ = pygmsh.generate_mesh(geom)
	#assert abs(compute_volume(points, cells) - ref) < 1.0e-2 * ref
	return points, cells


if __name__ == '__main__':
    import meshio
meshio.write('cube.vtu', *test())
```

**Comment by nschloe** [comment]
> How can I change geom.add_raw_code('Recombine Surface {%s};' %cube) to work?

This problem has nothing to do with pygmsh, more with gmsh itself. Ask them, perhaps they'll be able to help out. https://gitlab.onelab.info/gmsh/gmsh

> I talked with him and he was not very interested in how to use pygmsh properly-the only condition is to use pygmsh.

Wait. The head developer of the software tells you that this isn't how to do it, and he _still_ insists on using it this way? Please give me his name and his email address. (You can send it to nico.schloemer@gmail.com.)

**Comment by tady57** [comment]
Ok I will ask gmsh.

Thank you
