### ISSUE TITLE
create volume by rotating surface

### ISSUE THREAD

**Issue by r-maas** [nschloe/pygmsh#171]
I'm trying to create a volume by rotating a surface, and found out that for some reason using extrude with angle > pi doesn't work. An alternative way might be to divide up the rotation in four segments, and then join the segments. However, it seems the extrude command for an opencascade geometry only supports translations, not rotations.

Therefore, I create the four segments with a geom from pygmsh.built_in.Geometry() but now have to convert them to a pygmsh.opencascade.Geometry() (such that I can use boolean_union). I've tried add_volume but that doesn't work. Any idea's?

Thanks, 
Ruben

**Comment by nschloe** [comment]
> that for some reason using extrude with angle > pi doesn't work

Typical gmsh shortcoming. Bumped into this as well. Actually it doesn't even work for angle==pi, so you're doing the right thing in splitting it up into (at least 3) segments.

>  However, it seems the extrude command for an opencascade geometry only supports translations, not rotations.

A bunch of things may be missing here, indeed. It'd be great if you could provide a short Python code that produces and error, and I'll try to fix it.

**Comment by nschloe** [comment]
Oh, and you might want to check out https://github.com/nschloe/pygalmesh#rotation-bodies.

**Comment by r-maas** [comment]
Hi Nico, 

Thanks for the quick response. I've attached a short script that creates 4 volumes with the built_in geometry, and joins them in the opencascade geometry. Then generating a mesh fails (and I don't really know what to do with gmsh return codes).

Also thanks for pointing out pygalmesh! I didn't know about this before but I'm pretty sure that `pygalmesh.Polygon2D` combined with `pygalmesh.ring_extrude` exactly does what I hoped to achieve. 

Best regards,
Ruben

[mesh_conical_frustum.txt](https://github.com/nschloe/pygmsh/files/1931963/mesh_conical_frustum.txt)

**Comment by nschloe** [comment]
Could you make the example code shorter? I don't want to check the mesh plotting and such. Be minimal.

**Comment by r-maas** [comment]
OK, this is the minimal example that tries to join 4 volumes from the built_in geometry with the opencascade geometry:
```
import numpy as np
import pygmsh as pg
rz_array=np.array([[0.0,1.0],[2.5,1.0],[5,0.0],[0,0]]) #points in r,z format
vol_list=[]
geom_list=[]
N_sect=4;
for i in range(N_sect):
    t_angle=i*2.0*np.pi/N_sect
    geom = pg.built_in.Geometry()
    poly=geom.add_polygon([rz_array[:,0]*np.cos(t_angle),rz_array[:,0]*np.sin(t_angle),rz_array[:,1]],lcar=0.05)
    [t_surf,t_vol,_]=geom.extrude(poly,rotation_axis=[0,0,1],point_on_axis=[0,0,0],angle=1.0/2.0*np.pi)
    vol_list.append(t_vol)
    geom_list.append(geom)
geom2 = pg.opencascade.Geometry(characteristic_length_min=0.1,characteristic_length_max=0.1)
sect_list=[]
for i_sect in range(N_sect):
    sect_list.append(geom2.add_volume(vol_list[i_sect]))
union = geom2.boolean_union(sect_list)
points, cells, point_data, cell_data, field_data = pg.generate_mesh(geom2)
```

**Comment by balborian** [comment]
This is confusing, because he needs geom (with the built_in) to do the extrusion including rotation, but he also needs geom2 (opencascade) to do the boolean union. He can only use one to generate the mesh right?

**Comment by nschloe** [comment]
That's right. As far as I know, this is how gmsh works.
