### ISSUE TITLE
transforming circles

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#173]
In method `built_in.geometry.Geometry.add_circle` in 5520cfbf3633afc9be30902aee8da108ba1825b0, the optional linear transformation `R` changes the type of the two-dimensional array of vertex coordinates, `shape==(num_sections+1, 3)`, to a `len` `num_sections+1` list of shape (3,) coordinate arrays.
```python
        if R is not None:
            X = [numpy.dot(R, x) + x0 for x in X]
```

This was fine at the time since the only thing done with `X` thereafter was to iterate over its rows in a list-comprehension:
```python
p = [self.add_point(x, lcar) for x in X]
```
so either representation works the same; however, a94a8b15e09fd3be91b7c8abbd8a00187f639036 moved the central offset from before to after the transformation
```python
X += x0
```
and that behaves very differently for `X` `np.ndarray` (broadcast addition) or `list` (append).

I expect that this could be fixed by wrapping the list-comprehension with `numpy.vstack`, but I'm not sure exactly what the intent is here so I refrain from proposing a fix.  (Why is `x0` added twice `if R is not None`?  Should it be subtracted then added, so that the linear transformation is relative to the centre?)

Some of the tests relating to `add_circle`, such as `test_tori.py` are currently inoperative because broken by the issue with `Compound Line` which I suspect is related to #112, the default in `add_circle` being `compound=True`.

**Comment by gdmcbain** [comment]
To reproduce:
```python
from numpy import identity
from pygmsh.built_in import Geometry
Geometry().add_circle([0.]*3, 1., .1, identity(3))
```
which throws:
```
TypeError: 'float' object is not subscriptable
```
when `add_point` tries to interpret the individual coordinates of `x0` appended to `X` as points.

**Comment by nschloe** [comment]
Can this be closed now?

**Comment by gdmcbain** [comment]
Yes I think so.  The behaviour is covered by test_circle_transform.py #175 as well as by the tests on tori #177.
