### ISSUE TITLE
Conflicting IDs when mixing built-in and OpenCASCADE surfaces

### ISSUE THREAD

**Issue by kittychunk** [nschloe/pygmsh#178]
First of all, thank you for an excellent module! I have lost countless hours (and hair) over the years rolling my own Gmsh Python wrappers to automate geometry generation for computational mechanics simulations, and your tools definitely make life a lot easier.

A quick question - is it possible to mix and match functions from the built_in and opencascade modules in the same geometry? This is possible in native Gmsh but I'm getting an ID conflict when I try it in pygmsh. A minimal-ish example in which both square surfaces end up with the same ID, "s0", in the geo file:

```python
import pygmsh

geom = pygmsh.opencascade.Geometry()
p0 = geom.add_point([-0.1, -0.1, 0], 0.01)
p1 = geom.add_point([0.1, -0.1, 0], 0.01)
p2 = geom.add_point([0.1, 0.1, 0], 0.01)
p3 = geom.add_point([-0.1, 0.1, 0], 0.01)
l0 = geom.add_line(p0, p1)
l1 = geom.add_line(p1, p2)
l2 = geom.add_line(p2, p3)
l3 = geom.add_line(p3, p0)
ll0 = geom.add_line_loop([l0, l1, l2, l3])
square_builtin = geom.add_plane_surface(ll0)
square_opencascade = geom.add_rectangle([0, 0, 0], 0.5, 0.5)
geom.boolean_difference([square_opencascade], [square_builtin])

with open('id_failure_test.geo', 'w') as f:
    f.write(geom.get_code() + '\n')
```

The answer is probably RTFM but  [the documentation](https://pygmsh.readthedocs.io/en/latest/) seems to be MIA at the moment?

**Comment by nschloe** [comment]
Yeah that was a bug. Your excellent report made it easy tracking it down; thanks for that.

It's now merged and release, so simply updating should fix your issues.
