### ISSUE TITLE
Use mpi4py spawn to spawn gmsh processes

### ISSUE THREAD

**Issue by garth-wells** [nschloe/pygmsh#181]
This is rather niche, but calling pygmsh from within a MPI program will typically crash when `subprocess` calls `gmsh`.

Perhaps pygmsh could optionally use mpi4py `spawn` to call gmsh?

**Comment by nschloe** [comment]
I've looked at this again, and again couldn't get it to work with `spawn`. Perhaps someone with more knowledge of mpi4py could open a PR. Closing for now.
