### ISSUE TITLE
Possibility to create 2D quad meshes

### ISSUE THREAD

**Issue by tmaric** [nschloe/pygmsh#185]
Is there a possibility with the pygmsh to create 2D quad meshes by recombining 2D Delaunay cells?

I was searching for the "Recombine" option in the code, but all I found was [the hex test with the recombine option for 3D meshes](https://github.com/nschloe/pygmsh/blob/b711cfdd209572f875a946260c8d90e6929dc584/test/test_hex.py)

If this is not as of yet possible, I would be happy to code it, any pointers on where to start?

**Comment by nschloe** [comment]
Check https://github.com/nschloe/pygmsh/blob/master/test/test_quads.py.

**Comment by tmaric** [comment]
OK, I figured it out. Do you think it would make sense to add this as an example to README.md?

**Comment by nschloe** [comment]
If anyone else has the same problem, I might consider it. So far, everyone reading through the README found the link to the test/ directory.

**Comment by tmaric** [comment]
OK
