### ISSUE TITLE
save geo file

### ISSUE THREAD

**Issue by rvignolo** [nschloe/pygmsh#199]
Is there a way to store the .geo file instead of the mesh file?

I saw that the .geo file is created and located at /tmp but I have not seen any example showing how to store it.

In other words, is there a way to print and store the geom = pygmsh.built_in.Geometry() object.

Thanks!

**Comment by nschloe** [comment]
Check out the `geo_filename` argument in `generate_mesh()`.

**Comment by rvignolo** [comment]
oh thanks! I am sorry for asking. Thanks a lot again

**Comment by nschloe** [comment]
No problem.
