### ISSUE TITLE
pygmsh/gmsh doesn't handle 2d surface in 3d space

### ISSUE THREAD

**Issue by kayarre** [nschloe/pygmsh#208]
Using the example in the readme and augmenting the shape to a 2d surface in 3d without extrusion, it appears to not handle 2D surfaces?

```python
import pygmsh
import numpy as np

geom = pygmsh.built_in.Geometry()

# Draw a cross in 3d (45 degree rotation in x and y)
pts = [[-0.0707107,0.0207107,0.120711],
[-0.0707107,-0.120711,-0.0207107],
[0.0707107,-0.0207107,-0.120711],
[0.0707107,0.120711,0.0207107],
[0.0,0.353553,0.353553],
[-0.353553,-0.25,0.25],
[0.0,-0.353553,-0.353553],
[0.353553,0.25,-0.25]]

poly = geom.add_polygon(pts, lcar=0.05)

axis = [0, 0, 1]

# both give similar errors
points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom, dim=2)
points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom, dim=3)
```

for dim=2 and dim=3 the errors look like:
`Error   : Unable to recover the edge 183 (21/38) on GEdge 8 (on GFace 10)`

It's unclear if this is a gmsh issue or not, or if there is a proper better way to do this?

**Comment by nschloe** [comment]
It's a gmsh problem. Apparently it cannot mesh polygons that sit skewed in 3D space. The above example code works with
```python
    [0.0, 0.0, 0.0],
    [1.0, 0.0, 0.0],
    [1.0, 1.0, 0.0],
    [0.0, 1.0, 0.0],
```
however. My advice would be to create the mesh in 2D, and then simply rotate and translate the resulting point coordinates.
