### ISSUE TITLE
MSH4

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#209]
The production by default of the new (2018-08-22) [MSH file format (version 4)](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-_0028version-4_0029) by the new current stable release Gmsh 4.0.0 breaks most of the tests.  The call to `generate_mesh` gets Gmsh to generate MSH4 and then tries to call `meshio.read` on it but that insists on the legacy [MSH file format version 2](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-version-2), as reported in nschloe/meshio#280.

(Actually I'm running Gmsh 4.0.1-git-121425069, but I assume this also applies to current stable release Gmsh 4.0.0.)

To reproduce
```shell
python -m pytest -n auto test
```
or more simply
```shell
python test/test_airfoil.py
```
raises
> AssertionError: Need mesh format 2

I expect that fixing nschloe/meshio#280 will fix this.

**Comment by nschloe** [comment]
Let's close this now that the meshio bug is half fixed.

**Comment by gdmcbain** [comment]
This is hit by nschloe/meshio#284 too since `generate_mesh` (as called by `test_airfoil`) generates a binary MSH by default.

**Comment by gdmcbain** [comment]
Now most (37) of the tests are passing.   

Most of the 8 failures are related to compound entities #112 (which was put on hold awaiting Gmsh 3.1+, so might be revisited now). 
> Compounds entities are deprecated: use Compound meshing constraints instead, i.e. Compound Surface { ... };

However, there are a couple of others:
* `test_bsplines.`: `AssertionError` on volume
* `test_booleans` 
    * `KeyError: 'gmsh:physical'` in `test_fragments_diff_union` and `test_diff_physical_assignment`
    * `KeyError: 'gmsh:geometrical'` in `test_square_circle_slice`

I suspect the KeyErrors are related to MSH4 nschloe/meshio#280 or binary MSH4 nschloe/meshio#284.  The 'gmsh:physical' key is still breaking one of the examples in kinnala/scikit-fem#40 that relies on `pygmsh.generate_mesh` to define mixed boundary conditions.

**Comment by gdmcbain** [comment]
O. K, here are ASCII and binary MSH4 files with NodeData and ElementData.
* [ascii.tar.gz](https://github.com/nschloe/pygmsh/files/2330460/ascii.tar.gz)
* [binary.tar.gz](https://github.com/nschloe/pygmsh/files/2330461/binary.tar.gz)

I realized that I didn't know how to generate these in MSH4, so adapted [demos/api/view.py](https://gitlab.onelab.info/gmsh/gmsh/blob/master/demos/api/view.py), as included.  The mesh is four nodes and two triangular elements sharing an edge and forming a square.
![nodal_data](https://user-images.githubusercontent.com/1588947/44761506-c393a280-ab86-11e8-9a4b-9bb11dc5a04b.png)
![elemental_data](https://user-images.githubusercontent.com/1588947/44761505-c2fb0c00-ab86-11e8-9e04-651e515041d9.png)

**Comment by nschloe** [comment]
> The 'gmsh:physical' key

As far as I can tell, there are no such keys anymore in msh4. Perhaps in the `$Entities` section though?

**Comment by gdmcbain** [comment]
They're in there somewhere…  If I open `t1.msh` in binary MSH4 format in the Gmsh GUI and annotate the '1D element labels' by 'Physical tag', I can see 2, 2, 3, and 5, which are the right numbers.
![t1 physical-curves](https://user-images.githubusercontent.com/1588947/44770029-f69b5d80-aba9-11e8-99d0-5785d48174cf.png)

**Comment by gdmcbain** [comment]
Note that the '2' is an unnamed Physical Curve, from
```
MY_CURVE = 2;
Physical Curve(MY_CURVE) = {1,2} ;
```

**Comment by nschloe** [comment]
Ah, this is certainly the `tagEntity` at the beginning of each node/element section.

**Comment by gdmcbain** [comment]
Yes, I think so.  In `t1`, in `$Entities`, the four curves, numbered 1–4, have (with more Hollerithic spacing added by hand)
```
1 0    0    0 0.1 0    0 1 2 2 1 -2 
2 0.1 0    0 0.1 0.3 0 1 2 2 3 -2 
3 0    0.3 0 0.1 0.3 0 1 3 2 3 -4 
4 0    0    0 0    0.3 0 1 5 2 4 -1 
```
of which column 7 says they each have 1 `numPhysicals` which are 2, 2, 3, and 5, respectively.

**Comment by gdmcbain** [comment]
Or rather the `tagEntity` in the `$Elements` section refers to the `tag` in the `$Entities` section where the `numPhysical` values of `physicalTag` can be looked up.

**Comment by gdmcbain** [comment]
As a makeshift till `meshio.read` starts harvesting physical tags from the default intermediate MSH4 format (nschloe/meshio#289), and in cases for which `mesh_file_type="mesh"` #212 is inadequate (e.g. because the mesh contains elements of type not representable in MEDIT mesh, such as meshio's `("vertex", 1)`), it is possible to get `generate_mesh` to get Gmsh to use MSH2 with
```python
extra_gmsh_arguments=["-format", "msh2"]
```
I had [wondered](https://github.com/nschloe/pygmsh/issues/212#issuecomment-417205059) in #212 :
> Given two `-format` options on a Gmsh command line, which prevails?

The answer appears to be the latter.  A call like
```python
generate_mesh(geom, dim=1, extra_gmsh_arguments'=['-format', 'msh2'])
```
will issue a command-line like
```shell
gmsh -1 /tmp/tmp2m5hlr4i.geo -format msh -bin -o /tmp/tmpsnj73iqv.msh -format msh2
```
and generate `/tmp/tmpsnj73iqv.msh` in MSH2 rather than MSH4.
