### ISSUE TITLE
Python 3.5 support ?

### ISSUE THREAD

**Issue by nantille** [nschloe/pygmsh#21]
Hello,

When I try to pip install pygmsh (MacOS 10.10.5) that yields the following error:
ImportError: cannot import name 'HTTPSHandler'

I didn't find information on python version that you support, is it supposed to work on Python 3.x ?

**Comment by nschloe** [comment]
It's tested on Python 3 as well, so that should work. Perhaps [this](http://stackoverflow.com/a/20728240/353337) helps you.

Feel free to reopen if the issue persists.
