### ISSUE TITLE
add_volume from numpy 3d array

### ISSUE THREAD

**Issue by anildadj** [nschloe/pygmsh#210]
Hi,

I want to create a 3D volume and mesh it by inputting a numpy 3D array to pygmsh. Also, want to define surfaces on that volume with particular boundary conditions later to be input into an FEM workflow.

I could not find any example regarding the same. Any help is appreciated.

**Comment by nschloe** [comment]
This is way to unspecific. A numpy array for what? Better add a (small) code example.

**Comment by anildadj** [comment]
My structure of interest is enclosed in a bounding box defined by a boolean numpy 3D array of size (m x n x p), such that the array is all 1 (True) for the structure of interest and 0 (False) elsewhere.
I wish to mesh the volume described by 1's.
And also define two surfaces on this volume for unique boundary conditions. 
I hope I am clear OR else I shall provide code.

Thanks for the quick reply...

**Comment by nschloe** [comment]
> I wish to mesh the volume described by 1's.

As far as I know, that's not possible with gmsh, and hence neither with pygmsh.

I'm not aware of any mesh generator that accepts a Boolean array as input.
