### ISSUE TITLE
other intermediate formats for generate_mesh

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#212]
While stuck on MSH4 #209, held up upstream nschloe/meshio#280, @nschloe mentioned in nschloe/meshio#289 MEDIT's `mesh` format.  On looking into it in nschloe/meshio#290, it occurred to me that it might be a reasonable intermediate format for nine out of ten uses of `pygmsh.generate_mesh`.  I see that overriding `fast_conversion=False` gives `vtk` instead of `msh`.  What about generalizing that to allow the caller to try whatever?  I might try this out and see whether it fixes `test_booleans.test_diff_physical_assignment` and `test_booleans.test_fragments_diff_union`, flagged as failing in #209.

**Comment by nschloe** [comment]
I've always considered the intermediate mesh format an implementation detail. After all, the user never gets to see it. That's why the option was called `fast_conversion` and not `use_vtk` -- the latter may not mean much to the average user. However, I'm not at all opposed to the idea, perhaps with adding some documentation (which is sorely needed for `generate_mesh` anyway).

**Comment by gdmcbain** [comment]
Yes, I see.  I had been hoping to be able to just use `extra_gmsh_arguments` but it looks like the `if`–`else` for `fast_conversion` gets in the way.  (Given two `-format` options on a Gmsh command line, which prevails?)

There don't seem to be many formats in which Gmsh records its all-important physical tags.  Is it only MSHn and MEDIT mesh?  Although I did see https://gitlab.onelab.info/gmsh/gmsh/issues/389 about VTK.

**Comment by nschloe** [comment]
Okay, I'd suggest removing `fast_conversion` and replacing it my `mesh_file_type`, defaulting to `msh`. Plus a docstring that more or less repeats the comment
```
    # Gmsh's native file format `msh` is not well suited for fast i/o. This can 
    # greatly reduce the performance of pygmsh. As a workaround, use the VTK    
    # format. Unfortunately, gmsh doesn't support physical and geometrical tags 
    # for VTK yet. <https://gitlab.onelab.info/gmsh/gmsh/issues/389>
```

**Comment by nschloe** [comment]
Closing via #213.
