### ISSUE TITLE
test against current stable release of Gmsh?

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#215]
The fix for compound entity mesh constraints has arrived in Gmsh 4 and is implemented here in #214; however, it fails the continuous integration tests which rely on Ubuntu's packaged Gmsh which is version 3.0.6 and isn't compiled with PETSc.

Would it be reasonable to replace Ubuntu's Gmsh with the current stable release
http://gmsh.info/bin/Linux/gmsh-4.0.0-Linux64.tgz?  (Of course this might unleash other issues, e.g. related to MSH4 #209.)

**Comment by nschloe** [comment]
I think it'll be quite hard to support multiple gmsh versions at once; gmsh is simply to unstable as a software package, both in terms of backwards compatibility and the occasional segfaults. I wouldn't mind switching to the latest gmsh though. There's already work being done towards that in Debian, let me see if I can pack that into a launchpad PPA.

**Comment by nschloe** [comment]
As of #245, we're testing against gmsh 4.
