### ISSUE TITLE
return numeric identifiers of physical entities

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#216]
Currently `built_in.Geometry.add_physical_{point,line,surface,volume}` don't return anything.  The typical usage is to pass a `label` and remember that to be able to later access the physical entity.  

However, if using other intermediate formats for `pygmsh.generate_mesh` #212 besides Gmsh's native MSH, these `str` labels aren't stored in the mesh.  Here I mean not so much `mesh_file_type="vtk"`, which doesn't get the physical entities at all, but "mesh" which get the entities but only with an `int` tag and no `str`.

Perhaps these methods could be modified to return the entity or its numeric identifier in some way.

**Comment by gdmcbain** [comment]
This is to continue towards a makeshift for meshio not reading the physical entities from MSH4 #209 (nschloe/meshio#289 being incomplete), based on the use of `mesh_file_type="mesh"`.

**Comment by nschloe** [comment]
Is this still an issue with the new mesh formats?

**Comment by gdmcbain** [comment]
Since nschloe/meshio#289 (and then nschloe/meshio#331 for MSH4.1), was completed and merged, it has been possible to let `generate_mesh` let Gmsh write its default native MSHx.y and still return the tagged subsets of elements (in `cell_data[cell_type]["gmsh:physical"]`). Thus the makeshift of requiring other intermediate formats #212 kinnala/scikit-fem#40 is no longer needed.

The idea that methods that add physical entities return their identifiers seems reasonable and I don't think it would break anything but as there are no plans to use it, I'll close this issue.
