### ISSUE TITLE
test_bspline fails with Gmsh 4

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#220]
The interpretation of `BSpline` has changed somewhere between Gmsh 3.0.6 and Gmsh 4.0.1-git-296dd75f0.  This causes `test_bspline` to raise an `AssertionError` because the ‘volume’ (area) is quite different.

![bspline3 0 6](https://user-images.githubusercontent.com/1588947/45075912-ee07d180-b12b-11e8-97e4-0b6be5175be4.png)

*Figure:—* Gmsh 3.0.6

![bspline4 0 1](https://user-images.githubusercontent.com/1588947/45075911-ed6f3b00-b12b-11e8-8416-a21fced5c978.png)

*Figure:—* Gmsh 4.0.1-git-296dd75f0

The area of the latter is 0.7474554072002251, cf. `ref = 0.9156598733673261`, which looks reasonable for the former.

Not terribly pressing, I just wondered about this while chasing the other failures due to MSH4 #209 and obsolete compound entities #112 .

**Comment by nschloe** [comment]
Crazy. Thanks for producing such a nice example! @geuzaine Is this a gmsh bug?

**Comment by gdmcbain** [comment]
Here's the GEO file, extracted by running test/test_bspline in pdb and writing `geom.get_code()`.

[bspline.tar.gz](https://github.com/nschloe/pygmsh/files/2351612/bspline.tar.gz)

**Comment by geuzaine** [comment]
Hi Guys - Indeed, we changed the default parameters for the bspline interpolation to be consistent with what is done in most other CAD packages (in particular OpenCASCADE).

**Comment by nschloe** [comment]
Alright then. @gdmcbain, can you make a note about that in your PR? We can update the values as soon as gmsh 4 is in our tests.

**Comment by gdmcbain** [comment]
Thanks Christophe.  I mostly use Gmsh for geometry creation but occasionally I use FreeCAD and I did notice that the B-splines differed.

**Comment by gdmcbain** [comment]
> can you make a note about that in your PR? We can update the values as soon as gmsh 4 is in our tests.

How about using `get_gmsh_major_version` in the test?  #221  That's kind of self-documenting.  I suspect the transition to Gmsh 4 might take a while, given the new format MSH4 #209.

**Comment by nschloe** [comment]
@gdmcbain Well done.
