### ISSUE TITLE
How Pygmsh mesh a .*vtu file created by meshio?

### ISSUE THREAD

**Issue by SamTAOUM** [nschloe/pygmsh#229]
Hello,
I create a mesh with pygmsh that I change the coordinates of the points of mesh to my topologie of study.
I'm working to developp a FEM software on geophysics. I want to create mesh of order 2 or 3 for FEM.
The problem that I can't mesh it directly on order 2 by using " generate_mesh(geom, extra_gmsh_arguments=["-order", "2"])", cause the coordinates of points will be changed and than I lost the form of tetra10  in my mesh.
In GMSH, we can save than open a .msh file than mesh it into order 2. I'm looking to do the same in pygmsh using meshio. So my code:

_ first mesh
```
points, cells, ...= pygmsh.generate_mesh(geom, extra_gmsh_arguments=["-order", "1"])
```

_change coordinates of points (points--->newpoints)

_write vtu file with meshio
```
meshio.write_points_cells("mymesh.vtu",newpoints,cells,cell_data=cell_data)
```

how can I generate mesh to mymesh.vtu using pygmsh?
```
points, cells, ...= pygmsh.generate_mesh("mymesh.vtu", extra_gmsh_arguments=["-order", "2"])
```
??

![my_work](https://user-images.githubusercontent.com/44428415/47714487-4e535500-dc3d-11e8-886c-0e925b7ab6c4.png)

**Comment by nschloe** [comment]
> cause the coordinates of points will be changed and than I lost the form of tetra10 in my mesh.

I don't understand what that means.

> how can I generate mesh to mymesh.vtu using pygmsh?

What's the problem? You already described how to do it.

**Comment by SamTAOUM** [comment]
Hello

> points, cells, ...= pygmsh.generate_mesh("mymesh.vtu", extra_gmsh_arguments=["-order", "2"])

doesn't work.  `AttributeError: 'str' object has no attribute 'get_code'`

**Comment by nschloe** [comment]
Well you need to provide a geometry, right?

**Comment by SamTAOUM** [comment]
yes exactly

**Comment by nschloe** [comment]
Yeah so why don't you do it? You're using `generate_mesh` wrong.

**Comment by SamTAOUM** [comment]
I tried:

> geom_1 = pygmsh.built_in.Geometry()

> geom_1.add_raw_code( "mymesh.vtu")

> points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom_1, extra_gmsh_arguments=["-order", "2"])

but doesn't work

**Comment by nschloe** [comment]
This
```python
geom_1.add_raw_code( "mymesh.vtu")
```
doesn't make any sense at all. `"mymesh.vtu"` is not a valid gmsh command. I don't understand what you're trying to do.

**Comment by SamTAOUM** [comment]
hope, I explained clearly the problem

**Comment by nschloe** [comment]
> by opening a .*msh file to mesh it again on order 2.

pygmsh cannot _read_ meshes. You can only create a geometry and mesh that.

**Comment by SamTAOUM** [comment]
Okay, thank you for your explaination.
I'll try another solution to mesh my topologie of study on order 2 and 3.
