### ISSUE TITLE
Can't run example code

### ISSUE THREAD

**Issue by toothstone** [nschloe/pygmsh#234]
I hope I haven't missed something, but on running the example code from the README, I encounter the following error:

```
Traceback (most recent call last):
  File "pygmsh_test.py", line 33, in <module>
    meshio.write('test.vtu', points, cells, cell_data=cell_data)
  File "/home/toothstone/.virtualenvs/meshclick/lib/python3.7/site-packages/meshio/helpers.py", line 207, in write                            
    for key, value in mesh.cells.items():
AttributeError: 'numpy.ndarray' object has no attribute 'cells'
```
I tried some other simple meshes generated with pygmsh, same problem on writing with meshio.
The meshio-README example code runs fine, however.

I'm using python 3.7.1, numpy 1.15.4 and gmsh 4.0.7-1

**Comment by nschloe** [comment]
Which meshio version?

**Comment by toothstone** [comment]
meshio     2.3.3     
pygmsh     4.3.6     

Thank you for the quick reply!

**Comment by nschloe** [comment]
Everything looks good; no idea why this should happen. Perhaps because of gmsh 4? I'm only using gmsh 3.* (from Debian).

**Comment by toothstone** [comment]
I downgraded to 3.0.6, same result :/

**Comment by toothstone** [comment]
Tried it on jessie:
python 3.4.3
meshio 2.3.3
numpy 1.15.4
pygmsh 4.3.6
gmsh 2.8.3
Same problem.

**Comment by nschloe** [comment]
Still no idea why this should be happening.

**Comment by toothstone** [comment]
After starting my own script from scratch I realized the example code is simply slightly broken, I hope my PR solves that.

**Comment by nschloe** [comment]
I guess this can be closed now.
