### ISSUE TITLE
Add extrusion for points and lines

### ISSUE THREAD

**Issue by toothstone** [nschloe/pygmsh#236]
For generating meshes in a grid-like fashion, a lot of my gmsh code uses extrusion of points and lines like this:

```
pStart = newp; Point(pStart) = {0,0,0, lc};

out_lStart[] = Extrude {width, 0, 0}{ Point{pStart}; };
out_sStart[] = Extrude {0,0,thickness}{ Line{out_lStart[1]}; };
```

However, pygmsh currently only allows to extrude surfaces. Have you considered adding support for this? I think I could write a PR for it, just wanted to know if there are known problems with that or if I'm just holding it wrong and there is another way to do what I want which is already implemented.

**Comment by nschloe** [comment]
Good suggestion! Extrusion should work for all of the above. Feel free to open a PR.

**Comment by nschloe** [comment]
To be closed?

**Comment by toothstone** [comment]
Yes, forgot to mention the issue in my commit message. This use case is covered now.
