### ISSUE TITLE
distinguish format from suffix in generate_mesh

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#241]
`generate_mesh` has a keyword argument `mesh_file_type="msh"` which is used as both:
* the suffix of the [`NamedTemporaryFile`](https://docs.python.org/3/library/tempfile.html?highlight=namedtemporaryfile#tempfile.NamedTemporaryFile) for the mesh
* the argument to the [`-format`](http://gmsh.info/dev/doc/texinfo/gmsh.html#index-_002dformat-string) option in the constructed Gmsh command-line

However, for MSH2, the format should be `"msh2"` but the suffix `"msh"`.

As noticed in #240, passing `mesh_file_type="msh"` causes `meshio.read` to raise
> AssertionError: Could not deduce file format from extension '.msh2'.

**Comment by nschloe** [comment]
Fixed by https://github.com/nschloe/pygmsh/pull/242.
