### ISSUE TITLE
Problem with generate_mesh 

### ISSUE THREAD

**Issue by carlosantonio89** [nschloe/pygmsh#244]
Hi everybody,

I am new to pysgmsh and I'm trying the most simple example presented on the homepage:

```
import pygmsh
import numpy as np

geom = pygmsh.built_in.Geometry()

# Draw a cross.
poly = geom.add_polygon([
    [ 0.0,  0.5, 0.0],
    [-0.1,  0.1, 0.0],
    [-0.5,  0.0, 0.0],
    [-0.1, -0.1, 0.0],
    [ 0.0, -0.5, 0.0],
    [ 0.1, -0.1, 0.0],
    [ 0.5,  0.0, 0.0],
    [ 0.1,  0.1, 0.0]
    ],
    lcar=0.05
    )

axis = [0, 0, 1]

geom.extrude(
    poly,
    translation_axis=axis,
    rotation_axis=axis,
    point_on_axis=[0, 0, 0],
    angle=2.0 / 6.0 * np.pi
    )

points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)
```
I installed pygmsh via pip with python 3.7.2 on Windows 10 64 bits. After execute the above example a got the following error:

```
Traceback (most recent call last):
  File "C:/Users/carlos/Desktop/test_pymsh.py", line 30, in <module>
    points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)
  File "C:\Program Files\Python37\lib\site-packages\pygmsh\helpers.py", line 139, in generate_mesh
    [gmsh_executable] + args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
  File "C:\Program Files\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

How can I solve this issue?

Thanks in advance.

**Comment by gdmcbain** [comment]
Is Gmsh installed?

**Comment by carlosantonio89** [comment]
Yes. I just download the 64 bit binaries from they're website and executed gmsh.exe file. Do I need to compile it from the source?

**Comment by gdmcbain** [comment]
No, the binary should work fine. 

Is it on the `%PATH%`?

**Comment by carlosantonio89** [comment]
Yes. Path added but no success.

**Comment by gdmcbain** [comment]
Hmm… I'm don't use Windows everyday and am away from the office where I have access to a Windows machine, so I don't have the answers immediately on hand.. This should work though. 

So if you type 
```shell
gmsh
```
at the Windows  _Command Prompt_, it launches?

If yes, the next test after that will be to try calling Gmsh from Python with `subprocess`.

**Comment by carlosantonio89** [comment]
Problem solved! I had to different versions of Gmsh on my PATH. Deleting one of them solved the problem.

Thanks gdmcbain!
