### ISSUE TITLE
Is init-from-geo-file supported ?

### ISSUE THREAD

**Issue by fghoussen** [nschloe/pygmsh#249]
Is init-from-geo-file supported ?
My understanding is that no at the time (need to describe geometry).
If I am correct, is init-from-geo planned ? costly to integrate to existing code-base ?

Assuming you have a `tricky_geom.geo` file, would be nice to get mesh in python this way:

```
geom = pygmsh.built_in.Geometry().set_code('tricky_geom.geo')
points, cells, _, _, _ = pygmsh.generate_mesh(geom, prune_vertices=False)
for cell in cells:
    print(cell) # do stuffs here with cell
```

**Comment by nschloe** [comment]
You mean you already have a geo file on disk and just want to convert it to mesh data in Python?

**Comment by fghoussen** [comment]
Yes !... And browsing more the doc I guess `geom = pygmsh.built_in.Geometry().add_raw_code('tricky_geom.geo')` may be the answer ?!... :D

**Comment by fghoussen** [comment]
Or maybe more like that ?

```
geom = pygmsh.built_in.Geometry()
for line in open('tricky_geom.geo').readlines():
    geom.add_raw_code(line)
points, cells, _, _, _ = pygmsh.generate_mesh(geom, prune_vertices=False)
for cell in cells:
    print(cell) # do stuffs here with cell
```

**Comment by nschloe** [comment]
Yeah you can do that but honestly: No need for pygmsh. Just call gmsh via subprocess on your file, and then use meshio to read the mesh. That's exactly what pygmsh does, too; check out https://github.com/nschloe/pygmsh/blob/master/pygmsh/helpers.py#L146.

**Comment by fghoussen** [comment]
OK thanks ! If I got it well `meshio` is another python package (didn't know this one), right ?

**Comment by nschloe** [comment]
https://github.com/nschloe/meshio
