### ISSUE TITLE
generate_mesh

### ISSUE THREAD

**Issue by arrran** [nschloe/pygmsh#250]
Very simple question - how do I do the equivalent of 
```
gmsh input_file.geo -1 -2
```
with pygmsh. 
I would like to output a 2D .msh file

i cant find any documentation on generate_mesh so am using get_code() to output a .geo file, then using gmsh in the shell to make a 2D mesh, but I assume this is all possible with pygmsh

Thanks very much,
arran

**Comment by nschloe** [comment]
Why is `generate_mesh` not good enough?

**Comment by arrran** [comment]
generate_mesh gives me 3D and i only want 2D

**Comment by nschloe** [comment]
Ah, so that works? You specify a geometry, do `-2` and only get the shell? Didn't know that. Do you really need the `-1` there?

**Comment by nschloe** [comment]
Well anyway, you can just specify `dim`. See https://github.com/nschloe/pygmsh/blob/master/pygmsh/helpers.py#L80.

**Comment by arrran** [comment]
Okay great, clearly

thanks very much
