### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'gmsh': 'gmsh'

### ISSUE THREAD

**Issue by ArnoiZ** [nschloe/pygmsh#251]
Hi, I tried to run the example code:
```
import pygmsh
import numpy as np

geom = pygmsh.built_in.Geometry()

# Draw a cross.
poly = geom.add_polygon([
    [ 0.0,  0.5, 0.0],
    [-0.1,  0.1, 0.0],
    [-0.5,  0.0, 0.0],
    [-0.1, -0.1, 0.0],
    [ 0.0, -0.5, 0.0],
    [ 0.1, -0.1, 0.0],
    [ 0.5,  0.0, 0.0],
    [ 0.1,  0.1, 0.0]
    ],
    lcar=0.05
    )

axis = [0, 0, 1]

geom.extrude(
    poly,
    translation_axis=axis,
    rotation_axis=axis,
    point_on_axis=[0, 0, 0],
    angle=2.0 / 6.0 * np.pi
    )

points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)
```
But I got the following error message:
```
Traceback (most recent call last):
  File "/Users/ming/Documents/Project/Tidal-simulation/test.py", line 30, in <module>
    points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygmsh/helpers.py", line 147, in generate_mesh
    [gmsh_executable] + args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gmsh': 'gmsh'
```
How can I solve this problem?

**Comment by nschloe** [comment]
Looks very much like you don't have gmsh installed.

**Comment by ArnoiZ** [comment]
Oops, my bad. Thank you very much.

**Comment by Zty3616** [comment]
> Looks very much like you don't have gmsh installed.

Hi! My situation is that I have installed gmsh 4.1.3 and I also went to the helpers.py to set default value of gmsh_path as the gmsh's path in my computer. But it still didn't work. I don't know what the problem is. My system is windows10. Can you help me?
![image](https://user-images.githubusercontent.com/48903741/54900684-32fc2580-4f0f-11e9-9dda-9624376fe01c.png)

**Comment by Zty3616** [comment]
> Looks very much like you don't have gmsh installed.
The Traceback is as follows, 
![image](https://user-images.githubusercontent.com/48903741/54900800-8f5f4500-4f0f-11e9-8d21-00967e9a8039.png)
The chinese character in the last line means 'The system cannot find the file specified.'

**Comment by nschloe** [comment]
First off all, you don't need to modify pygmsh's code. Just pass the argument `gmsh_path="C:\\..."` to `generate_mesh`.

The error you're getting means that you specified a faulty path.

**Comment by Zty3616** [comment]
> First off all, you don't need to modify pygmsh's code. Just pass the argument gmsh_path="C:\\..." to generate_mesh.
> The error you're getting means that you specified a faulty path.

Got it, thank you very much!
