### ISSUE TITLE
Question about creating a mesh for a 2D surface

### ISSUE THREAD

**Issue by ArnoiZ** [nschloe/pygmsh#252]
Hi, I am new to mesh. And I am trying to create a 2D mesh with coordinates looks like this
<img width="640" alt="スクリーンショット 2019-03-23 13 09 29" src="https://user-images.githubusercontent.com/25852180/54861489-eaa50200-4d6c-11e9-971f-6b0504ba72c1.png">
I tried the following code:
```
# create list of points
point_list = []
for i in range(len(data)):
    point_list.append([data['p_lat'][i], data['p_lon'][i], 0.0])

# generate mesh
geom = pg.built_in.Geometry()
poly = geom.add_polygon(point_list, lcar=0.05)
```
But I don't know how to continue to generate the mesh for the polygon. Could you please shed some light for me? Also, could you explain what does the parameter `lcar` means? I couldn't found explanation for it in the document.

Thank you very much.

**Comment by nschloe** [comment]
Easy:
```python
import pygmsh

data = {
    "p_lat": [0.0, 1.0, 1.0, 0.0],
    "p_lon": [0.0, 0.0, 1.0, 1.0],
}

point_list = []
for i in range(4):
    point_list.append([data['p_lat'][i], data['p_lon'][i], 0.0])

# generate mesh
geom = pygmsh.built_in.Geometry()
poly = geom.add_polygon(point_list, lcar=0.1, make_surface=True)

pts, cells, _, _, _ = pygmsh.generate_mesh(geom)
```
`lcar` is the gmsh lingo, meaning _characteristic length_ near the entity you specify. Choosing a smaller value will result in a finer mesh.

**Comment by ArnoiZ** [comment]
Got it, thank you very much!

**Comment by ArnoiZ** [comment]
Hi Nico,

I tried the upper code and after two hours it threw out the following error. 
```
Info    : Meshing surface 63578 (Plane, Delaunay)
Traceback (most recent call last):
Error   : Unable to recover the edge 169075 (61/61) on curve 47952 (on surface 63578)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
Info    : Done meshing 2D (2892.44 s)
    exec(code_obj, self.user_global_ns, self.user_ns)
Info    : Meshing 3D...
  File "<ipython-input-4-e0883473eb2b>", line 5, in <module>
Info    : Done meshing 3D (2.9e-05 s)
    points, cells, _, _, _ = pg.generate_mesh(geom)
Info    : 136758 vertices 200334 elements
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygmsh/helpers.py", line 158, in generate_mesh
Error   : ------------------------------
    p.returncode
Error   : Mesh generation error summary
Error   :     0 warnings
Error   :     1 error
AssertionError: Gmsh exited with error (return code 1).
Error   : Check the full log for details
Error   : ------------------------------
Info    : Writing '/var/folders/35/3w_m9rnj5qq7vv6bv07d6yq00000gn/T/tmpf5pmdaw3.msh'...
Info    : Done writing '/var/folders/35/3w_m9rnj5qq7vv6bv07d6yq00000gn/T/tmpf5pmdaw3.msh'
Info    : Stopped on Sun Mar 24 13:56:52 2019
```
I think the problem is that what I did was inputing all the 'boundary' points and let `pygmsh` to create inner points to fill the surface. 
But what I actually wanted to do was to input all the points and connect them to each other to generate a surface mesh. Is there a way to do so?

Best regards,

Ming

**Comment by nschloe** [comment]
> But what I actually wanted to do was to input all the points and connect them to each other to generate a surface mesh. Is there a way to do so?

You're looking for triangulating a point cloud. [qhull](http://www.qhull.org/) does that, but only for convex sets. I don't know of algorithms generating meshes for point clouds of non-convex sets (as you appear to have).
