### ISSUE TITLE
ValueError: not enough values to unpack (expected 1, got 0)

### ISSUE THREAD

**Issue by Zty3616** [nschloe/pygmsh#253]
Dear pygmsh users, I have just run the this example and I met this problem.

```python
import pygmsh
import numpy as np

geom = pygmsh.built_in.Geometry()

# Draw a cross.
poly = geom.add_polygon([
    [ 0.0,  0.5, 0.0],
    [-0.1,  0.1, 0.0],
    [-0.5,  0.0, 0.0],
    [-0.1, -0.1, 0.0],
    [ 0.0, -0.5, 0.0],
    [ 0.1, -0.1, 0.0],
    [ 0.5,  0.0, 0.0],
    [ 0.1,  0.1, 0.0]
    ],
    lcar=0.05
    )

axis = [0, 0, 1]

geom.extrude(
    poly,
    translation_axis=axis,
    rotation_axis=axis,
    point_on_axis=[0, 0, 0],
    angle=2.0 / 6.0 * np.pi
    )


points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom)
```
The trackback is as follows. I don't the reason, can you help me?
![image](https://user-images.githubusercontent.com/48903741/54903974-292af000-4f18-11e9-8002-cfe9de62ce28.png)

**Comment by nschloe** [comment]
It's an error in meshio, wait for https://github.com/nschloe/meshio/pull/365.

**Comment by nschloe** [comment]
Fixed now, simply upgrade to meshio 2.3.7 and it should all work.

**Comment by Zty3616** [comment]
Succeed! Thank you for your help!

**Comment by Zty3616** [comment]
> Fixed now, simply upgrade to meshio 2.3.7 and it should all work.

Succeed! Thank you for your help!

**Comment by Zty3616** [comment]
Hi! I have another question. After the execution of the above code is completed, how can I find the corresponding .geo file and the .msh file?

**Comment by nschloe** [comment]
You can provide the `geo_filename` argument to store the geo file. You can use that to regenerate the msh file.

**Comment by Zty3616** [comment]
> You can provide the geo_filename argument to store the geo file. You can use that to regenerate the msh file.

Problems solved! Thank you very much again!
---------------------------------------------------------
To people who may ask the same question above, just do as follows,
![image](https://user-images.githubusercontent.com/48903741/54991981-15a38600-4ff9-11e9-98b0-0aaa22a4ad24.png)

**Comment by Zty3616** [comment]
Problems solved! Thank you very much again! 

To people who may ask the same questions above, just do as follows,

![image](https://user-images.githubusercontent.com/48903741/54992068-513e5000-4ff9-11e9-96da-39afb9ef7688.png)
