### ISSUE TITLE
#251 closed issue in ubuntu :No such file or directory: 'gmsh': 'gmsh'  

### ISSUE THREAD

**Issue by brioglade** [nschloe/pygmsh#254]
I  installed gmsh 4.1.5 and setted the correct path in the .bashrc file.
The error occur when I run the same example as #251 in spyder(anaconda3).

**Comment by nschloe** [comment]
From #251:

> First off all, you don't need to modify pygmsh's code. Just pass the argument gmsh_path="C:\\..." to generate_mesh.
