### ISSUE TITLE
How to get the volume which is created by extruding a surface

### ISSUE THREAD

**Issue by Zty3616** [nschloe/pygmsh#256]
Dear Pygmsher, 

Hi! I meet a problem when I try this:
```Python
outer_wall_volume = mf.create_p_l_s(model_settings, geom,
                                    text_name='outer_points_coordinates.txt')
inner_wall_volume = mf.create_p_l_s(model_settings, geom,
                                    text_name='inner_points_coordinates.txt')
wall = geom.boolean_difference(outer_wall_volume, inner_wall_volume)
```
In the above code, the function ```mf.create_p_l_s()``` is a user-defined-function by myself. And parts of this function's code is as follows:
```# Extrude a polygon
    axis = [0, 0, 15]
    outer_wall_volume = geom.extrude(outer_wall_poly, translation_axis=axis)

    return outer_wall_volume
```
```outer_wall_poly``` is a list of points needed for pygmsh method ```extrude```.
What I really want to do is that by extruding a surface to get a volume and name this volume with certain name like ```outer_wall_volume```. However, the python interpreter indicates that the returned ```outer_wall_volume``` is a ```Dummy``` object which is tuple having 3 elements within it:
![image](https://user-images.githubusercontent.com/48903741/55276865-e4e28a00-5333-11e9-94a2-f5c82ba7a193.png)
When I used method ```boolean_difference```, I got a Traceback as above.
How can I deal with this? All I want is just to get a volume extruded from a surface. 
Could you please help me?

**Comment by nschloe** [comment]
@Zty3616 I noticed you're using screenshots a lot. Best replace them with actual copied-and-pasted commands. They are searchable and more easily readable.

**Comment by nschloe** [comment]
Closing. Please reopen with an actual [MVCE](https://stackoverflow.com/help/mcve).
