### ISSUE TITLE
how to load a gmsh file

### ISSUE THREAD

**Issue by SBFRF** [nschloe/pygmsh#261]
this package looks like a great way to create the gmsh and save a gmsh,  is there a way to load a gmsh file?  I didn't see it in the documentation.

**Comment by gdmcbain** [comment]
As in a [MSH](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format) file?  Try [meshio](https://github.com/nschloe/meshio); it's what pygmsh uses internally for this purpose.

**Comment by gdmcbain** [comment]
Or as in a GEO file?

```python
geo = pygmsh.built_in.Geometry()

with open('t1.geo', 'r') as fin:
    geo._GMSH_CODE.append(fin.read())

mesh = pygmsh.generate_mesh(geo)
```

The leading underscore on the `._GMSH_CODE` attribute is a hint that this might not be a good idea, but it might work, as the above simple snippet does, depending on what is to be achieved.

**Comment by SBFRF** [comment]
Its a gmesh or i guess the MSH file looks similar.  meshio worked.  It might be worth putting a pointer into this README to let users know about this
