### ISSUE TITLE
Meshing a sphere creates extra points

### ISSUE THREAD

**Issue by clionFHR** [nschloe/pygmsh#262]
When I am meshing the surface of a sphere with pygmsh, I am getting points that do not belong to any of the triangles of the mesh. Here is an example code:
```
def mesh_tri(geom, minedge,maxedge):
    return pygmsh.generate_mesh(geom, dim=2,
                                extra_gmsh_arguments=['-clmax', str(maxedge),'-clmin', str(minedge)],
                                verbose=False)
```
```
def mesh_sphere_tri(r=1,minedge=.1,maxedge=0.1):

    geom = pygmsh.built_in.Geometry()
    geom.add_ball([0,0,0], r)
    return mesh_tri(geom, minedge, maxedge)
```
```
import gmsh as gm

mesh = gm.mesh_sphere_tri(1,1/10,1/10)

# Find out which mesh points are not parts of triangles
N_points=mesh.points.shape[0]
a=np.full(N_points,True,dtype='bool')
inds=np.arange(N_points)
for triangle in mesh.cells['triangle']:
    for vertex in triangle:
        a[vertex]=False

print(inds[a])
```

When I execute the above code, I get a whole bunch of points that are in `mesh.points` but are not part of any triangle in `mesh.cells['triangle']`. The weird thing is that these extra points are aligned on two main equatorial planes (plus the centre of the sphere):

![image](https://user-images.githubusercontent.com/50581110/57620530-52b3df80-7589-11e9-94a2-05e77b8acfc0.png)

Is this behaviour inherent in Gmsh, or is it due to pygmsh? Is there any way to avoid it?

(Another weird thing is that when I am meshing a cube or a cylinder, I do not get these extra points...)

Thank you very much for your help!

**Comment by gdmcbain** [comment]
I think this is a Gmsh thing. The usual remedy in Gmsh is to declare the points, curves, surfaces, and volumes of interest as 'physical', then Gmsh saves only the nodes and elements associated with physical entities. If no entities are declared physical, Gmsh saves everything, which often includes unwanted construction-points, curves, &c.

This is provided for in pygmsh by the `Geometry.add_physical` method.

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
