### ISSUE TITLE
surface between two volumes

### ISSUE THREAD

**Issue by tcaduser** [nschloe/pygmsh#263]
Is it possible to get the surface at the intersection of two volumes?  I am using the opencascade factory.

    disk = geom.add_cylinder([0.0, 0.0, 0.0],   [0,0,.1], 0.75)
    bulk = geom.add_box([-1.0, -1.0, 0.0], [2, 2,-1.5])

I am able to get the volumes using boolean difference.

    disk_vol = geom.boolean_difference([disk], [bulk], delete_first=False, delete_other=False)
    bulk_vol = geom.boolean_difference([bulk], [disk], delete_first=False, delete_other=False)

**Comment by nschloe** [comment]
* I'm a bit confused by the fact that you're trying to get the intersection between a 2D and a 3D object.  Is that really what you want? 
  * Is there a gmsh command that gives you the surface only?

**Comment by tcaduser** [comment]
I need to get the surface connecting two volumes in order to identify boundary conditions.  If I do this:

    disk = geom.add_cylinder([0.0, 0.0, 0.0],   [0,0,.1], 0.75)
    bulk = geom.add_box([-1.0, -1.0, 0.0], [2, 2,-1.5])
    geom.add_physical(disk, 'disk')
    geom.add_physical(bulk, 'bulk')
    with open('ring.geo', 'w') as f:
      f.write(geom.get_code())
      f.write('''
    Coherence;
    ''')

I am able to get the volumes but not the surfaces.  Gmsh has a Boundary command, but I could not make it work.

Otherwise, I have a script, that will read in a msh2 file and add the "Physical Surface" for each set of triangles bordering the regions.

**Comment by nschloe** [comment]
> Gmsh has a Boundary command, but I could not make it work.
> Otherwise, I have a script, that will read in a msh2 file and add the "Physical Surface" for each set of triangles bordering the regions.

I don't understand. Did you get it to work or not? What command do you use in gmsh to make it work? Is it missing from pygmsh?

**Comment by nschloe** [comment]
```
with open('ring.geo', 'w') as f:
  f.write(geom.get_code())
  f.write('''
Coherence;
''')
```
Note that there is `geom.add_raw_code()`.

**Comment by tcaduser** [comment]
> > Gmsh has a Boundary command, but I could not make it work.
> > Otherwise, I have a script, that will read in a msh2 file and add the "Physical Surface" for each set of triangles bordering the regions.
> 
> I don't understand. Did you get it to work or not? What command do you use in gmsh to make it work? Is it missing from pygmsh?

I could not get Gmsh's Boundary command to work.

I wrote a long python script last year to:
* read in a msh2 format file
* process all tetrahedra into triangles
* identify which triangles interface two regions
* add new triangles as surfaces to the msh file
* label the new surfaces as Physical Surfaces

I had not used in for at least a year, but I was able to make it work in response to a request from a user of my software.

My preference would be if pygmsh/Gmsh was able to automatically create these for me.  My current solution is somewhat fragile.

**Comment by nschloe** [comment]
> I could not get Gmsh's Boundary command to work.

Okay. Well, pygmsh can only do as much as gmsh can do, so your best bet is to to paste your geo file on [gmsh's gitlab](https://gitlab.onelab.info/gmsh/gmsh/issues) (they are usually very responsive) and see what comes out of this. After that, we can see how we can get this into pygmsh.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
