### ISSUE TITLE
How to apply translation on the copy of a volume

### ISSUE THREAD

**Issue by rajgourav** [nschloe/pygmsh#269]
Hi, I'm trying to create a complex structure by  adding together the copies of a geometrical unit.
That is I want to create a basic shape, then create multiple copies of it and then translate them and Union them together.
```python
# translating the 'first' object and creating a new object 'second'
second = geom.translate( first , [50,0,0] ) 
whole_geom = geom.boolean_union([first,second]) # joining them together
fmesh = pygmsh.generate_mesh(geom)
```
This is what I want to do, but this will not work as the 'Translate' function is not returning anything. 
How can I do this?

Is there any way to make copies of an object?
or Is there any way to create a second object by translating the first ?

**Comment by nschloe** [comment]
gmsh translations don't return anything. You just create an object and translate it. Just make two of your `first` objects.

**Comment by rajgourav** [comment]
> gmsh translations don't return anything. You just create an object and translate it. Just make two of your `first` objects.

To easily create 2 of our first object, is there an option to copy?
so that I can write

new_object = something.copy(old_object)

**Comment by nschloe** [comment]
I'd try
```python
def  some_function_that_creates_the_object():
    # ...
    return obj

obj1 = some_function_that_creates_the_object()
obj2 = some_function_that_creates_the_object()
geom.translate(obj2, [50,0,0] ) 
```

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
