### ISSUE TITLE
mpi4py and pygmsh

### ISSUE THREAD

**Issue by MuellerSeb** [nschloe/pygmsh#276]
Hey there,

I'd like to create multiple meshes in parallel with pygmsh. But mpi4py has a problem with ``subprocess``, so it fails. (See: https://stackoverflow.com/questions/27722573/calling-a-subprocess-within-a-script-using-mpi4py)
Maybe it could be an option to use [``pexpect``](https://github.com/pexpect/pexpect), which could also simplify output handling. I used it in one of my packages (working with mpi4py):

https://github.com/GeoStat-Framework/ogs5py/blob/d3e05941a7a76a6d6fdf53a148af7b196fede66a/ogs5py/ogs.py#L1143

What do you think?

Cheers,
Sebastian

**Comment by nschloe** [comment]
This relates to #84 and #181, which never got resolved properly, so I'd be _very_ happy if this could be a solution. @garth-wells suggested to use `mpi4py.spawn`, but I never got it to work.

Anyways, just make sure to add a comment about why we're using Pexpect, otherwise I see myself accidentally replacing it with subprocess in a while. :smile:

**Comment by MuellerSeb** [comment]
I just updated gmsh from v3 to v4. Now it is working. I think there were some MPI/OpenMP things going on in gmsh v3, that crashed the MPI.
See for example: https://gitlab.onelab.info/gmsh/gmsh/issues/478

So I think, there is no need to use pexpect, since the problem is on the gmsh side. (pexpect made the code a bit shorter and more readable but it would introduce another dependency)

Cheers,
Sebastian

**Comment by nschloe** [comment]
Wait, so it all works out-of-the box now?

**Comment by MuellerSeb** [comment]
At least in my case. Downloaded here:
http://gmsh.info/#Download

Im on ubuntu 18.04

**Comment by nschloe** [comment]
Great. Yeah, I recently pushed 4.4.1 to Debian, and I think it landed for Ubuntu 19.10 already, so we should be safe.
