### ISSUE TITLE
generate_mesh stalled after repeated calls

### ISSUE THREAD

**Issue by jviquerat** [nschloe/pygmsh#280]
Hi,

I am using pygmsh as part of a reinforcement learning workflow, which leads me to repeatedly calling ```pygmsh.generate_mesh``` within a single execution of my python code.
I have come to notice that this ```generate_mesh``` call systematically stalls after 995 successful calls (no crashing, just stalling).

Would there be a particular reason behind that ? It does not seem to be a memory issue (checked it). I am using pygmsh 6.0.2 and gmsh 3.0.6 under ubuntu 18.04 LTS.

**Comment by nschloe** [comment]
No idea why that should be the case. The first thing I'd try is upgrade to a newer version of gmsh.

**Comment by jviquerat** [comment]
That indeed worked, thanks (I was using the version installed from ```apt install```). I'm closing the issue then :)
