### ISSUE TITLE
#251 closed issue

### ISSUE THREAD

**Issue by brioglade** [nschloe/pygmsh#281]
Hi @nschloe, Sorry for my foolish head.I still don't understand the closed issue #251 and I really want to figure it out for your kindness help again.

**Comment by nschloe** [comment]
What is it that you don't understand? What have you tried?

**Comment by brioglade** [comment]
I found the closed issue #253.
points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom,gmsh_path = "/home/ufo/paddle/gmsh-4.3.0-Linux64/bin/gmsh"). 
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    gmsh_path = "/home/ufo/paddle/gmsh-4.3.0-Linux64/bin/gmsh"
TypeError: 'Mesh' object is not iterable       

from helpers import compute_volume
Here can't find the helpers module.

**Comment by nschloe** [comment]
```
File "test.py", line 32, in <module>
TypeError: 'Mesh' object is not iterable
```
This is your error. What's in that line 32?

**Comment by brioglade** [comment]
points, cells, point_data, cell_data, field_data = pygmsh.generate_mesh(geom,
                                                                        gmsh_path = "/home/ufo/paddle/gmsh-4.3.0-Linux64/bin/gmsh")    This is the line 32.

**Comment by nschloe** [comment]
Well there's the issue. It doesn't return an iterable, but just a Mesh.
```
mesh = pygmsh.generate_mesh(geom, gmsh_path = "...")
```
Just use `mesh.points`, `mesh.cells` etc. then.
