### ISSUE TITLE
importing xml meshes into fenics with the meshio.write("my_mesh.xml", mesh) gives the error Type mismatch reading XML MeshFunction. MeshFunction type is "uint", but file type is "int".

### ISSUE THREAD

**Issue by SiriusFuenmayor** [nschloe/pygmsh#285]
Hi, when I generate a mesh with the command:
```python
my_mesh = pygmsh.generate_mesh(geom, mesh_file_type="msh", geo_filename="my.geo", msh_filename="my.msh")
```
then write it with the command:
```python
meshio.write("my.xml", my_mesh)
```
and then importing it with 
```python
mesh = Mesh('./my.xml')
subdomains = MeshFunction('size_t', mesh, './my:physical.xml')
```
I get the error
```
*** Error:   Unable to read mesh function from XML file.
*** Reason:  Type mismatch reading XML MeshFunction. MeshFunction type is "uint", but file type is "int".
*** Where:   This error was encountered inside XMLMeshFunction.h.
*** Process: 0
```
I have been fixing this manually by changing the type `attribute` in the physical.xml' from `int `to `uint`

**Comment by nschloe** [comment]
Can't say much without seeing an MWE. Sounds like you want to adapt the data type of your physical fields straight away though.

Also, don't use DOLFIN XML, the format is outdated.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
