### ISSUE TITLE
Get conectivity matrix and get nodes in the boundary 

### ISSUE THREAD

**Issue by mariolinovIC** [nschloe/pygmsh#288]
Hi Nico,

PyGmsh seems to be a great tool for my CFD project.
I wonder if there is any way to get the connectivity matrix or the edges defined by the two nodes they join.
I also would like to know if its is possible to distinguish what nodes are on the boundary.
Thanks for your support.

Cheers,

Mario

**Comment by nschloe** [comment]
You'll have to work that out for yourself. The connectivity matrix is cheap, edges and and boundary nodes are harder. (The latter needs a `unique` call on the edges.) You might want to check out meshplex, https://github.com/nschloe/meshplex/blob/master/meshplex/mesh_tri.py#L367.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
