### ISSUE TITLE
Zenodo release out of sync

### ISSUE THREAD

**Issue by MuellerSeb** [nschloe/pygmsh#289]
Hey there,

unfortunately the Zenodo release page is not updated. The latest version that is citable is 4.0.8 (https://zenodo.org/record/1173106)

Since there is a Github integration for Zenodo, releases can be triggered automatically. So there should be no overhead for you.

I'd like to cite the latest version of pygmsh in an upcoming paper, so it should be also in your interest to provide an updated DOI ;-)

Keep up the good work!
Cheers, Sebastian

**Comment by nschloe** [comment]
I've got Github integration set up on Zenodo, but it's a bit weird with GitHub. I've got plenty of tags pushsed by the latest "Latest release" is still only 4.0.8 https://github.com/nschloe/pygmsh/releases?after=v4.1.3.

Do you know how to programatically change that?

**Comment by nschloe** [comment]
Btw I'm always using

>Cite all versions? You can cite all versions by using the DOI 10.5281/zenodo.1173105. This DOI represents all versions, and will always resolve to the latest one. 

anyway.

**Comment by MuellerSeb** [comment]
I once read about that this is an issue with the GitHub UI. There is a subtle difference for Github between Tags and Releases, even though both tabs show almost the same content.

Personally I use the web-interface to create actual releases for projects and I don't tag them remotely.

For the moment I can live with the "all-version" DOI.

**Comment by nschloe** [comment]
Alright, fixed now. For the record, you'll have to push the git tag (I did that) and then _also_ mark that tag as a release via the github API (or the web interface). I just added
```
git push --tags
curl -H "Authorization: token `cat $(HOME)/.github-access-token`" -d '{"tag_name": "$(VERSION)"}' https://api.github.com/repos/nschloe/pygmsh/releases
```
to the makefile, so this should never be an issue again.
