### ISSUE TITLE
Incremental meshing with attributes?

### ISSUE THREAD

**Issue by liubenyuan** [nschloe/pygmsh#291]
Hi,

Thank you for your pygmsh. I want to use it for 3D FEM simulation (low frequency), in the application of transcranial electrical stimulation.

1. I would like to add two electrodes patches on the boundary of an already meshed cylinder (tetrahedrons). An electrode-patch has a fixed area and size, and it needs to be perfectly placed on the boundary curvature. The patch volume requires much more refined tetrahedrons.

2. The conductivity of a patch needs to also be set manually. All tetrahedrons should have attributes. For example, the tetrahedrons within the cylinder have attribute 0, the (refined) tetrahedrons of electrode-patches have attributes 1 and 2 respectively.

Benyuan

**Comment by nschloe** [comment]
So you're tring to define subdomains? Best check how to do it in gmsh and then repeat the same in pygmsh.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.
