### ISSUE TITLE
Error : Is gmsh installed

### ISSUE THREAD

**Issue by shoujieqiu** [nschloe/pygmsh#292]
I can do this:
`import pygmsh`
but why stiil meet the error when run 
"mesh=pygmsh.generate_mesh(geom)"
The error is as follow:
"FileNotFoundError: [Errno 2] No such file or directory: 'gmsh': 'gmsh'
Is gmsh installed?"

**Comment by nschloe** [comment]
You need to install [gmsh](http://gmsh.info/).

**Comment by shoujieqiu** [comment]
Thanks a lot! It helps me!
