### ISSUE TITLE
Set material name string/integer for different geometric regions using pygmsh

### ISSUE THREAD

**Issue by amrit-poudel** [nschloe/pygmsh#294]
Hi,

I would like to use pygmsh to create a geometry with two(or many) different materials (which would be identified by a string or an integer). I was wondering how I can go about doing that using pygmsh.

minimal working code:
```python
import meshio
import pygmsh as pg
import numpy as np

geom = pg.built_in.Geometry()
rectangle1 = geom.add_rectangle(0.0, 2.0, 0.0, 2.0, 0.0, 2)
rectangle2 = geom.add_rectangle(2.0, 3.0, 0.0, 2.0, 0.0, 1)
###########geom.add_physical_surface([rectangle1], u"s")
mesh = pg.generate_mesh(geom)
```

This is a simple example. I have two rectangles (in a more complicated case, I could have a complex shape) which I would like to assign to two different materials.  The line that I have commented out does not work, which I thought would be the way to assign material type to each region.

Currently, this code returns a list of triangular elements, but I cannot identify which element belongs to which region or rectangle. Is it possible to have each element with an identifier so that I know which region/rectangle it belongs to?

Thanks for any help!

**Comment by gdmcbain** [comment]
You need the `.surface` attribute of the rectangle.
```python
geom.add_physical(rectangle1.surface, u"s")
```

> Is it possible to have each element with an identifier so that I know which region/rectangle it belongs to?

Yes, `mesh.cell_data['triangle']['gmsh:physical']` is a `numpy.ndarray` of `shape == (len(mesh.cells['triangle'],)` and `dtype('int64')` which identify the physical surfaces; here all 1.  See also `mesh.field_data['s']` which is `[1, 2]`, being the `int` identifying the physical surface and the dimension.

For a complete example assigning different material types to two regions, see 

https://github.com/kinnala/scikit-fem/blob/8b031ff1c587d5a141b98c66625505e7fde8cd87/docs/examples/ex17.py#L26-L30

**Comment by amrit-poudel** [comment]
Thanks a lot! I managed do that using opencascade kernel/engine:

geom =  pg.opencascade.Geometry(characteristic_length_min=min_grid_size, characteristic_length_max=max_grid_size)
rectangle1 = geom.add_rectangle([0.0, 0.0, z], lswidth, height, char_length=lsgrid_size)
geom.add_physical_surface(rectangle1, "s1") # will be labeled as 1 since it was added first



It looks like it is also possible to do that with built_in kernel using your syntax, which I was unaware of before, so thanks for pointing that out:

geom.add_physical(rectangle1.surface, u"s")


My next question is: How can I identify the boundary vertices/nodes and elements (triangular element in 2D) whose one of the nodes belongs to the boundary? I guess, I can figure out the second part of my question myself, but I am wondering about the first part, that is, identifying the boundary vertices. If you know of a way to do that, I would appreciate any pointer.

Thanks again.

**Comment by gdmcbain** [comment]
> How can I identify the boundary vertices/nodes

This is a bit fiddly so I prefer to leave it to the experts and use [`skfem.mesh.MeshTri.boundary_nodes`](https://kinnala.github.io/scikit-fem-docs/api.html?highlight=boundary_nodes#skfem.mesh.MeshTri.boundary_nodes).  Here:

```python
from skfem.importers.meshio import from_meshio

mesh = pg.generate_mesh(geom)
from_meshio(mesh).boundary_nodes()
```

**Comment by amrit-poudel** [comment]
Thanks for the note. Is it not possible to do that using pygmsh alone and without calling another library?

**Comment by gdmcbain** [comment]
It's not really a job for pygmsh; pygmsh just talks to Gmsh in GEO and gets meshio to read whatever Gmsh writes.  pygmsh is more about geometry and topology than meshes.

You can look in the source of [`skfem.mesh.Mesh.boundary_nodes`](https://github.com/kinnala/scikit-fem/blob/ccc9ab102f5eaed7e89cb7ca40eae2f299eb9048/skfem/mesh/mesh.py#L310-L312) and see what it's doing; however, when I did that, I decided to leave it to the experts.

**Comment by amrit-poudel** [comment]
If there was a way to group nodes that belong to line/curve/loop (in 2D) or a surface (in 3D), then pulling boundary nodes would be possible.  This seems to be the way to do in Gmsh. I thought since Gmsh can do it, so will pygmsh.

I will take a look into that library you pointed out to see how they manage to do it. That said, if anybody else has a better idea, please feel free to comment/suggest. Thanks.

**Comment by gdmcbain** [comment]
Oh, do you mean that you want to define a `Physical Line`?  That can be done in pygmsh, yes, sorry.  Use the same `.add_physical` method but pass lines instead of surfaces.
```python
geom.add_physical(rectangle1.lines, 'boundary')
```

**Comment by amrit-poudel** [comment]
when you do rectangle1.lines, which line will that select? Is it possible to select the line that I want?Rectangle is a simple example, what if  we have a  circle with a hole and we want to assign boundary tag to outer or inner loop?

My question basically boils down to the previous question I posed,  that is, how do we get the boundary nodes? I thought grouping nodes into lines/curves/loops (in 2D) was the way to do it, but then the impression I got from you is that it is more complicated than that.

**Comment by gdmcbain** [comment]
`rectangle1.lines` is a list of four lines.  If you just want to select a proper subset, you can do so, but you'd need to know the order.

Better in that case would be to eschew `add_rectangle` in favour of explicitly defining the points, lines, and plane surface; see, e.g., https://github.com/kinnala/scikit-fem/blob/d5e9a91101066a13a5ef5244c97832038d972571/docs/examples/ex13.py#L10-L26.

**Comment by gdmcbain** [comment]
> what if we have a circle with a hole and we want to assign boundary tag to outer or inner loop?

See the aforementioned ex17 which tags the outer loop.  (Though in the succeeding boundary value problem, it's a Neumann boundary rather than Dirichlet so it's the facets that are needed rather than the nodes, but the pygmsh would be identical.)

**Comment by amrit-poudel** [comment]
okay, I see your point. Why did you think earlier that this would not help you get the boundary nodes? Once we have points and lines, simply reading the tag would be enough to identify boundary nodes. No? What am I missing?

**Comment by gdmcbain** [comment]
Well no, that's right; I was considering the case in which no Physical Curves had been defined.  Given just points and triangles, finding which points are on the boundary is tedious.  Defining Physical Curves is definitely the way to go if you can.

**Comment by amrit-poudel** [comment]
Thanks a lot for your help. I appreciate it. 

Slightly different question, but still relevant to this topic:
What is the correct syntax for creating points, lines, splines, physical lines, physical points etc using using opencascade engine?

Here is my example which does not  seem to work.

import meshio
import pygmsh as pg
import numpy as np

min_grid_size = 0.5
max_grid_size = 1
geom =  pg.opencascade.Geometry(characteristic_length_min=min_grid_size, characteristic_length_max=max_grid_size)
y = 0
z = 0
w = 10
point1 = geom.add_point([0.0, 0, y, z], char_length=0.5)
geom.add_physical_point(point1, "boundary1")
point2 = geom.add_point([w, y, z], char_length=1)
line1  = geom.add_line([point1, point2])
geom.add_physical_line(line1, "s1")


Is there a way to make this work using opencascade engine? Thanks!

**Comment by amrit-poudel** [comment]
So I figured that char_length is not a valid syntax. The right syntax is then:

point1 = geom.add_point([0.0, 0, y, z],  0.5)
geom.add_physical_point(point1, "boundary1")
point2 = geom.add_point([w, y, z],  1)
line1 = geom.add_line([point1, point2])
geom.add_physical_line(line1, "s1")

mesh = pg.generate_mesh(geom)

The problem I am facing right now is how I can pull out the right vertex  that belongs to "boundary1" tag. Currently, mesh.cell_data["vertex"] does not seem to help.  Any other ideas how I  can get the vertex/point that  belongs to "boundary1" tag ?

**Comment by amrit-poudel** [comment]
I think I figured out the solution to my second question as well:
It looks like I need to look at two different places to determine which vertex belong to boundary1.
mesh.cell_data["vertex"]["gmsh:physical"]
mesh.field_data["boundary1"]

**Comment by gdmcbain** [comment]
Yes, that's right about needing to look in `cell_data` and `field_data` to match up the names and the tags.

One little thing:

```python
point1 = geom.add_point([0.0, 0, y, z], 0.5)
```

The first argument should have length three, being the coordinates in ℝ³.
