### ISSUE TITLE
Force equal number of nodes on two parallel edges or surfaces

### ISSUE THREAD

**Issue by amrit-poudel** [nschloe/pygmsh#295]
I would like to use pygmsh to create equal number of nodes on two edges of a  rectangle with small length. However, the extrude command does not seem to do the job. I do not want any nodes in the interior of the rectangle. Nodes must appear only on the two edges (left and right edges). 
```python
swire_width = 10
swire_length = 1 # same length as grid size
sgrid_size = swire_length
z= 0
min_grid_size = sgrid_size
max_grid_size = sgrid_size
geom =  pg.opencascade.Geometry(characteristic_length_min=min_grid_size, characteristic_length_max=max_grid_size)
point1 = geom.add_point([0.0, 0.0, z], sgrid_size)
point2 = geom.add_point([0.0, swire_width, z], sgrid_size)
line1 = geom.add_line(*[point1, point2])
point3 = geom.add_point([sgrid_size, 0.0, z], sgrid_size)
line2 = geom.add_line(*[point1, point3])
point4 = geom.add_point([sgrid_size, swire_width, z], sgrid_size)
line3 = geom.add_line(*[point2, point4])
_, r1, _ = geom.extrude(line1, [sgrid_size, 0.0, 0.0])
```

Does anyone have any suggestion? Thanks!

**Comment by gdmcbain** [comment]
When [extruding](http://gmsh.info/dev/doc/texinfo/gmsh.html#Structured-grids) in Gmsh, specify the number of layers.  In pygmsh, this is the `num_layers` keyword argument; e.g. [wire1.py](https://github.com/nschloe/pygmsh/files/3990893/wire1.py.txt)
```python
from pygmsh.built_in import Geometry

swire_width = 10
swire_length = 1
sgrid_size = swire_length

z = 0

geom = Geometry()
points = [geom.add_point([0., y, z], sgrid_size)
          for y in [0., swire_width]]
line = geom.add_line(*points)
wire = geom.extrude(line, [swire_length, 0., 0.], num_layers=1)

with open('wire1.geo', 'w') as fout:
    fout.write(geom.get_code())
```

![wire1](https://user-images.githubusercontent.com/1588947/71300877-4c25fa00-23ed-11ea-8291-438cb593c93a.png)

**Comment by amrit-poudel** [comment]
Thanks for the input. I figured that after extrusion, if I set the surface transfinite, then it seems to do the job. That way I do not have to specify all the points (the way you've done it), which I do not know beforehand. 

My real problem statement is: I have an arbitrary geometry in 2D whose one of the boundary edges is a vertical line. I extrude this vertical line and declare the extruded surface transfinite. 

Do you think that would be reasonable way of doing it, or am I not doing this correctly?

**Comment by gdmcbain** [comment]
I haven't tried anything like that myself.  Maybe ask the Gmsh mailing list; working out how to do it in Gmsh is the tricky part, scripting it in pygmsh thereafter is usually easy enough.

**Comment by amrit-poudel** [comment]
wire = geom.extrude(line, [swire_length, 0., 0.], num_layers=1)

Is it possible to access points from the extruded line (above) ? If so, how?

Also, I noticed that you have used built_in engine here? What would be the syntax to access points from extruded line if opencascade engine is used instead?

Many thanks.

**Comment by gdmcbain** [comment]
> Is it possible to access points from the extruded line (above) ? If so, how?

You mean from `wire[0]`? No, I don't think so. It's only a `LineBase` which only has an `id`, not access to its terminal points.

**Comment by amrit-poudel** [comment]
Thanks for that note. By the way, how do I specify mesh color in pygmsh? For instance, I have three different regions and I want mesh color to be different for those regions. What do I need to do in pygmsh such that when I open .msh file (generated by pygmsh) in Gmsh, I will see the mesh with three different colors for three different regions I created?

Thanks!

**Comment by nschloe** [comment]
pygmsh has no GUI, so you cannot specify colors here. You need to do that in Gmsh; best ask those guys.
