### ISSUE TITLE
generate_mesh broken with  an AssertionError

### ISSUE THREAD

**Issue by Ethan-yangs** [nschloe/pygmsh#300]
Hello, I'm new in pygmsh and  I have problems with the example, this seems trivial but I can't figure it out.
```
import pygmsh
geom = pygmsh.built_in.Geometry()
poly = geom.add_polygon([
    [ 0.0,  0.0, 0.0],
    [ 1.0,  0.0, 0.0],
    [ 0.3,  0.7, 0.0],
    [ 0.0,  0.7, 0.0],
    ])
axis = [0, 0, 1]
geom.extrude( poly, [0, 0, 0.8] )
mesh = pygmsh.generate_mesh(geom,gmsh_path= "D:\\gmsh\\gmsh-4.1.3-Windows64\\gmsh.exe")
```
**produces this error:**
```
Error   : Unknown number option 'Mesh.ChacoHypercubeDim'
Error   : Unknown number option 'Mesh.ChacoMeshDim1'
Error   : Unknown number option 'Mesh.MshFilePartitioned'
Error   : Unknown number option 'Mesh.RemeshParametrization'
Error   : No elements in region 1 
Info    : Done meshing 3D (0 s)
Info    : 417 vertices 573 elements
Error   : ------------------------------
Error   : Mesh generation error summary
Error   :     0 warnings
Error   :     1 error
Error   : Check the full log for details
Error   : ------------------------------
Info    : Writing 'C:\Users\yang\AppData\Local\Temp\tmpee049vb8.msh'...
Info    : Done writing 'C:\Users\yang\AppData\Local\Temp\tmpee049vb8.msh'
Info    : Stopped on Tue Feb 04 11:16:09 2020
Traceback (most recent call last):
  File "E:/python projects/data_file/question.py", line 14, in <module>
    mesh = pygmsh.generate_mesh(geom,gmsh_path= "D:\\gmsh\\gmsh-4.1.3-Windows64\\gmsh.exe")
  File "C:\Users\yang\python\lib\site-packages\pygmsh\helpers.py", line 141, in generate_mesh
    p.returncode
AssertionError: Gmsh exited with error (return code 1).
```
Gmsh has generated grid in 'C:\Users\yang\AppData\Local\Temp\tmpee049vb8.msh' But the scripts will report errors, I can't writte the points, cells, point_data, cell_data, field_data.
 I hope you can help me, Many thanks in advance!

**Comment by nschloe** [comment]
> gmsh-4.1.3

Try and update to a newer version of gmsh, this is probably the source of the errors.

**Comment by Ethan-yangs** [comment]
Thanks for your quick reply, I just updated the Gmsh version to newest (4.5.2) from [http://gmsh.info] but  still have the same error. My pygmsh version: 6.0.2, python: 3.7

C:\Users\yang\python\python.exe "E:/python projects/data_file/question.py"
Error   : Unknown number option 'Mesh.ChacoHypercubeDim'
Error   : Unknown number option 'Mesh.ChacoMeshDim1'
Error   : Unknown number option 'Mesh.MshFilePartitioned'
Error   : Unknown number option 'Mesh.RemeshParametrization'
Info    : Running 'D:\gmsh\gmsh-4.5.2-Windows64\gmsh.exe -3 C:\Users\yang\AppData\Local\Temp\tmph3xdxm7s.geo -format msh -bin -o C:\Users\yang\AppData\Local\Temp\tmp9tkxa4e3.msh' [Gmsh 4.5.2, 1 node, max. 1 thread]
Info    : Started on Tue Feb 04 21:28:30 2020
Info    : Reading 'C:\Users\yang\AppData\Local\Temp\tmph3xdxm7s.geo'...
Info    : Done reading 'C:\Users\yang\AppData\Local\Temp\tmph3xdxm7s.geo'
Info    : Meshing 1D...
Info    : [  0 %] Meshing curve 1 (Line)
Info    : [ 10 %] Meshing curve 2 (Line)
Info    : [ 20 %] Meshing curve 3 (Line)
Info    : [ 30 %] Meshing curve 4 (Line)
Info    : [ 40 %] Meshing curve 8 (Line)
Info    : [ 50 %] Meshing curve 9 (Line)
Info    : [ 50 %] Meshing curve 10 (Line)
Info    : [ 60 %] Meshing curve 11 (Line)
Info    : [ 70 %] Meshing curve 13 (Line)
Info    : [ 80 %] Meshing curve 14 (Line)
Info    : [ 90 %] Meshing curve 18 (Line)
Info    : [100 %] Meshing curve 22 (Line)
Info    : Done meshing 1D (0 s)
Info    : Meshing 2D...
Info    : [  0 %] Meshing surface 6 (Plane, Frontal)
Info    : [  0 %] Simple recombination completed (0 s): 48 quads, 18 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.768152, min Q = 0.412134
Info    : [ 20 %] Meshing surface 15 (Surface, Frontal)
Info    : [ 20 %] Simple recombination completed (0.015625 s): 86 quads, 24 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.762042, min Q = 0.565871
Info    : [ 40 %] Meshing surface 19 (Surface, Frontal)
Info    : [ 40 %] Simple recombination completed (0 s): 86 quads, 26 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.783564, min Q = 0.57007
Info    : [ 50 %] Meshing surface 23 (Surface, Frontal)
Info    : [ 50 %] Simple recombination completed (0 s): 28 quads, 10 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.704791, min Q = 0.562195
Info    : [ 70 %] Meshing surface 27 (Surface, Frontal)
Info    : [ 70 %] Simple recombination completed (0 s): 61 quads, 20 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.760751, min Q = 0.542755
Info    : [ 90 %] Meshing surface 28 (Plane, Frontal)
Info    : [ 90 %] Simple recombination completed (0 s): 48 quads, 18 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.768152, min Q = 0.412134
Info    : Done meshing 2D (0.046875 s)
Info    : Meshing 3D...
Info    : 3D Meshing 1 volume with 1 connected component
Error   : No elements in volume 1 
Info    : Done meshing 3D (0 s)
Info    : 417 nodes 573 elements
Error   : ------------------------------
Error   : Mesh generation error summary
Error   :     0 warnings
Error   :     1 error
Error   : Check the full log for details
Error   : ------------------------------
Info    : Writing 'C:\Users\yang\AppData\Local\Temp\tmp9tkxa4e3.msh'...
Info    : Done writing 'C:\Users\yang\AppData\Local\Temp\tmp9tkxa4e3.msh'
Info    : Stopped on Tue Feb 04 21:28:30 2020
Traceback (most recent call last):
  File "E:/python projects/data_file/question.py", line 17, in <module>
    mesh = pygmsh.generate_mesh(geom, gmsh_path = "D:\\gmsh\\gmsh-4.5.2-Windows64\\gmsh.exe")
  File "C:\Users\yang\python\lib\site-packages\pygmsh\helpers.py", line 141, in generate_mesh
    p.returncode
AssertionError: Gmsh exited with error (return code 1).

Process finished with exit code 1

**Comment by nschloe** [comment]
I can create the mesh without problem:
```python
import pygmsh

geom = pygmsh.built_in.Geometry()
poly = geom.add_polygon(
    [[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.3, 0.7, 0.0], [0.0, 0.7, 0.0]]
)
axis = [0, 0, 1]
geom.extrude(poly, [0, 0, 0.8])
mesh = pygmsh.generate_mesh(geom)

mesh.write("out.vtu")
```
![f](https://user-images.githubusercontent.com/181628/74735465-09e43200-5251-11ea-974f-fc043a7e7618.png)

Appears to be a broken installation.
