### ISSUE TITLE
surprising multiple boundary cell blocks generated with new meshio cells list

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#301]
Continuing #297 to look ahead to see how meshio 4 will affect pygmsh, I found an unexpected result.
```python
from pygmsh import generate_mesh
from pygmsh.built_in import Geometry

geom = Geometry()
circle = geom.add_circle([0.] * 3, 1.)
geom.add_physical(circle.line_loop.lines, 'circle')
geom.add_physical(circle.plane_surface, 'disk')

mesh = generate_mesh(geom, dim=2,
                     geo_filename='disk.geo',
                     msh_filename='disk.msh')
print(mesh)

for cellblock in mesh.cells:
    print(cellblock[0], cellblock[1].shape)
```
The mesh has its boundary divided into three:
```
<meshio mesh object>
  Number of points: 111
  Number of cells:
    line: 10
    line: 10
    line: 10
    triangle: 190
  Cell data: gmsh:physical
```
as seen also inspecting the list of cells:
```
line (10, 2)
line (10, 2)
line (10, 2)
triangle (190, 3)
```

This is based on the same example used in #297 which in turn is simplified from a longstanding example used in another code: https://github.com/kinnala/scikit-fem/blob/c8261575ba5295030161fe967776499b019a7cd8/docs/examples/ex12.py#L7-L14.

The number three is presumably from the default `num_sections=3` in `Geometry.add_circle`, but this division of the boundary cells is new and unwanted.  It seems to be something to do with those MSH 4.1 entities which have puzzled more than one meshio developer.

Should this be avoided by modifying the pygmsh user code?  Avoided internally by pygmsh?  Or dealt with downstream by the consuming finite element library?

**Comment by gdmcbain** [comment]
Adding `compound=True` to the `add_circle` still generates a mesh with three lots of 'line' cells.

**Comment by gdmcbain** [comment]
Perhaps this should be consider a bug in Gmsh rather than pygmsh or meshio?

**Comment by nschloe** [comment]
So the element block is
```
$Elements
4 220 1 220
1 1 1 10
1 1 4 
2 4 5 
3 5 6 
4 6 7 
5 7 8 
6 8 9 
7 9 10 
8 10 11 
9 11 12 
10 12 2 
1 2 1 10
11 2 13 
12 13 14 
13 14 15 
14 15 16 
15 16 17 
16 17 18 
17 18 19 
18 19 20 
19 20 21 
20 21 3 
1 3 1 10
21 3 22 
22 22 23 
23 23 24 
24 24 25 
25 25 26 
26 26 27 
27 27 28 
28 28 29 
29 29 30 
30 30 1 
2 5 2 190
31 38 48 59 
32 37 47 60 
33 53 56 104 
34 53 104 108 
35 36 46 73 
36 26 27 69 
37 26 69 70 
38 46 36 85 
39 37 49 65 
40 13 68 98 
41 20 21 56 
42 49 37 64 
43 48 38 67 
44 47 37 66 
45 45 84 93 
46 61 34 67 
47 43 61 67 
48 62 43 67 
49 38 62 67 
50 51 33 71 
51 39 51 71 
52 52 39 72 
53 13 14 68 
54 104 32 108 
55 33 51 102 
56 84 35 93 
57 31 73 89 
58 52 72 95 
59 56 21 77 
60 68 15 111 
61 51 39 69 
62 39 52 70 
63 8 9 57 
64 51 58 102 
65 72 35 95 
66 68 50 98 
67 73 31 96 
68 94 61 96 
69 44 61 94 
70 14 15 68 
71 29 30 58 
72 41 54 84 
73 55 40 85 
74 36 55 85 
75 53 40 76 
76 73 46 89 
77 55 68 111 
78 99 62 106 
79 36 62 99 
80 40 53 108 
81 55 36 99 
82 54 41 78 
83 40 55 79 
84 41 56 77 
85 69 28 103 
86 25 70 105 
87 59 12 63 
88 60 5 64 
89 20 56 83 
90 56 53 83 
91 84 54 95 
92 61 44 65 
93 56 41 104 
94 27 28 69 
95 25 26 70 
96 74 46 85 
97 45 75 84 
98 12 2 63 
99 5 6 64 
100 65 44 107 
101 29 58 103 
102 62 36 73 
103 35 84 95 
104 65 49 100 
105 38 59 63 
106 37 60 64 
107 33 66 80 
108 66 44 80 
109 57 9 86 
110 8 57 87 
111 11 12 59 
112 4 5 60 
113 51 69 103 
114 82 42 94 
115 70 52 105 
116 60 47 91 
117 59 48 90 
118 58 51 103 
119 34 61 65 
120 69 39 70 
121 23 24 81 
122 71 42 72 
123 39 71 72 
124 23 81 110 
125 16 17 79 
126 3 22 78 
127 38 63 106 
128 48 67 101 
129 34 65 100 
130 47 66 102 
131 71 33 80 
132 42 71 80 
133 42 80 94 
134 43 73 96 
135 17 76 79 
136 77 3 78 
137 43 62 73 
138 68 55 99 
139 57 86 101 
140 87 57 100 
141 21 3 77 
142 17 18 76 
143 58 30 92 
144 67 34 101 
145 81 54 110 
146 63 50 106 
147 66 33 102 
148 86 48 101 
149 49 87 100 
150 47 58 92 
151 74 32 88 
152 32 75 88 
153 46 74 88 
154 75 45 88 
155 50 99 106 
156 58 47 102 
157 11 59 90 
158 4 60 91 
159 41 77 78 
160 76 40 79 
161 53 76 109 
162 31 94 96 
163 31 82 94 
164 19 20 83 
165 82 45 93 
166 30 1 92 
167 7 8 87 
168 9 10 86 
169 61 43 96 
170 41 75 104 
171 2 13 98 
172 6 7 97 
173 74 40 108 
174 62 38 106 
175 1 4 91 
176 10 11 90 
177 63 2 98 
178 64 6 97 
179 72 42 93 
180 35 72 93 
181 49 64 97 
182 50 63 98 
183 24 25 105 
184 28 29 103 
185 22 23 110 
186 15 16 111 
187 18 19 109 
188 75 41 84 
189 40 74 85 
190 82 31 89 
191 45 82 89 
192 37 65 107 
193 76 18 109 
194 50 68 99 
195 44 66 107 
196 66 37 107 
197 19 83 109 
198 86 10 90 
199 48 86 90 
200 83 53 109 
201 75 32 104 
202 80 44 94 
203 32 74 108 
204 54 81 95 
205 54 78 110 
206 79 55 111 
207 78 22 110 
208 16 79 111 
209 42 82 93 
210 81 52 95 
211 88 45 89 
212 46 88 89 
213 1 91 92 
214 91 47 92 
215 81 24 105 
216 52 81 105 
217 87 49 97 
218 7 87 97 
219 34 100 101 
220 100 57 101 
$EndElements
```
Read:
 * first line: There are 4 blocks, 220 elements total, numbered from 1 to 220
 * second line: The first block starts, type 1 (line), block id 1, 10 entries total. Then 10 lines follow (with their ids)
  * then: second block starts, type 1(line), block id 2, 10 entries total. etc.

In total we have three blocks with 10 lines each, and a block with 190 triangles. So I would say that meshio does the right thing here.

It's a bit weird that compound doesn't take care of this. Perhaps there's another gmsh trick to this. I'd post the geo file in their bug tracker and ask if there's a way to get one block of lines in the output msh file.

**Comment by gdmcbain** [comment]
Yes, it is high time that we got on top of the MSH 4.1 `$Entities`.

**Comment by gdmcbain** [comment]
> It's a bit weird that compound doesn't take care of this.

It might be that it would but that continuing to refer to `circle.line_loop.lines` circumvents it and gets back to the three ‘elementary entities’.

**Comment by gdmcbain** [comment]
I was puzzled by the exchange at the end of last month on the nomenclature of entities, ([‘Physical entities/groups’](http://onelab.info/pipermail/gmsh/2020/013505.html))

* ﻿J. Theler: ‘When were physical entities renamed to groups? Is the official nomenclature “Physical group” now?’

* C. Geuzaine: ‘We settled on “Physical group” in the api to make a clear distinction with model (elementary) entities. But I still use both terminologies.’ 

Perhaps the `$Entities` are just the same as ‘elementary entities’.  That's awful as the latter have no significance in a finite element mesh and no significance in the context of meshio or pygmsh.

**Comment by gdmcbain** [comment]
Following the clarification of `meshio.Mesh.cells: List[Cells]` in nschloe/meshio#685, viz. that they have no data, they're of less interest here than 
* `.cells_dict`, here with
  *  `'line'` of `shape==(30, 2)` and 
  * `'triangle'` of `shape==(186, 3)`) and 
* `.cell_sets_dict`, here with with:
  * `'circle'`: `{'line': arange(30)}`
  * `'disk'`: `{'triangle': arange(186)}`

I think applications should manage to work with that.

The Gmsh $Entities remain of interest for writing MSH 4.1 nschloe/meshio#332 but that's not required in pygmsh.
