### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by steersteer** [nschloe/pygmsh#302]
hi,

I'm getting this error when trying to install via pip on python 3.7:
```
----- Installing 'pip install pygmsh ' -----
Requirement already up-to-date: pip in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (20.0.2)
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install
----- Failed to install 'pip install pygmsh ' -----
```
Any idea what I can do?

**Comment by nschloe** [comment]
Try `pip install pygmsh --force`.

**Comment by steersteer** [comment]
Thanks but unfortunately this yielded the same result

**Comment by nschloe** [comment]
Make sure that `pip` actually uses Python 3. Try `python3 -m pip install pygmsh`.

**Comment by steersteer** [comment]
i get this when trying with and without the "-m":
`----- Installing 'python3  pip install pygmsh' -----
ERROR: Could not find a version that satisfies the requirement python3 (from versions: none)
ERROR: No matching distribution found for python3
----- Failed to install 'python3  pip install pygmsh' -----

----- Installing 'python3 -m  pip install pygmsh' -----
Usage:   
  C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe -m pip install [options] <archive url/path> ...
no such option: -m
----- Failed to install 'python3 -m  pip install pygmsh' -----`

**Comment by nschloe** [comment]
Please use triple fences for code blocks in the future, this makes reading easier.

This problem doesn't seem to be pygmsh-related. Can you install _anything_ at all?

**Comment by nschloe** [comment]
Also, perhaps this is better discussed on slack. https://app.slack.com/client/TTL6Q54A3/CTLGZQFML/

**Comment by steersteer** [comment]
> Can you install anything at all?
Yes, everything but pygmsh

**Comment by nschloe** [comment]
Let's discuss this on slack.
