### ISSUE TITLE
Plot a mesh with matplotlib

### ISSUE THREAD

**Issue by CsatiZoltan** [nschloe/pygmsh#321]
I have an `.msh` file created by gmsh. My goal is to convert it to tikz using [tikzplotlib](https://github.com/nschloe/tikzplotlib) so that I can include it in a Latex document. For that, I need to display the mesh in matplotlib. Is it possible with this library?

**Comment by nschloe** [comment]
You can easily do that yourself. You have all the points and the cells, just draw the lines accordingly.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time.

**Comment by akbarpn136** [comment]
I'm new in pygmsh, any example on how to plot mesh in matplotlib? Thank you for this work anyway

**Comment by nschloe** [comment]
@akbarpn136 Best don't highjack unrelated issues. Open a new discussion!

**Comment by akbarpn136** [comment]
Ok, sorry about that..
