### ISSUE TITLE
test_boundary_layers.py not working correctly for new GMSH versions

### ISSUE THREAD

**Issue by MaartenBlommaert** [nschloe/pygmsh#323]
When running the test_boundary_layers.py code in the test folder of pygmsh (pygmsh 6.0.9) in combination with newer GMSH versions (tested with GMSH 4.5.6), I get no longer the intended mesh refinement towards the lower side and the right corner of the meshed polygon.  With GMSH version 3.0.6 this is still working correctly. See also the following figures:
**GMSH 4.5.6**
![blayers_GMSH456 0000](https://user-images.githubusercontent.com/62435163/78892803-4f132c00-7a6a-11ea-8e42-54705e066c86.png)
**GMSH3.0.6**
![blayers_GMSH306 0000](https://user-images.githubusercontent.com/62435163/78892796-4cb0d200-7a6a-11ea-9ab8-4a355cb440fe.png)

**Comment by nschloe** [comment]
I can reproduce this issue. Looking at it.

**Comment by nschloe** [comment]
Maarten, how does
```
p0 = newp;
Point(p0) = {0.0, 0.0, 0.0, 0.1};
p1 = newp;
Point(p1) = {2.0, 0.0, 0.0, 0.1};
p2 = newp;
Point(p2) = {3.0, 1.0, 0.0, 0.1};
p3 = newp;
Point(p3) = {1.0, 2.0, 0.0, 0.1};
p4 = newp;
Point(p4) = {0.0, 1.0, 0.0, 0.1};
l0 = newl;
Line(l0) = {p0, p1};
l1 = newl;
Line(l1) = {p1, p2};
l2 = newl;
Line(l2) = {p2, p3};
l3 = newl;
Line(l3) = {p3, p4};
l4 = newl;
Line(l4) = {p4, p0};
ll0 = newll;
Line Loop(ll0) = {l0, l1, l2, l3, l4};
s0 = news;
Plane Surface(s0) = {ll0};
field1 = newf;
Field[field1] = BoundaryLayer;
Field[field1].EdgesList = {l0};
Field[field1].NodesList = {p0, p1};
Field[field1].hfar= 0.1;
Field[field1].hwall_n= 0.01;
Field[field1].ratio= 1.1;
Field[field1].thickness= 0.2;
Field[field1].AnisoMax= 100.0;
field2 = newf;
Field[field2] = BoundaryLayer;
Field[field2].NodesList = {p2};
Field[field2].hfar= 0.1;
Field[field2].hwall_n= 0.01;
Field[field2].ratio= 1.1;
Field[field2].thickness= 0.2;
Field[field2].AnisoMax= 100.0;
BoundaryLayer Field = {field1,field2};
```
look for you?

**Comment by nschloe** [comment]
Perhaps give https://github.com/nschloe/dmsh a shot.

**Comment by MaartenBlommaert** [comment]
Hi Nico, 

Thanks for the fast response!
With the 4.5.6 version, I get the same behavior as you do (3.0.6 does not give refinement with that geo input). 
However, based on some first trials I did, it does not seem to be working very robustly yet for more general shapes, as was also indicated in the thread you opened at https://gitlab.onelab.info/gmsh/gmsh/-/issues/812#note_9454. 
For now I'll work with simple refinement instead of the boundary layer functionality. Shall I close the issue now, or do you want to update the demo first?

**Comment by nschloe** [comment]
I've updated pygmsh already. Thanks again for the good report!
