### ISSUE TITLE
opencascade engine errors when trying to combine circle arcs with lines

### ISSUE THREAD

**Issue by amrit-poudel** [nschloe/pygmsh#327]
I have a bunch of lines and arcs which I would like to combine to create a surface in 2D. However, I keep getting the following error:

Error   : Could not create circle arc
Error   : '/tmp/tmpjr24kkji.geo', line 68 : Could not add circle
Error   : Could not create circle arc
Error   : '/tmp/tmpjr24kkji.geo', line 70 : Could not add circle
Error   : Unknown OpenCASCADE curve with tag 15
Error   : '/tmp/tmpjr24kkji.geo', line 80 : Could not add line loop
Error   : Unknown OpenCASCADE line loop with tag 15
Error   : '/tmp/tmpjr24kkji.geo', line 82 : Could not add plane surface
Error   : Unknown OpenCASCADE curve with tag 15

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
import pygmsh as pg
geom =  pg.opencascade.Geometry(characteristic_length_min=min_grid_size, characteristic_length_max=max_grid_size)
## lines
line1 = geom.add_line( *[point1, point2])
line2 = geom.add_line( *[point3, point4])
## arcs
 arc1 = geom.add_circle_arc(point1, pointc, point2)
 arc2 = geom.add_circle_arc(point3, pointc, point4)
## surface
some_surface = geom.add_plane_surface(geom.add_line_loop([line1, line2, arc1, arc2]))

What is the correct way of adding arcs and lines to create a surface using the opencascade engine?
Many thanks for help.

**Comment by nschloe** [comment]
To debug: Produce the geo file, ask yourself what's what's wrong with it. You can consult with gmsh upstream. Post your results here if you think it's a pygmsh bug.

**Comment by amrit-poudel** [comment]
I was able to combine circle arcs with lines, by using the same syntax as above.  There were errors (minor/not worth reporting) in how I set up a circle which was the source of all the trouble. You can close this issue. Thanks.
