### ISSUE TITLE
how can i stop printing info posting from gmsh 

### ISSUE THREAD

**Issue by shayanmazloom** [nschloe/pygmsh#328]
how can i stop printing info posting from gmsh ?
"""
Info    : Started on Sat Apr 18 10:57:33 2020
Info    : Reading 'C:\Users\HP\AppData\Local\Temp\tmp8xq8sch5.geo'...
Info    : Done reading 'C:\Users\HP\AppData\Local\Temp\tmp8xq8sch5.geo'
Info    : Meshing 1D...
Info    : [  0 %] Meshing curve 1 (Line)
Info    : [ 10 %] Meshing curve 2 (Line)
Info    : [ 10 %] Meshing curve 3 (Line)
Info    : [ 20 %] Meshing curve 4 (Line)
Info    : [ 20 %] Meshing curve 5 (Line)
Info    : [ 20 %] Meshing curve 6 (Line)
Info    : [ 30 %] Meshing curve 7 (Line)
Info    : [ 30 %] Meshing curve 8 (Line)
Info    : [ 30 %] Meshing curve 9 (Line)
Info    : [ 40 %] Meshing curve 10 (Line)
Info    : [ 40 %] Meshing curve 11 (Line)
Info    : [ 40 %] Meshing curve 12 (Line)
Info    : [ 50 %] Meshing curve 13 (Line)
Info    : [ 50 %] Meshing curve 14 (Line)
Info    : [ 50 %] Meshing curve 15 (Line)
Info    : [ 60 %] Meshing curve 16 (Line)
Info    : [ 60 %] Meshing curve 17 (Line)
Info    : [ 70 %] Meshing curve 18 (Line)
Info    : [ 70 %] Meshing curve 19 (Line)
Info    : [ 70 %] Meshing curve 20 (Line)
Info    : [ 80 %] Meshing curve 21 (Line)
Info    : [ 80 %] Meshing curve 22 (Line)
Info    : [ 80 %] Meshing curve 23 (Line)
Info    : [ 90 %] Meshing curve 24 (Line)
Info    : [ 90 %] Meshing curve 25 (Line)
Info    : [ 90 %] Meshing curve 26 (Line)
Info    : [100 %] Meshing curve 27 (Line)
Info    : [100 %] Meshing curve 28 (Line)
Info    : Done meshing 1D (0.03125 s)
Info    : Meshing 2D...
Info    : [  0 %] Meshing surface 1 (Plane, Frontal-Delaunay)
Info    : [ 50 %] Meshing surface 2 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (0.078125 s)
Info    : Meshing 3D...
Info    : Done meshing 3D (0 s)
Info    : 142 nodes 308 elements
Info    : Writing 'C:\Users\HP\AppData\Local\Temp\tmpyekrrjew.msh'...
Info    : Done writing 'C:\Users\HP\AppData\Local\Temp\tmpyekrrjew.msh'
Info    : Stopped on Sat Apr 18 10:57:33 2020
"""
and also how can i just run 2d mesh?

**Comment by gdmcbain** [comment]
> and also how can i just run 2d mesh?

Pass `dim=2` to `generate_mesh`.

https://github.com/nschloe/pygmsh/blob/ed0c9420f4319ded82bb4957bf5852809f797011/pygmsh/helpers.py#L55

**Comment by nschloe** [comment]
And `verbose=False`.

**Comment by shayanmazloom** [comment]
> > and also how can i just run 2d mesh?
> 
> Pass `dim=2` to `generate_mesh`.
> 
> https://github.com/nschloe/pygmsh/blob/ed0c9420f4319ded82bb4957bf5852809f797011/pygmsh/helpers.py#L55

thanks for your help

**Comment by shayanmazloom** [comment]
> And `verbose=False`.

thanks for your fast help!
