### ISSUE TITLE
set_transfinite_volume() method is missing in pygmsh

### ISSUE THREAD

**Issue by amrit-poudel** [nschloe/pygmsh#329]
I could not find set_transfinite_volume() method in pygmsh (read the doc) for the corresponding set_transfinite_volume() in Gmsh.
set_transfinite_surface() and set_transfinite_lines() methods do exist in pygmsh though.

Is there a way to set transfinite volume by other means in pygmsh?

Thanks.

**Comment by nschloe** [comment]
There's always `add_raw_code()`. I'd be happy about a PR for `set_transfinite_volume()`, too.

**Comment by amrit-poudel** [comment]
import pygmsh as pg

geom =  pg.opencascade.Geometry(characteristic_length_min=0.5, characteristic_length_max=1)
box = geom.add_volume(geom.add_surface_loop([rectangle1, rectangle2, rectangle3, rectangle4, rectangle5, rectangle6]))
code = f"Transfinite Volume {{{box.id}}}"
  geom.add_raw_code(code)

The above code does not quite work. GMSH raw code only requires ID of the volume. What am I missing?

**Comment by gdmcbain** [comment]
The syntax is [`Transfinite Volume { expression-list }`](http://gmsh.info/dev/doc/texinfo/gmsh.html#index-Transfinite-Volume-_007b-expression_002dlist-_007d-_003c-_003d-_007b-expression_002dlist-_007d-_003e-_003b); i.e. braces not parentheses, so try
```python
code = f"Transfinite Volume {{{box.id}}};"
```

**Comment by amrit-poudel** [comment]
import pygmsh as pg

s_wire_length = 4
s_wire_width  = 2
 s_wire_height  = 2
 s_grid_size = 1.0
 max_grid_size = s_grid_size
 min_grid_size = s_grid_size
  geom =  pg.opencascade.Geometry(characteristic_length_min=min_grid_size, characteristic_length_max=max_grid_size)
    point1 = geom.add_point([s_grid_size, 0.0, 0.0], s_grid_size)
    point2 = geom.add_point([s_grid_size, s_wire_width, 0.0], s_grid_size)
    point3 = geom.add_point([s_grid_size, s_wire_width, s_wire_height], s_grid_size)
    point4 = geom.add_point([s_grid_size, 0.0, s_wire_height], s_grid_size)
    point5 = geom.add_point([s_wire_length-s_grid_size, 0.0, 0.0], s_grid_size)
    point6 = geom.add_point([s_wire_length-s_grid_size, s_wire_width, 0.0], s_grid_size)
    point7 = geom.add_point([s_wire_length-s_grid_size, s_wire_width, s_wire_height], s_grid_size)
    point8 = geom.add_point([s_wire_length-s_grid_size, 0.0, s_wire_height], s_grid_size)
    line1 = geom.add_line(*[point1, point2])
    line2 = geom.add_line(*[point2, point3])
    line3 = geom.add_line(*[point3, point4])
    line4 = geom.add_line(*[point4, point1])
    line5 = geom.add_line(*[point1, point5])
    line6 = geom.add_line(*[point2, point6])
    line7 = geom.add_line(*[point3, point7])
    line8 = geom.add_line(*[point4, point8])
    line9 = geom.add_line(*[point5, point6])
    line10 = geom.add_line(*[point6, point7])
    line11 = geom.add_line(*[point7, point8])
    line12 = geom.add_line(*[point8, point5])
    rectangle1 = geom.add_plane_surface(geom.add_line_loop([line1, line2, line3, line4])) #left
    rectangle2 = geom.add_plane_surface(geom.add_line_loop([line4, line8, line12, line5])) #front
    rectangle3 = geom.add_plane_surface(geom.add_line_loop([line2, line7, line10, line6])) #back
    rectangle4 = geom.add_plane_surface(geom.add_line_loop([line1, line6, line9, line5])) #bottom
    rectangle5 = geom.add_plane_surface(geom.add_line_loop([line3, line7, line11, line8])) #top
    rectangle6 = geom.add_plane_surface(geom.add_line_loop([line9, line10, line11, line12])) #right
    box = geom.add_volume(geom.add_surface_loop([rectangle1, rectangle2, rectangle3, rectangle4, rectangle5, rectangle6]))
    geom.add_physical_volume(box, "wire") 
    code = f"Transfinite Volume {{{box.id}}};"
    geom.add_raw_code(code)
pg.generate_mesh(geom, msh_filename="wire.msh")


The above code generates the following error:
Error   : Incompatible surface 14 in transfinite volume 26

**Comment by gdmcbain** [comment]
This might be more of a Gmsh question than a pygmsh question.  It's not a syntactical error, it's semantic; you need to tell Gmsh more about the volume so that it knows how to treat it transfinitely.  Try some experiments in Gmsh without pygmsh first; e.g. try generalizing [t6.geo](http://gmsh.info/dev/doc/texinfo/gmsh.html#t6) to three dimensions.

**Comment by amrit-poudel** [comment]
Thanks for your help. I appreciate it.

I use the exact same approach in 2D, and it works fine. In 2D, I extrude a line to create another line and a surface, which I set to use transfinite algo. I am doing exactly the same in 3D. I extrude a surface (rectangle1) to create another surface rectangle1e and a volume  "left_box", which I set to use transfinite algo.  I am not quite sure what else I would need.

**Comment by gdmcbain** [comment]
In t6:
* Transfinite Curves are defined before the Transfinite Surface
* One of the Transfinite Surfaces has the right-hand side expression list.

For a Transfinite Volume,

>  The expression-list on the right-hand-side should contain the tags of the six or eight points on the boundary of the volume that define the corners of the transfinite interpolation. If no tags are given, the transfinite algorithm will try to find the corners automatically.

Maybe in this case the automatic try fails so Gmsh needs help in one of the two forms suggested above.
