### ISSUE TITLE
Create a .step file from pygmsh

### ISSUE THREAD

**Issue by caf13** [nschloe/pygmsh#332]
Dear all,

I am trying to bring the geometry generated in gmsh to run it in Ansys, however I have only successfully passed files in .step format which I have created in GMSH (without pygmsh), but I cannot find the way to generate .step files in pygmsh, I have only found to generate .vtk

**Comment by nschloe** [comment]
step files describe a geometry, not a mesh, so there is no way to get them out of pygmsh.

**Comment by gdmcbain** [comment]
This is true, but only a small step after pygmsh is required.

Assume you've created your `geom: pygmsh.built_in.Geometry` or `pygmsh.opencascade.Geometry` (more likely the latter).  Say as in my example from #344.  Then append to the pygmsh script to write the GEO file:
```python
with open("cylinder.geo", "w") as fgeo:
    fgeo.write(geom.get_code())
```

I have a separate little GEO script, `print.opt`:
```c++
Printf(StrCat(shape, ".geo"));
Include StrCat(shape, ".geo");
Print StrCat(shape, ".", fmt);
Exit;
```

which can be invoked from the shell with
```shell
gmsh print.opt -setstring shape cylinder -setstring fmt step
```

but one could probably use `geom.add_raw_code` to append the Gmsh `Print("cylinder.step");` command.
