### ISSUE TITLE
Simple mesh with no new points

### ISSUE THREAD

**Issue by MuellerSeb** [nschloe/pygmsh#333]
Hey there,

a stupid question. Is it possible with pygmsh/gmsh to create a mesh from a set of points, where no new points are added and the resulting mesh is the convex hull of the point cloud?

Cheers,
Sebastian

**Comment by nschloe** [comment]
Best use qhull via scipy for that. https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.Delaunay.html

**Comment by MuellerSeb** [comment]
Cool. Thanks for the hint!
