### ISSUE TITLE
tags are not conserved for same geo file

### ISSUE THREAD

**Issue by cTatu** [nschloe/pygmsh#340]
Hi. I'm using pygmsh and gmsh on 2 different computers. They have the same version on both.

3.0.6 for gmsh and 6.1.1 for pygmsh

The problem is that they generate different tags number for a given surface on the same geo code. I need they to stay constant because I use those tags to set a trasnfinite feature and also those are the boundary ids for running elmer simulations.
So for one computer the boundary faces are in complete different order and the simulation is useless.

How can I tell gmsh or pygmsh to use always the same ids or tags?

**Comment by nschloe** [comment]
Let's first check if it's a pygmsh or gmsh issue. Generate the geo file and see if it's the same on both machines. If not it's pygmsh. If yes, run it through gmsh on both machines and compare the output.

**Comment by cTatu** [comment]
Thank you for answering. I just checked and it's gmsh fault. I was using 3.0.6 which seems to not care about preserving tags of entities. I updated to 4.x and now it's working just fine. Thank you!
