### ISSUE TITLE
Extrude Circle to make Cylindrical Sheet

### ISSUE THREAD

**Issue by ManyAngledOne** [nschloe/pygmsh#344]
I don't seem to be able to generate a cylindrical sheet with pygmsh. I've been attempting to extrude a circle to make this possible, but I seem to be breaking the rules when I try this.
```
import pygmsh
gmsh_path = r'C:\gmsh-4.6.0-Windows64\gmsh.exe'

geom = pygmsh.opencascade.Geometry(
  characteristic_length_min=0.1,
  characteristic_length_max=0.1,
  )

circle=geom.add_circle( [0.0, 0.0, 0.0], 1.0)
 
geom.extrude(circle, translation_axis=[0, 0, 1])

mesh = pygmsh.generate_mesh(geom, gmsh_path=gmsh_path)`
```
I get `AssertionError: Illegal extrude entity.` because the object `circle` I pass into `geom.extrude` is not a `LineBase` object. See line 403 of geometry.py: `assert isinstance(input_entity, LineBase), "Illegal extrude entity."`

Using the gmsh gui alone it generates the code:
```
SetFactory("OpenCASCADE");
Circle(1) = {0, -0, 1, 1, 0, 2*Pi};
Extrude {0, 0, 1} { Curve{1}; }
```

**Comment by KeunwooPark** [comment]
You have to use ```add_disk()``` instead of ```add_circle()```. Please check [here](https://pygmsh.readthedocs.io/en/latest/opencascade.html).

**Comment by nschloe** [comment]
The code in the original example works for me:
![screenshot](https://user-images.githubusercontent.com/181628/91987468-60691780-ed2e-11ea-9243-d817fe58e43c.png)

**Comment by ManyAngledOne** [comment]
No, you misunderstand. I want a cylindrical sheet, not a cylinder. A 2d object like a pipe. An extruded circle, not an extruded disk.

**Comment by ManyAngledOne** [comment]
I can get what I want using the gmsh python API with this

```
import gmsh
import sys

gmsh.initialize(sys.argv)
gmsh.option.setNumber("General.Terminal", 1)
gmsh.model.occ.addCircle(0, 0, 0, 1)
gmsh.model.occ.extrude([(1, 1)], 0, 0, 0.5)
gmsh.model.occ.synchronize()
gmsh.model.mesh.generate(2)
gmsh.write("cylinder.msh")
```

![image](https://user-images.githubusercontent.com/7295786/92051813-3e7d8e00-ed4a-11ea-9694-f6d4f216dc44.png)

**Comment by gdmcbain** [comment]
```python
circle = geom.add_circle([0.0, 0.0, 0.0], 1.0, make_surface=False)

for arc in circle.line_loop.lines:
    geom.extrude(arc, translation_axis=[0, 0, 1])
```

![cylinder](https://user-images.githubusercontent.com/1588947/92061686-4127c400-edda-11ea-96cf-b6604b64c379.png)

**Comment by ManyAngledOne** [comment]
That looks great, thank you very very much. I can finally abandon the insanity inducing (for complicated geometries) gmsh api.
