### ISSUE TITLE
add_background_field removed?

### ISSUE THREAD

**Issue by jwittke** [nschloe/pygmsh#346]
Hi,

I didn't use pygmsh for a longer time but
what happens to

`pygmsh.built_in.geometry.Geometry.add_background_field`

The docs mention it 
<https://pygmsh.readthedocs.io/en/latest/built_in.html#pygmsh.built_in.geometry.Geometry.add_background_field>
but I can't find it in the code.

Thanks,
Jan

**Comment by nschloe** [comment]
If I recall correctly, it was removed from gmsh itself.

**Comment by nschloe** [comment]
You're probably looking for `set_background_mesh`, see https://github.com/nschloe/pygmsh#mesh-refinementboundary-layers. Available from pygmsh 7.0.0+ (to be released later today).
