### ISSUE TITLE
How to get the .geo file or .msh file

### ISSUE THREAD

**Issue by HongyuFF** [nschloe/pygmsh#349]
I run the examples show in readme file, it successful, and it told me it done write the .msh file and .gro file, but it is not in the direction in the document is shows, I also cant find it in hide file. How can I get the .geo file and .msh file use pygmsh code. can u give me an example?

![图片1](https://user-images.githubusercontent.com/67565219/88121470-c8570a80-cb93-11ea-9f71-f200968f9f6b.png)

**Comment by gdmcbain** [comment]
Check out the full list of arguments to `pygmsh.helpers.generate_mesh`:

https://github.com/nschloe/pygmsh/blob/4c8a002c4354f84398a1c95c3754f07ab4d43427/pygmsh/helpers.py#L86-L99

The ones you want are `geo_filename` and `msh_filename`.

_P. S.:&mdash;_  It's better to copy and paste error messages; it's difficult to search the content of a screen-grab.

**Comment by gdmcbain** [comment]
```python
from pygmsh.built_in import Geometry
from pygmsh.helpers import generate_mesh

geom = Geometry()
geom.add_point([0] * 3)

generate_mesh(geom, geo_filename='o.geo', msh_filename='o.msh')
```

**Comment by HongyuFF** [comment]
I copy the example in readme, the code is:
import pygmsh

geom = pygmsh.opencascade.Geometry(
  characteristic_length_min=0.1,
  characteristic_length_max=0.1,
  )

rectangle = geom.add_rectangle([-1.0, -1.0, 0.0], 2.0, 2.0)
disk1 = geom.add_disk([-1.2, 0.0, 0.0], 0.5)
disk2 = geom.add_disk([+1.2, 0.0, 0.0], 0.5)
union = geom.boolean_union([rectangle, disk1, disk2])

disk3 = geom.add_disk([0.0, -0.9, 0.0], 0.5)
disk4 = geom.add_disk([0.0, +0.9, 0.0], 0.5)
flat = geom.boolean_difference([union], [disk3, disk4])

geom.extrude(flat, [0, 0, 0.3])
mesh = pygmsh.generate_mesh(geom)

#
and it has the output 

Info    : Done optimizing mesh (Wall 0.00927401s, CPU 0.008447s)
Info    : 2169 nodes 11512 elements
Info    : Writing '/tmp/tmp4lart3kb.msh'...
Info    : Done writing '/tmp/tmp4lart3kb.msh'
Info    : Stopped on Tue Jul 21 21:08:40 2020 (From start: Wall 1.09102s, CPU 0.81345s)

but i cant find .msh in the document tmp

**Comment by HongyuFF** [comment]
i run the example and it has the same problem: It said it create the .msh file but I dont know where it is.
-----------------------------------------------------------------------------------------------------------------------------------------------
from pygmsh.built_in import Geometry

from pygmsh.helpers import generate_mesh

​

geom = Geometry()

geom.add_point([0] * 3)

​

generate_mesh(geom, geo_filename='o.geo', msh_filename='o.msh')

Info    : Running '/home/hongyu/.local/lib/python3.8/site-packages/gmsh-4.6.0-Linux64-sdk/lib/../bin/gmsh -3 o.geo -format msh -bin -o o.msh' [Gmsh 4.6.0, 1 node, max. 1 thread]
Info    : Started on Tue Jul 21 21:20:43 2020
Info    : Reading 'o.geo'...
Info    : Done reading 'o.geo'
Info    : Meshing 1D...
Info    : Done meshing 1D (Wall 3.09944e-06s, CPU 2.2e-05s)
Info    : Meshing 2D...
Info    : Done meshing 2D (Wall 1.50204e-05s, CPU 9.9e-05s)
Info    : Meshing 3D...
Info    : Done meshing 3D (Wall 2.59876e-05s, CPU 0.000157s)
Info    : 1 nodes 1 elements
Info    : Writing 'o.msh'...
Info    : Done writing 'o.msh'
Info    : Stopped on Tue Jul 21 21:20:43 2020 (From start: Wall 0.00143909s, CPU 0.035291s)

msh file: o.msh

geo file: o.geo

<meshio mesh object>
  Number of points: 1
  Number of cells:
    vertex: 1

**Comment by HongyuFF** [comment]
I find the direction in the terminal!
----
[I 21:38:22.427 NotebookApp] Saving file at /pyex/command.ipynb
-----
Thanks for your help!
