### ISSUE TITLE
Adding Physical Groups

### ISSUE THREAD

**Issue by Spranky63** [nschloe/pygmsh#35]
Hi

I am not sure if I am applying the `add_physical_volume` command correctly. For instance in the given extruded and twisted 4 point star example the extruded volume `vol` gets assigned the string `ex1` when I run the python script. But when I add
```
geom.add_physical_volume(vol, label='twisted_star')
```
no physical group volume in Gmsh appears because the volume is assigned in Gmsh the label name (`p1`) and not `ex1`. When I do
```
geom.add_physical_volume('p1', label='twisted_star')
```
that works.

I also note that when I inspect the Elementary Entities in Gmsh some lines are assigned names starting  with `p`. I started writing a python script of my own using pygmsh and saw later in Gmsh some line names starting with 'l' and some with 'p' . I though 'l' was for lines and 'p' for points. In the twisted star example Line1  (first assigned line of the polygon) also has the name (p1) in Gmsh. In the .geo text file produced by Python it is 'l1' as it might be expected. Not sure if this is a bug in Gmsh, or my understanding is flawed. I am running Gmsh 2.16.0  on OS X 10.11.6. In any case consistent naming  is important because, for example, the geom.add_polygon command creates a host of points, lines and surfaces that one might want to refer to later by 'p1', 'l1', 'surf1' etc., as more polygons get added.

Screenshot:

![gmsh screenshot](https://cloud.githubusercontent.com/assets/24934474/22185339/099adaba-e0e4-11e6-89e7-4395a84f1a1b.jpg)

Could you possibly add to the twisted star Python script example say a physical group name to the bottom and/or top star surfaces and also to the volume, and check in Gmsh that the physical groups appear as expected? I am using Elmer as the solver and assignment of the boundary conditions is made easier when the surfaces are defined as physical groups.

With thanks and appreciation for your efforts

**Comment by nschloe** [comment]
When using
```
geom.add_physical_volume(vol, label='mylabel')
```
after `geom.extrude` in the example, the resulting geo file will contain
```
ex1[] = Extrude{{0,0,1}, {0,0,1}, {0,0,0}, 1.0471975512}{Surface{surf1};};
Physical Volume("mylabel") = ex1;
```
Isn't this correct?

**Comment by Spranky63** [comment]
Hi

Thanks for answering.  Unfortunately I don't know how to organize the entities so that their names come out right in the GUI. What I did find out however is if I manually edit the .geo file so that after the extrude command it writes the Physical Volume line as shown below....

ex1[] = Extrude{{0,0,2}, {0,0,2}, {0,0,0}, 1.0471975512}{Surface{surf1};};
Physical Volume("twisted_star") = ex1[];

instead of   

Physical Volume("mylabel") = ex1;     

then it appears to generates a Physical Volume Group - see Screenshot

![screenshot](https://cloud.githubusercontent.com/assets/24934474/22218936/2baa2190-e1a9-11e6-958b-272434d2bf97.jpg)

Maybe the add_physical_volume command needs to be changed. The add_physical_surface command seems to work

geom.add_physical_surface(poly, label='star') will assign a physical group to the polygon star. 

On the subject of add_physical_surface my own problem is one of parametrising a general finned heatsink where I want to assign many surfaces the same physical group name. Below is how I do that at present

```
for i in range(numfins):
    geom.add_polygon([
    [i*(fingap+finbase), -base, 0.0],
    [i*(fingap+finbase)+finbase/2-fintip/2, -base-finlength, 0.0],
    [i*(fingap+finbase)+finbase/2-fintip/2, -base-finlength, -length],
    [i*(fingap+finbase), -base, -length]],
    lcar=edge
    )
    finsurfacelist += 'surf' + str(2*i+1) + ','  
    geom.add_polygon([
    [i*(fingap+finbase)+finbase/2+fintip/2, -base, 0.0],
    [i*(fingap+finbase)+finbase/2+fintip/2, -base, -length],
    [i*(fingap+finbase)+finbase, -base-finlength, -length],
    [i*(fingap+finbase)+finbase, -base-finlength, 0.0]],
    lcar=edge
    )
    finsurfacelist += 'surf' + str(2*i+2) + ','
finsurfacelist= finsurfacelist[:-1]
finsurfacelist += '}'
geom.add_physical_surface(finsurfacelist,'Fin_Surface')
```

Not that pretty, but it seems to work. Of course it also relies on the fact that each time add_polygon is used a surface 'surf' is added with successive numbering ie. surf1, surf2.

Keep up the good work.

**Comment by nschloe** [comment]
Okay, I've read up on the extrusion matter now and [found](http://www.manpagez.com/info/gmsh/gmsh-2.4.0/gmsh_66.php) about the return value of `Extrude`:
```
// This list will contain the "top" of the extruded surface (in
// out[0]) as well as the newly created volume (in out[1]).
```
To properly add the physical volume from the extrude, one hence has to do
```
// [...]
geom.add_physical_volume(vol + '[1]', label='labello')
```
which generates
```
ex1[] = Extrude{{0,0,1}, {0,0,1}, {0,0,0}, 1.0471975512}{Surface{surf1};};
Physical Volume("labello") = ex1[1];
```
This should be made clearer in pygmsh.

**Comment by nschloe** [comment]
Okay, I've improved this by making sure that `extrude` now returns two items,
```
top, extruded = extrude(...)
```
This coincides with how Gmsh treats this. The first is the "top" surface or line from where the extrusion started, and the second is the extruded entity, i.e., a surface or a volume.

Creating a physical volume from an extrusion is now as easy as
```
top, vol = extrude(...)
geom.add_physical_volume(vol, label='twisted_star')
```
