### ISSUE TITLE
How to import a numpy array

### ISSUE THREAD

**Issue by Ali1990dashti** [nschloe/pygmsh#351]
Dear community,

Firstly, for me it was fantaric to hear that you have developed a python version of gmsh. I only used the software to generate meshes. I am using another python library (Gempy: https://github.com/cgre-aachen/gempy) to create some models. That library is giving me my results as some ids in a meshed environment, but meshes are rectangular. That package is very efficient for doing geological modelling and defining the distribution of different layers. Now, I wanted to use the layering result of tht pachage as an input for gmsh to do the meshing. The results of the moddeler are x,y,z and an id which is the property of each node or voxel. this property says that each voxel belongs to which layer. 
Now, can I use the results of that model as an input for meshing by the developed gmsh?
In advance, I appreciate any response and contribution to my request.

Regards
Ali

**Comment by nschloe** [comment]
If you can do it in gmsh, you can do it in pygmsh.

**Comment by Ali1990dashti** [comment]
Dear @nschloe ,

Thanks for your response. I have not done meshing in gmsh with the outputs of the Gempy. I always define points, lines, surfaces, and so on to make a meshed environment in gmsh. Now, I wanted to apply the mentioned procedure (using a numpy array containing some data).
Is there any tutorial on pygmsh strating from the scratch?
Thanks for your help

**Comment by nschloe** [comment]
> Is there any tutorial on pygmsh strating from the scratch?

The `README` and the docs (see link in readme).

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time!
