### ISSUE TITLE
Error_in_running_the_test_sample

### ISSUE THREAD

**Issue by Ali1990dashti** [nschloe/pygmsh#353]
Dear all,
hope doing well and being healthy. I wanted to redo the example presented in read me, but unfortunately I faced the following error:

Is gmsh installed?
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-f2bc847bedfa> in <module>
----> 1 mesh = pygmsh.generate_mesh(geom)

~\Anaconda3\envs\enviro\lib\site-packages\pygmsh\helpers.py in generate_mesh(geo_object, verbose, dim, prune_vertices, prune_z_0, remove_lower_dim_cells, gmsh_path, extra_gmsh_arguments, geo_filename, msh_filename, mesh_file_type)
    154     # https://stackoverflow.com/a/803421/353337
    155     try:
--> 156         p = subprocess.Popen(
    157             [gmsh_executable] + args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
    158         )

~\Anaconda3\envs\enviro\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    852                             encoding=encoding, errors=errors)
    853 
--> 854             self._execute_child(args, executable, preexec_fn, close_fds,
    855                                 pass_fds, cwd, env,
    856                                 startupinfo, creationflags, shell,

~\Anaconda3\envs\enviro\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1305             # Start the process
   1306             try:
-> 1307                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1308                                          # no special security
   1309                                          None, None,

FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```
I just copied and pasted the existing syntax. Can anyone please help me to tack this error?
In advance I appreciate any feedback.
cheers,

**Comment by nschloe** [comment]
You don't have gmsh installed or Python cannot find it.

**Comment by Ali1990dashti** [comment]
I installed it but I have no idea why it does not work here.
![ffff](https://user-images.githubusercontent.com/62764899/91046581-fc04d480-e618-11ea-9ed4-e0bb74961147.jpg)

**Comment by nschloe** [comment]
pygmsh needs the gmsh executable, not the python module.

_Note:_ Never post screenshots, always post copy-pasted code. Also make sure to format it properly using code fences.

**Comment by Ali1990dashti** [comment]
Thanks for you hints.
Can you please make it more clear how I can make the gmsh executable?
I think there is also a problem with my pygmsh, because when I call
```
import pygmsh
pygmsh.__version__
```
It gives me:
`'unknown'`
Is it okay to have such type of version for pygmsh?
Thanks for the feedbacks

**Comment by gdmcbain** [comment]
> Can you please make it more clear how I can make the gmsh executable?

It looks like you're running Anaconda? If so, in a shell with your conda env activated, try
```shell
conda install pip
pip install gmsh-sdk
```

**Comment by Ali1990dashti** [comment]
Dear @gdmcbain 

Thanks for your hints. But still I have the same problem. I installed both the pip and also gmsh-sdk, but still I am facing the previous error (Is gmsh installed?).

**Comment by gdmcbain** [comment]
Yes? So it looks like you're working under Microsoft Windows. What happens if you open an *Anaconda Command Prompt* and enter the following :
```shell
conda create -n pygmsh-353
conda activate pygmsh-353
conda install pip
pip install gmsh-sdk pygmsh 
gmsh -version
python your_script.py
```

**Comment by Ali1990dashti** [comment]
I created the new environment and installed pip and gmsh-sdk pygmsh. the version of gmsh is also 4.6.0. But what do you mean by the last line (python your_script.py)? should I copy my syntax (including data and codes) directly as a python command?
I always use jupyter notebook to copy the syntax and then run the model.

**Comment by gdmcbain** [comment]
Oh, a Jupyter notebook? I don't know much about them, sorry.

> But what do you mean by the last line (python your_script.py)? should I copy my syntax (including data and codes) directly as a python command

Create a Python script file (.py suffix) with lines of Python commands, like in [test_pacman.py](https://github.com/nschloe/pygmsh/blob/master/test/test_pacman.py). Save it to the current directory and call python on it. This doesn't necessarily fix your notebook problem but it does narrow down your problem to Jupyter.

**Comment by Ali1990dashti** [comment]
Yes, I usually use Jupyter and thought maybe ir is possible to do pygmsh staff in Jupyter. But it seems that I must shift to python to run prepared .py files.

**Comment by nschloe** [comment]
Alright, everything's new with the 7.0.0 update, so chances are this is fixed now. Feel free to reopen if not.
