### ISSUE TITLE
Filtering Exterior and Interior Points

### ISSUE THREAD

**Issue by KeunwooPark** [nschloe/pygmsh#357]
Hi. Is it possible to filter the exterior and interior points of 2D and 3D mesh with pygmsh?
I'm new to gmsh and pygmsh. If it is not what (py)gmsh can do, then please suggest other libraries.

**Comment by nschloe** [comment]
I don't know about gmsh. Take a look at [meshplex](https://github.com/nschloe/meshplex), it has `is_interior_node` and `is_boundary_node`.
