### ISSUE TITLE
Hole generation

### ISSUE THREAD

**Issue by ffilotto** [nschloe/pygmsh#358]
I am trying to generate an extruded volume  with holes. 
To create the Surface, i run .add_polygon, with the option "holes". This should be a list of LineLoops.

When inspecting the resulting .geo file, no LineLoops are actually created, but are later referenced and it creates a warning.

Looking at the code, it seems that hole generation is quite "early stage" and actually not working. 

Am I correct?

If so, I'll do a PR for correcting hole generation, at least for add_polygon at first.

**Comment by nschloe** [comment]
MWE please.

**Comment by ffilotto** [comment]
Sorry.

`
import pygmsh
import meshio

# Create square
points_poly= [[-1,-1,0],[1,-1,0],[1,1,0],[-1,1,0]]
points_hole1 = [[-0.5,-0.5,0],[0.5,-0.5,0],[0.5,0.5,0],[-0.5,0.5,0]]

# Create LineLoop from
holes = []
points = []
for ip,p in enumerate(points_hole1):
    points.append(pygmsh.built_in.point.Point(p))
lines = []
for ip,p in enumerate(points): 
    p0 = p
    if ip<len(points)-1:
        p1 = points[ip+1]
    else:
        p1 = points[0]

    lines.append(pygmsh.built_in.line.Line(p0,p1))

holes.append(pygmsh.built_in.line_loop.LineLoop(lines))

# Ideally, we could have a LineLoop defined as point list
# holes.append(points_hole1)

geom = pygmsh.built_in.Geometry()
poly = geom.add_polygon(points_poly,lcar=0.25,holes=holes)
mesh = pygmsh.generate_mesh(geom, prune_vertices=True, verbose=False, remove_lower_dim_cells=True)
`
And the output .geo file is 

`// This code was created by pygmsh vunknown.
p4 = newp;
Point(p4) = {-1, -1, 0, 0.25};
p5 = newp;
Point(p5) = {1, -1, 0, 0.25};
p6 = newp;
Point(p6) = {1, 1, 0, 0.25};
p7 = newp;
Point(p7) = {-1, 1, 0, 0.25};
l4 = newl;
Line(l4) = {p4, p5};
l5 = newl;
Line(l5) = {p5, p6};
l6 = newl;
Line(l6) = {p6, p7};
l7 = newl;
Line(l7) = {p7, p4};
ll1 = newll;
Line Loop(ll1) = {l4, l5, l6, l7};
s0 = news;
Plane Surface(s0) = {ll1,ll0};`

The problem is that 'll0' is never created. Eventually, it would be nice if holes coulb be a list of point coordinates as the first argumento of 'add_poligon'

**Comment by ffilotto** [comment]
I guess I might have misunderstood how 'holes' was implemented. It need to reference points, lines and line loops already existing (meaning, I need to add them with '.add_point', '.add_line' and so on), is it correct? It was just a bit confusing because the polygon (points, lines and line loops) itself is created by the function, so I was expecting a similar behaviour for the 'holes' argument.

Do you think it's worth to do a PR for having 'holes' defined as a list of points?

**Comment by nschloe** [comment]
Check [here](https://github.com/nschloe/pygmsh/blob/master/test/test_hole_in_square.py) for a reference how to use holes. I think it's rather clear and it mirrors how gmsh does it. Probably not worth changing the API here.
