### ISSUE TITLE
README example error

### ISSUE THREAD

**Issue by krober10nd** [nschloe/pygmsh#369]
* Using pygalmesh==0.7.2 and gmsh 4.6.0 on MacOS Catalina, I copy and pasted code from the `pygmsh` README into a file and received this error: 

* MWE: 

```
from math import sqrt
import pygmsh
 
 
with pygmsh.occ.Geometry() as geom:
    geom.add_ball([0.0, 0.0, 0.0], 1.0)
 
    geom.set_mesh_size_callback(
        lambda dim, tag, x, y, z: abs(sqrt(x ** 2 + y ** 2 + z ** 2) - 0.5) + 0.1
    )
    mesh = pygmsh.generate_mesh(geom)
```

* error: 
```
$ python blah.py 
Traceback (most recent call last):
  File "blah.py", line 9, in <module>
    lambda dim, tag, x, y, z: abs(sqrt(x ** 2 + y ** 2 + z ** 2) - 0.5) + 0.1
  File "/Users/Keith/firedrake/lib/python3.7/site-packages/pygmsh/common/geometry.py", line 305, in set_mesh_size_callback
    gmsh.model.mesh.setSizeCallback(fun)
AttributeError: type object 'mesh' has no attribute 'setSizeCallback'
```

**Comment by nschloe** [comment]
You need gosh 4.7+, i.e., build from master for now.

**Comment by krober10nd** [comment]
Hm, I see. So I get that through here 

https://gmsh.info/? 

The development `pypi` installs 4.6 and all the brew formulas are for 4.6. Guess install by source manually?

**Comment by nschloe** [comment]
That's what I did. We could press for a release, too.

**Comment by krober10nd** [comment]
Okay...I tried installing `gmsh` from source to get 4.7.0. It didn't work so I started this [issue](https://gitlab.onelab.info/gmsh/gmsh/-/issues/1007)

**Comment by krober10nd** [comment]
macOS Catalina 10.15

**Comment by nschloe** [comment]
Ah okay, don't know then. (I'm on Linux myself.) Let's see what the gmsh devs have to say.

**Comment by krober10nd** [comment]
So according to the gitlab thread I posted above, Christopher told me to use the SDK-dev `gmsh` package which works by itself just fine. I guess I just need to figure out how to hook this up so `pygmsh` sees it.

**Comment by krober10nd** [comment]
So I updated to `gmsh` 7.0 (I also had to updated `meshio`) but there was a typo in the README in any case. 

For the section of the README with the sphere with the inner ring of finer resolution, this worked for me:

```
     mesh = geom.generate_mesh()
```

This did not work (which is what written):

```
    mesh = pygmsh.generate_mesh(geom)
```

**Comment by nschloe** [comment]
Fixed.
