### ISSUE TITLE
Adding Polygons or Rectangles that share common points and lines

### ISSUE THREAD

**Issue by Spranky63** [nschloe/pygmsh#37]
Hi Nico

The add_polygon or add_rectangle commands are very useful in that points, lines, and line loops are all created for you and so do not complicate the code. However, if you add polygons or rectangles that share common points and lines new points and lines will still be created with the same coordinates, and Gmsh does not seem to like that. It would be useful I think if an option could be added to these commands in which a list of existing polygons/rectangles could be added as an argument so that the command could then identify existing points and lines (within a tolerance bound) and not generate new ones. 

Imagine how much simpler the following code would look without the add_point, add_line, add_line_loop commands

```
for i in range(numfins):
    points[8*i] = geom.add_point([i*(fingap+finbase), -base, 0.0],edge)
    points[8*i+1] = geom.add_point([i*(fingap+finbase)+finbase/2.0-fintip/2.0, -base-finlength, 0.0],edge)
    points[8*i+2] = geom.add_point([i*(fingap+finbase)+finbase/2.0-fintip/2.0, -base-finlength, -length],edge)
    points[8*i+3] = geom.add_point([i*(fingap+finbase), -base, -length],edge)
    lines[8*i] = geom.add_line(points[8*i],points[8*i+1])
    lines[8*i+1] = geom.add_line(points[8*i+1],points[8*i+2])
    lines[8*i+2] = geom.add_line(points[8*i+2],points[8*i+3])
    lines[8*i+3] = geom.add_line(points[8*i+3],points[8*i])
    loops[2*i] = geom.add_line_loop({lines[8*i],lines[8*i+1],lines[8*i+2],lines[8*i+3]})
    surfaces[2*i] = geom.add_plane_surface(loops[2*i])
```

**Comment by nschloe** [comment]
I don't get it yet. You'd to share points between polygons, but not create the points manually?

An MWE always helps.

**Comment by Spranky63** [comment]
I was sure I had an issue with Gmsh when multiple points/lines were created with the same coordinates. I think I will retract that statement. I just tried a simple example with two polygons adjoining each other and there was no problem with Gmsh. The Physical Surfaces that were added were also identified. The visibility window in Gmsh suggests 8 points and 8 lines are added and I thought this was causing the problem I was having as only 6 and 7 are needed, but it must have been something else - sorry. I will try my own code again using add_polygon. Please close the issue.

```
geom = pg.Geometry()

poly1 = geom.add_polygon([
    [0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [1.0, 1.0, 0.0],
    [1.0, 0.0, 0.0],
    ],
    lcar=0.1
    )

poly2 = geom.add_polygon([
    [0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [-1.0, 1.0, 0.0],
    [-1.0, 0.0, 0.0],
    ],
    lcar=0.1
    )

geom.add_physical_surface(poly1,'poly1')
geom.add_physical_surface(poly2,'poly2')
```
![screenshot](https://cloud.githubusercontent.com/assets/24934474/22406818/0c76487a-e65a-11e6-97aa-099f8928a52a.jpg)

**Comment by nschloe** [comment]
Feel free to reopen if you meet the error again or have any other suggestions. Well worked-out case studies like this one here are always welcome!

**Comment by cweickhmann** [comment]
I ran into a similar issue with `add_polygon` in the geo kernel (did not test with OpenCascade):
When I create two adjacent polygons, the common points and edges are actually created twice and so the overall domain is not connected. Instead, one has to create all the points and then iterate over and connect them.

I naively thought the whole purpose of `add_polygon` was to automate this.

**Comment by TysonRayJones** [comment]
To further @cweickhmann's point, imagine that you have floating-point coordinates of the vertices of many polygons. They *should* all abut, but floating-point error means there exist multiple unique approximations of the same coordinate. If `add_polygon` behaved as suggested above, this would cause no issue; the user would blindly feed in their coordinates and near-enough-to-be-equivalent coordinates would be merged. 

Alas, if this doesn't happen, the workaround is quite cumbersome: one has to manually map each floating-point coordinate to an existing point label (or create a new one, if none existing are sufficiently close). All well and good for 2D working, but then once the polygons are extruded (whereby extruded coordinates *do* seem to undergo automatic merging), this manual process becomes nightmarish.

**Comment by Social-Mean** [comment]
> ![image](https://user-images.githubusercontent.com/15192310/110149397-4c39cc00-7dde-11eb-97ae-a5a59e8a8f77.png)

@cweickhmann Hi, what is the code to generate such a geometry with mesh shown on the image? I want to create two geometries that are adjacent to each other.
