### ISSUE TITLE
Can't find Geometry

### ISSUE THREAD

**Issue by SteveDoyle2** [nschloe/pygmsh#372]
I tried running your B-spline example and ran into an issue.  I made an updated version to help me debug it a bit, but got stuck.

I'm using:
 - Windows 10
 - Python 3.7.7
 - pygmsh 7.0.0
 - meshio 4.2.1
 - numpy 1.19.1

```
import pygmsh
import pygmsh.geo
from pygmsh.geo import Geometry

with Geometry() as geom:
    lcar = 0.1
    p1 = geom.add_point([0.0, 0.0], lcar)
    p2 = geom.add_point([1.0, 0.0], lcar)
    p3 = geom.add_point([1.0, 0.5], lcar)
    p4 = geom.add_point([1.0, 1.0], lcar)
    s1 = geom.add_bspline([p1, p2, p3, p4])

    p2 = geom.add_point([0.0, 1.0], lcar)
    p3 = geom.add_point([0.5, 1.0], lcar)
    s2 = geom.add_spline([p4, p3, p2, p1])

    ll = geom.add_curve_loop([s1, s2])
    pl = geom.add_plane_surface(ll)

    mesh = geom.generate_mesh()
```

It fails on line 3 (from pygmsh.geo import Geometry) with:
```
Traceback (most recent call last):
  File ".\gmsh.py", line 1, in <module>
    import pygmsh
  File "C:\Python37\lib\site-packages\pygmsh\__init__.py", line 1, in <module>
    from . import geo, occ
  File "C:\Python37\lib\site-packages\pygmsh\geo\__init__.py", line 1, in <module>
    from .geometry import Geometry
  File "C:\Python37\lib\site-packages\pygmsh\geo\geometry.py", line 1, in <module>
    import gmsh
  File "C:\utilities\gmsh.py", line 3, in <module>
    from pygmsh.geo import Geometry
ImportError: cannot import name 'Geometry' from 'pygmsh.geo' (C:\Python37\lib\site-packages\pygmsh\geo\__init__.py)
```

Looking at the pygmsh and pygmsh.geo init files, I see you're using relative imports.  Is this maybe the reason that it's not working properly?

**Comment by nschloe** [comment]
Relative imports are perfectly legal. I have no idea why it doesn't work for you.

**Comment by SteveDoyle2** [comment]
Got it...I was looking at the traceback and I saw:

  File "C:\Python37\lib\site-packages\pygmsh\geo\geometry.py", line 1, in <module>
    import gmsh

My test file was "gmsh.py".  Seems like an odd scoping rule.  I would assume python would look to the global scope, but apparently not.  It's strange that it failed the way it did.

**Comment by SteveDoyle2** [comment]
To be clear, I just changed the filename to "test_pygmsh.py" and it works.

**Comment by nschloe** [comment]
Well done.
