### ISSUE TITLE
Sizing function agreement

### ISSUE THREAD

**Issue by krober10nd** [nschloe/pygmsh#375]
Building my own 2D sizing function and querying it during mesh generation seems to produce a mesh that does not agree with the sizing function. I would take an educated guess and imagine that there's some very low gradation rate being enforced here but I'm not sure how to turn that off. However, I did not observe this disagrement in mesh size distribution in 3D just 2D so far.

Anyway, here's the MWE. It requires `SeismicMesh V3.0.2` and a file you can download on the readme of SeismicMesh for the 2d example to build the sizing function from a seismic velocity model. 
```python
import meshio
import pygmsh
 
from SeismicMesh import get_sizing_function_from_segy, Rectangle
  
# Name of SEG-Y file containg velocity model.
fname = "vel_z6.25m_x12.5m_exact.segy"
 
bbox = (-12000, 0.0, 0.0, 67000.0)
rectangle = Rectangle(bbox)
 
# Construct mesh sizing object from velocity model
ef = get_sizing_function_from_segy(
    fname,
    bbox,
    hmin=75.0,
    wl=10,
    freq=2,
    dt=0.001,
    grade=0.15,
)
 
with pygmsh.geo.Geometry() as geom:
    geom.add_rectangle(-12e3, 0.0, 0.0, 67e3, 0.0) 
    geom.set_mesh_size_callback(lambda dim, tag, x, y, z: (ef.eval([x, y])) / 1.1)
    mesh = geom.generate_mesh() 
mesh.write("BP2004_gmsh.vtk")
```

I end up with this which kind of looks like something but is pretty largely off from the true sizing function (which is already graded). 

![1](https://user-images.githubusercontent.com/181628/94990680-4b2a1780-057e-11eb-9079-e1e9564d16b8.png)

According to me, it should look like this: 

![2](https://user-images.githubusercontent.com/181628/94990683-4e250800-057e-11eb-8af3-72144671efb1.png)

**Comment by nschloe** [comment]
(Just FYI: ParaView has a screen shot function too. File->Save Screenshot. This captures less of what you don't want.)

**Comment by krober10nd** [comment]
Updated.

**Comment by nschloe** [comment]
As per @geuzaine's suggestion (https://gitlab.onelab.info/gmsh/gmsh/-/issues/1015), could you try
```python
import gmsh
gmsh.option.setNumber('Mesh.Algorithm', 5)
```
and see if anything changes?

**Comment by krober10nd** [comment]
Thanks Nico for posting that issue. Adding those lines in the appropriate places produces the following error. 

```
    gmsh.option.setNumber("Mesh.Algorithm", 5)
  File "/Users/Keith/firedrake/lib/python3.7/site-packages/gmsh-git-MacOSX-sdk/lib/gmsh.py", line 309, in setNumber
    raise Exception(logger.getLastError())
  File "/Users/Keith/firedrake/lib/python3.7/site-packages/gmsh-git-MacOSX-sdk/lib/gmsh.py", line 6711, in getLastError
    raise Exception('Could not get last error')
Exception: Could not get last error
```

I wonder if its possible to pass this option to `generate_mesh`? Seems that I need to initialize some other stuff. Besides that, I didn't find this `algorithm 5` option in the `gmsh` website just this:https://gmsh.info/doc/texinfo/gmsh.html#Choosing-the-right-unstructured-algorithm

**Comment by krober10nd** [comment]
Ok thanks! So this is what I get with running this code changing the algorithm type to 5 (not much difference it seems besides the quality looks worse than before): 

```
 import pygmsh
 
 from SeismicMesh import get_sizing_function_from_segy, Rectangle
 import gmsh
 
 
 # Name of SEG-Y file containg velocity model.
 fname = "vel_z6.25m_x12.5m_exact.segy"
 
 bbox = (-12000, 0.0, 0.0, 67000.0)
 rectangle = Rectangle(bbox)
 
 # Construct mesh sizing object from velocity model
 ef = get_sizing_function_from_segy(
     fname,
     bbox,
     hmin=75.0,
     wl=10,
     freq=2,
     dt=0.001,
     grade=0.15,
 )
 
 with pygmsh.geo.Geometry() as geom:
     geom.add_rectangle(-12e3, 0.0, 0.0, 67e3, 0.0)
     geom.set_mesh_size_callback(lambda dim, tag, x, y, z: (ef.eval([x, y])) / 1.1)
     gmsh.option.setNumber("Mesh.Algorithm", 5)
     mesh = geom.generate_mesh()
 mesh.write("BP2004_gmsh.vtk")
```

![BP2004_gmsh_algo5](https://user-images.githubusercontent.com/18619644/95030616-57e66280-0687-11eb-88c0-39216ac8f4d8.png)

Besides, what exactly does algorithm 5 mean? I can't seem to find much on these number options for the algorithms actually.

**Comment by geuzaine** [comment]
See [Mesh.Algorithm](http://gmsh.info/doc/texinfo/gmsh.html#index-Mesh_002eAlgorithm) for the values `Mesh.Algorithm` can take.

Did you disable mesh size interpolation from the boundary, i.e. set `gmsh.option.setNumber("Mesh.CharacteristicLengthExtendFromBoundary", 0)`, as explained in the [tutorial on mesh size fields](http://gmsh.info/doc/texinfo/gmsh.html#t10)?

**Comment by krober10nd** [comment]
Thanks @geuzaine  that worked. 
![BP2004_gmsh_algo5_v2](https://user-images.githubusercontent.com/18619644/95078773-0d4b0180-06ec-11eb-8f67-8828cb1437c6.png)

**Comment by geuzaine** [comment]
PS: does it also work with the default algorithm (Frontal-Delaunay)?

**Comment by krober10nd** [comment]
Yep, they both work and produce similar results. This is with the default. It's slightly faster (the default) by about 2 seconds.
![BP2004_gmsh_default_v2](https://user-images.githubusercontent.com/18619644/95080043-e097e980-06ed-11eb-8394-a05e831a792c.png)

**Comment by nschloe** [comment]
The setting `CharacteristicLengthExtendFromBoundary` and friends to `0` is now the default when you `set_mesh_size_callback`.
