### ISSUE TITLE
OpenCASCADE revolve angle = 2*pi

### ISSUE THREAD

**Issue by daalgi** [nschloe/pygmsh#384]
https://github.com/nschloe/pygmsh/blob/ee66103e915e6b58b2949ef7e3fd37c7bbb4b134/pygmsh/common/geometry.py#L182

Is it possible to skip this line when using the OpenCASCADE kernel?

The OpenCASCADE kernel in Gmsh 4.6.0 does not have the limitation of angle < Pi. Working example in a .geo file:

```SetFactory("OpenCASCADE");    
Rectangle(1) = {2, 0, 1, 3, 4, 0};    
Extrude {{0, 1, 0}, {0, 0, 0}, Pi*2} {    
    Surface{1}; Layers{36}; Recombine;    
}
```

**Comment by nschloe** [comment]
Fixing this now. Note that I added a less strict assertion for `occ::revolve()` based on its docstring:
```
When the mesh is extruded the angle should be strictly smaller than 2*Pi
```
