### ISSUE TITLE
[“ELEMENT - The Exascale Mesh Network”] ExCALIBUR ELEMENT project

### ISSUE THREAD

**Issue by krober10nd** [nschloe/pygmsh#385]
* In case you're interested:

https://epcced.github.io/ELEMENT/workshops.html

**Comment by nschloe** [comment]
Thanks Keith for the invitation! These days, I'm not so interested in extreme scaling anymore. I try to make sure that the bottleneck of my applications is an axpy or a dot product and I'll leave the rest to the domain experts. Feel free to ping me for other events, though!

**Comment by krober10nd** [comment]
No problem.  I understand your point of view. I just do things out of necessity these days but I always find mesh generation interesting. 

 I unfortunately couldn't attend because it started at 4 am Sao Paulo time. Hopefully someone recorded some slides. @geuzaine was this recorded or do you have any slides that could be please shared from it?

**Comment by geuzaine** [comment]
The slides are online: https://epcced.github.io/ELEMENT/workshops.html
