### ISSUE TITLE
AttributeError: module 'meshio.gmsh' has no attribute 'gmsh_to_meshio_type'

### ISSUE THREAD

**Issue by nilswagner** [nschloe/pygmsh#386]
The following script raises the attribute error. The example is taken from https://pypi.org/project/pygmsh/
I am using
```
>>> import pygmsh
>>> pygmsh.__version__
'6.1.1'
>>> import meshio
>>> meshio.__version__
'4.1.0'
```
```
# ellpsoid with holes
import pygmsh

with pygmsh.occ.Geometry() as geom:
    geom.characteristic_length_max = 0.1
    ellipsoid = geom.add_ellipsoid([0.0, 0.0, 0.0], [1.0, 0.7, 0.5])

    cylinders = [
        geom.add_cylinder([-1.0, 0.0, 0.0], [2.0, 0.0, 0.0], 0.3),
        geom.add_cylinder([0.0, -1.0, 0.0], [0.0, 2.0, 0.0], 0.3),
        geom.add_cylinder([0.0, 0.0, -1.0], [0.0, 0.0, 2.0], 0.3),
    ]
    geom.boolean_difference(ellipsoid, geom.boolean_union(cylinders))

    mesh = geom.generate_mesh()
```

**Comment by gdmcbain** [comment]
That pygmsh code looks like it's for pygmsh 7, not 6.1.1.

**Comment by gdmcbain** [comment]
I mean I'm surprised that it got to the last line, which is the first to involve meshio, since there was no pygmsh.occ in pygmsh<7. It had been called [pygmsh.opencascade](https://github.com/nschloe/pygmsh/tree/v6.1.1/pygmsh/opencascade).

**Comment by nschloe** [comment]
Outdated meshio. https://github.com/nschloe/pygmsh/blob/master/setup.cfg#L41
