### ISSUE TITLE
EP3118 format string warning

### ISSUE THREAD

**Issue by malessandro** [nschloe/pygmsh#391]
Running any example code like:

    with pygmsh.occ.Geometry() as geom:
        geom.characteristic_length_max = 0.1
        r = 0.5
        disks = [
            geom.add_disk([-0.5 * cos(7 / 6 * pi), -0.25], 1.0),
            geom.add_disk([+0.5 * cos(7 / 6 * pi), -0.25], 1.0),
            geom.add_disk([0.0, 0.5], 1.0),
        ]
        geom.boolean_intersection(disks)
        mesh = geom.generate_mesh()

I got this warning:

> python3.7/site-packages/numpy/ctypeslib.py:521: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
  return array(obj, copy=False)

I didn't get the warning using pygmsh==6.0.2.

can I overlook it?

**Comment by nschloe** [comment]
The error goes away when using Python 3.8+.
