### ISSUE TITLE
Physical labels

### ISSUE THREAD

**Issue by beckerrh** [nschloe/pygmsh#410]
Hello,
Trying to understand the new treatment of physical labels, I have the impression that using the same label twice results in 
a strange behavior, an empty label is created for the second group. If I remember correctly, previously the second group was added to the first (at least this is what I would have expected). See the following example.
Best regards,
Roland
```python
import pygmsh
with pygmsh.geo.Geometry() as geom:
    p = geom.add_rectangle(-1, 1, -1, 1, z=0, mesh_size=1)
    geom.add_physical(p.lines[0], label="A")
    geom.add_physical(p.lines[1], label="A")
    geom.add_physical(p.surface, label="100")
    mesh = geom.generate_mesh()
print(f"{mesh.cell_sets=}")
```

**Comment by nschloe** [comment]
Duplicate labels are now disallowed to avoid such confusion. Best use
```python
geom.add_physical([p.lines[0], p.lines[1]], label="A")
```

**Comment by Mirialex** [comment]
hi, do you have any documentation to share on how to use add_physical()?
