### ISSUE TITLE
[Feature request] Load shape from CAD files, add_shapes_from_file() 

### ISSUE THREAD

**Issue by BinWang0213** [nschloe/pygmsh#428]
Hi,

I'd like to use `Merge` to load a CAD geometry and then perform other operations using pygmsh.

Currently, I have to use the following code by mixing gmsh API and pygmsh

```python
import pygmsh
from pygmsh.occ.dummy import Dummy

with pygmsh.occ.Geometry() as geom:
    #Load geometry and create pygmsh obj for it
    s =   gmsh.model.occ.importShapes('MP3.igs')
    surfaces_load = [Dummy(*i) for i in s]

    disk=geom.add_disk([4.00582951, 0.25997906],0.04,0.04)
    geom.boolean_difference(surfaces_load, disk)

    geom.save_geometry('test.brep')
```
![image](https://user-images.githubusercontent.com/20053787/108460443-51274900-723e-11eb-8546-ca96a58ab798.png)
[MP3.zip](https://github.com/nschloe/pygmsh/files/6007782/MP3.zip)

So I suggest to add `import_shapes` function in pygmsh. Here is a draft code I have:

```
from pygmsh.occ.dummy import Dummy

def import_shapes(fname):      
      s = gmsh.model.occ.importShapes(fname)
      return [Dummy(*i) for i in s]

```

Do you have a better idea to implement this?

**Comment by nschloe** [comment]
Thanks the suggestion, added this just now. For changes like this, you can also provide a PR, this makes things easier for me.
