### ISSUE TITLE
access different gmsh meshers

### ISSUE THREAD

**Issue by bigfooted** [nschloe/pygmsh#444]
I could not find how to select the mesher (delaunay, bamg, initial mesh only, etc.)
Is this possible?

**Comment by nschloe** [comment]
Sure. `generate_mesh` has the `algorithm` argument that takes an integer, see http://gmsh.info/doc/texinfo/gmsh.html#index-Mesh_002eAlgorithm.

**Comment by bigfooted** [comment]
Oh that is great, thanks! Much better than mixing directly with gmsh options like 
gmsh.option.setNumber("Mesh.Algorithm", Number)
