### ISSUE TITLE
How to have "Line{l4} In Surface{s0}" in pygmsh 7?

### ISSUE THREAD

**Issue by tbenthompson** [nschloe/pygmsh#445]
In pygmsh version 6 and below, I used a snippet like:
```
intersection_code = 'Line{{{}}} In Surface{{{}}};'.format(line.id, surf.surface.id)
geom.add_raw_code(intersection_code)
```
to enforce that the meshing of a surface conformed to a line embedded in that surface. This is something I use regularly with my workflow. 

Is there an equivalent using the new pygmsh version 7 API and the underlying gmsh python API? If not, do you think it would be a fairly simple PR? I'd be happy to help. 

Thanks for a great project! 

For a full working example with pygmsh 6.1.1 of what I'm trying to do. You can see that the mesh conforms to the diagonal line from (-0.5, 0.5) to (0.5, 0.5). I have much more complex lines of this sort embedded in more complex surfaces. 

```
import pygmsh
import numpy as np
mesh_size = 0.3
geom = pygmsh.built_in.Geometry()
surf_corners = np.array([[-1, -1, 0], [1, -1, 0], [1, 1, 0], [-1, 1, 0]])
surf = geom.add_polygon(surf_corners, mesh_size)
pt1 = geom.add_point([0.5, 0.5, 0], mesh_size)
pt2 = geom.add_point([-0.5, -0.5, 0], mesh_size)
line = geom.add_line(pt1, pt2)
intersection_code = 'Line{{{}}} In Surface{{{}}};'.format(line.id, surf.surface.id)
geom.add_raw_code(intersection_code)
mesh = pygmsh.generate_mesh(geom, dim = 2)

import matplotlib.pyplot as plt
points = mesh.points
cells = mesh.cells_dict
plt.triplot(points[:,0], points[:,1], cells['triangle'], linewidth = 0.5)
plt.show()
```

![image](https://user-images.githubusercontent.com/4241811/114330602-1344f380-9b10-11eb-8d56-5e6a0cb32739.png)

**Comment by nschloe** [comment]
> Is there an equivalent using the new pygmsh version 7 API and the underlying gmsh python API?

You can always use the underlying the Gmsh Python API, indeed.
```python
import gmsh

gmsh.do_your_thing
```

**Comment by tbenthompson** [comment]
> 
> You can always use the underlying the Gmsh Python API, indeed.
> 
> ```python
> 
> import gmsh
> 
> 
> 
> gmsh.do_your_thing
> 
> ```

Ok. Thanks! Are you you aware of a way to do this kind of "Line in Surface" with the underlying gmsh API. I tried to look through and didn't find anything promising. I also didn't find a way of inserting custom code. If that assessment sounds correct, I'll probably submit a feature request to the gmsh API and just stick with using pygmsh 6.1.1 for now.

**Comment by nschloe** [comment]
> Are you you aware of a way to do this kind of "Line in Surface" with the underlying gmsh API?

No idea. Best ask the Gmsh folks!

> I also didn't find a way of inserting custom code. 

You never you geo "code" in the API. It's all Python calls.

**Comment by nschloe** [comment]
Wait, how about `in_surface()`?

**Comment by tbenthompson** [comment]
> Wait, how about `in_surface()`?

Oh wow! How did I miss that? Thank you! I'll go test it out.

**Comment by nschloe** [comment]
Assuming this is fixed. Feel free to reopen if not.
