### ISSUE TITLE
How can I rotate a mesh ? 

### ISSUE THREAD

**Issue by moonchildz** [nschloe/pygmsh#446]
Hello :)

 I am trying to generate a random blob that is composed of several ellipsoids, and I cannot find how to rotate/translate the object. 
```python
pi = 3.141592
with pgm.occ.Geometry() as geom:
    ellip_list = []
    xyz_list = []
    rad_list = []
    angle_list = []
    ballnum = rnd.randint(5, 23)
    xi = rnd.uniform(-2.5, 2.5)
    yi = rnd.uniform(-2.5, 2.5)
    zi = rnd.uniform(-2.5, 2.5)
    r1i = rnd.uniform(0.3, 2.5)
    r2i = rnd.uniform(r1i - 0.2, r1i + 0.2)
    r3i = rnd.uniform(r1i - 0.2, r1i + 0.2)
    thi = rnd.uniform(-pi, pi)
    psi = rnd.uniform(-pi, pi)
    pyi = rnd.uniform(-pi, pi)
    ellip_init = geom.add_ellipsoid((xi, yi, zi), radii=(r1i, r2i, r3i))
    ellip_list.append(ellip_init)
    geom.translate(ellip_init, (xi, yi, zi))
    geom.rotate(ellip_init, (xi, yi, zi), thi, 0)
```
And I got error at last line : 
```
TypeError: rotate() argument after * must be an iterable, not int
```
I just thought that geom.rotate() rotates the object ellip_init with respect of center point (xi, yi, zi), with angle value thi with respect of axis 0, where I intended x-axis. 

Supposing that I want to rotate the object using rotation center (xi, yi, zi) and angle values ( thi, psi, pyi), how should I write the function ?

**Comment by nschloe** [comment]
I'm getting
```
NameError: name 'pgm' is not defined
```
Please make sure your MWEs are complete. (You can edit your post, too.)

**Comment by moonchildz** [comment]
I imported  pygmsh as pgm.

I solved the issue. Here's my improved code : 

    geom.translate(ellipsoid,xyz_list[n])
    geom.rotate(ellipsoid,point=xyz_list[n],angle = rad_list[n][2],axis=(0.0,0.0,1.0))

Thank you.

**Comment by nschloe** [comment]
I don't want to guess what you're running. Please make sure your code is _complete_. I just want to copy and paste the code and see the error.
