### ISSUE TITLE
Pass mesh fineness arguments

### ISSUE THREAD

**Issue by ryancoe** [nschloe/pygmsh#449]
Back in #331, I learned how to set the fineness of the mesh using `extra_gmsh_arguments`, but this seems to have gone away in v7. How should this be done with the new API? I'm looking to pass arguments to `gmsh` such as `clscale` and `clcurv`.

**Comment by nschloe** [comment]
From v7 on, pygmsh uses the Gmsh's own Python API. I think you set the values like
```
import

gmsh.option.setNumber('Mesh.MeshSizeMin', 0.1)
```

**Comment by ryancoe** [comment]
Thanks very much @nschloe!

For posterity, here's my test. Also, I have never found the `gmsh` documentation easy to navigate, but I believe this section gives the relevant option fields: https://gmsh.info/doc/texinfo/gmsh.html#Command_002dline-options (I tend to use `Mesh.MeshSizeFactor`)

```python
import pygmsh
import gmsh

r1 = 1

for ms in [0.5, 1]:

    with pygmsh.occ.Geometry() as geom:
        print('Setting MeshSizeFactor to {:}'.format(ms))
        gmsh.option.setNumber('Mesh.MeshSizeFactor', ms)
        print('MeshSizeFactor: {:}'.format(gmsh.option.getNumber('Mesh.MeshSizeFactor')))
        sphere = geom.add_ball(center=[0,0,0], radius=r1)   
        mesh = geom.generate_mesh(dim=2)
        
    mesh.write('my_mesh_{:}.stl'.format(ms))
```
![image](https://user-images.githubusercontent.com/5589887/115579716-a9e98100-a283-11eb-88dd-c2fe9d0fb8e3.png)
