### ISSUE TITLE
Generating mesh for a polygon with a 'hole' inside it

### ISSUE THREAD

**Issue by RalphOppenheimer** [nschloe/pygmsh#466]
Hello,
Normally, by using the following code:

`geom.add_polygon(
        [
            [0.0, 0.0],
            [1.0, -0.2],
            [1.1, 1.2],
            [0.1, 0.7],
            [0.0, 0.0]
        ],
        mesh_size=0.1,
    )`

Generating mesh is quite simple, but what if I have a geometry, which has a 'hole' inside it? 
(it can be specified by coordinates)
Is it possible, to input a shape with a hole, and then generate mesh for it? If so, how? Thank you in advance for your help in that regard.

Cheers.

**Comment by gdmcbain** [comment]
See

https://github.com/nschloe/pygmsh/blob/ace74f5f5419dcfcaae6f195773e837d1f1691fb/test/built_in/test_hole_in_square.py#L17-L25
