### ISSUE TITLE
Pygmsh Boolean_Union

### ISSUE THREAD

**Issue by Maratono** [nschloe/pygmsh#473]
Hello,
When I do the boolean operation in gmsh, it seems that it doesn't save as a new surface. Because, when I want to "copy" or "translate" it, I face the following error:
```````````
      union = model.boolean_union([s100, s200, s300, s400, s500, s600])
      Copy_geo = model.copy(union)
```````````

Traceback (most recent call last):
  File "/Users/tayebi/Documents/Work/Ph.D./Micromechanical modeling/Periodic_homogenization_main.py", line 15, in <module>
    Geometry(Porosity)
  File "/Users/tayebi/Documents/Work/Ph.D./Micromechanical modeling/PyGeometry.py", line 82, in Geometry
    Copy_geo = model.copy(union)
  File "/Users/tayebi/miniconda3/envs/pygmsh-402/lib/python3.9/site-packages/pygmsh/common/geometry.py", line 240, in copy
    dim_tag = self.env.copy(obj.dim_tags)
AttributeError: 'list' object has no attribute 'dim_tags'

Thanks in advance for your help

**Comment by nschloe** [comment]
A union returns multiple objects. They correspond to different geometric entities I think.

**Comment by Maratono** [comment]
Thanks a lot for your response,
So, how can I take the right geometry from "union"? Moreover, the meshing of the geometry destroys. Do you know how I can remesh it?
Thanks

**Comment by nschloe** [comment]
> So, how can I take the right geometry from "union"?

What do you mean by "right"?

**Comment by Maratono** [comment]
I supposed that "union" returns only one object which is a geometry entity, but you say that it returns multiple objects!

**Comment by nschloe** [comment]
That's right, gmsh does that. One item for each separate entity. What's the problem?

**Comment by Maratono** [comment]
I want only one object, output from boolean_union which I can "copy" and "translate".

**Comment by nschloe** [comment]
The output of union is always a list. Perhaps it has only one entry in your case?

**Comment by Maratono** [comment]
In GMSH script I can create a unioned object which I can "translate" it. What do you mean it has one entry?

**Comment by nschloe** [comment]
You get a list back. Maybe it's a list of lenght 1?

**Comment by ruiesteves-pt** [comment]
Dear Nico, I am having the exact same issue - I checked the length of said list and indeed it is of length 1. However when I do:
```
union = geom.boolean_union([block1,block2])
union_copy = geom.copy(union[0])
```


I get the following error:
`TypeError: 'Dummy' object is not iterable`

Is there anyway around this?

**Comment by nschloe** [comment]
I always need a full copy-and-pastable code snippet to reproduce.

**Comment by ruiesteves-pt** [comment]
Here you have it, sorry about that.
```
import pygmsh
import meshio

with pygmsh.occ.Geometry() as geom:
    p1 = [0,0,0]
    p2 = [5,5,5]
    box1 = geom.add_box(p1,p2)

    p3 = [5,0,0]
    p4 = [5,5,5]
    box2 = geom.add_box(p3,p4)

    box_union = geom.boolean_union([box1,box2])
    box_copy = geom.copy(box_union[0])
    geom.mirror(box_copy,[0,1,0,0])
    complete_structure = geom.boolean_union(box_union[0],box_copy)

    mesh = geom.generate_mesh()
    mesh.write("test_box.xdmf")

```

**Comment by nschloe** [comment]
The second union call is wrong. It needs a list.
```python
complete_structure = geom.boolean_union([box_union[0], box_copy])
```
