### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by arrran** [nschloe/pygmsh#474]
Hi
Do you recommend any packages for plotting meshes in python?
I looked at [ogs5py](https://geostat-framework.readthedocs.io/projects/ogs5py/en/stable/tutorial_03_gmsh.html) but I think it is outdated.
I would like simple plots like those in your documentation.
Thanks
arran

**Comment by nschloe** [comment]
Paraview. There's also meshio which can save 2d meshes as SVG.
