### ISSUE TITLE
Deprecation of add_raw_code / quad recombination alg selection

### ISSUE THREAD

**Issue by tanderson92** [nschloe/pygmsh#477]
Hey there!
    (Thanks for the great work on this project, it's a joy to use.)

I had a question about the apparently deprecated add_raw_code. It was noted in #373 as well but the issue there was sidestepped. Is there a particular reason this was removed / does not work anymore? I ask for a different reason. I essentially want to do what is mentioned in https://github.com/nschloe/pygmsh/issues/304#issuecomment-585481860, that is, use a different RecombinationAlgorithm for generating quad meshes. Or, is there another way to do this and I'm committing an XY error?

Maybe I am really asking for permission to make a PR that adds the recombination algorithm as an optional argument to generate_mesh and then passes it along to gmsh in a similar way as the "algorithm" option currently does.

Thanks.

**Comment by nschloe** [comment]
pygmsh is based on gmsh's own Python API, not on the old geo-files, which is why `add_raw_code` doesn't make sense anymore. You can always use gmsh's API inbetween pygmsh calls though.

**Comment by tanderson92** [comment]
Thanks, this makes sense.
