### ISSUE TITLE
`Point` instance should store its `mesh_size` as an attribute

### ISSUE THREAD

**Issue by Corwinpro** [nschloe/pygmsh#480]
The `mesh_size` argument of a `Point` class:

https://github.com/nschloe/pygmsh/blob/e40e57b38888c5666e9a16b51824671c1e527c71/src/pygmsh/common/point.py#L14

is used to create a `Point` object but is discarded after that. I can envisage use cases when the `mesh_size` of a `Point` is required _after_ the `Point` has been created, but right now there is no way to access that attribute post factum.

PS. It would be a rather simple addition (fix), and I am happy to add this.

**Comment by nschloe** [comment]
> I can envisage use cases

Let's hear about it.

**Comment by Corwinpro** [comment]
An example I have in mind is when a collection of `Point`s is generated automatically, and there are two points that have the same coordinates but different mesh sizes. One of those points can be ignored in subsequent boundary / geometry generation (because they represent the same physical location), but users should be able to make a conscious choice of which one to use or ignore. `mesh_size` could be a way to reason about that (e.g., prefer a `Point` with smaller `mesh_size`).

**Comment by nschloe** [comment]
That sounds like all the info is processes _before_ specifying the geometry, doesn't it?

**Comment by Corwinpro** [comment]
That is correct. I believe that if a module / class that operates with `pygmsh` objects only should not be able to extract this information from the `pygsmh.Point` object.

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen at any time.
