### ISSUE TITLE
Meshing STL / IGES

### ISSUE THREAD

**Issue by jkbgbr** [nschloe/pygmsh#491]
Dear all,

I'm looking for a way to set up a cli-only pipeline to solve structural FE problems. These are shell models of doubly curved surfaces, with some simple loads.

My question is: can I somehow import and mesh geometries generated using pythonOCC using pygmsh? My export options from pythonocc are IGS and STP.

Thank you in advance!

**Comment by nschloe** [comment]
I would probably look at https://gitlab.onelab.info/gmsh/gmsh/blob/master/tutorial/python/t20.py.

**Comment by jkbgbr** [comment]
Wow!
Worked like a charm!
I'll still have to figure out many things (match mesh size with feature size, quad meshing if possible etc)., but this looks _very_ promising.
