### ISSUE TITLE
extrusion along polyline?

### ISSUE THREAD

**Issue by JianqiangDing** [nschloe/pygmsh#499]
Hi, 

If I am not mistaken, It seems that there is no API to extrude a 2d mesh along some given path(as curve or polyline .etc), Is it possible to realize it using existing APIs?

Any advice would be helpful, big thanks.

**Comment by nschloe** [comment]
You can use `geom.extrude`. Example:
```python
poly = geom.add_polygon([[5.0, 0.0], [6.0, 0.0], [5.0, 1.0]], mesh_size=0.1)
a, b, poly_lat = geom.extrude(poly, [0.0, 0.0, 1.0], num_layers=1)
```

**Comment by JianqiangDing** [comment]
but it only supports extrusion along a given straight line, am I right?

**Comment by nschloe** [comment]
Ah, I see now what you're looking for. Yeah you're right, you can't extrude a surface along an arbitrary path.

**Comment by JianqiangDing** [comment]
Q_0: For the reason we are working on discrete triangle mesh, How about concatenating segment surfaces by extruding along each small curve/polyline segment, I am not familiar with Gmsh and the design of your library, I am afraid this may introduce issues at joints (i.e. bad triangles even holes can be introduced)

The idea comes from issue #498 

Could you please provide some suggestions about this idea (perhaps the idea can work with simple necessary post-processing steps :) )?  

Q_1: I just test the boolean union operation, it seems that the output mesh does not remain the same mesh size as input element meshes

(About my testing case, I just call the API as
`
geom.boolean_union([top_ball, mid_cylinder, bottom_ball])
`
to union three elementary meshes, but the output mesh looks coarser)? Is there a way to fix this issue?

Here are screens for your reference

![image](https://user-images.githubusercontent.com/7833870/144571293-add31e45-fb70-4c76-906b-1de71fdbba88.png)
![image](https://user-images.githubusercontent.com/7833870/144571356-d41f6a3c-9737-4cb0-b3b0-79ae8d7c549a.png)
