### ISSUE TITLE
Round corners function?

### ISSUE THREAD

**Issue by lucascbarbosa** [nschloe/pygmsh#502]
I need to round the corners of my mesh, but there seems not to be a function for that. So I will try to use bspline but I have two problems: I need to round the corners of the voids inside my mesh (negative corners?), which I don't know how to do it with pygmsh, and I need to specify the radius size. Do you have any idea of what I should do? Would be interesting if I come up with the function for that?

**Comment by nschloe** [comment]
Perhaps the puzzle piece example on the front page will help. -> `difference`

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen at any time.
