### ISSUE TITLE
Is there a function in pygmsh that facilitates joining 3D meshes?

### ISSUE THREAD

**Issue by Chaztikov** [nschloe/pygmsh#505]
Hi, thanks for taking the time to read this.  It's more of a question than an issue (is there a better place to ask?)

I would like to generate a 3D mesh corresponding to the attached image (bifurcated channel, with stenosis).

I am not sure how I would go about doing this in pygmsh.

I could generate three cylinders by (separately) specifying points in 2D and using pygmsh.geo.Geometry().revolve

Following that, is some function within pygmsh that I should consider using in order to join the three 3D components?

Thanks!
Charlie

![image](https://user-images.githubusercontent.com/9398385/147334019-cde93879-24f2-4aad-9add-48ad82a163d7.png)

**Comment by nschloe** [comment]
> s there a better place to ask?

https://github.com/nschloe/pygmsh/discussions

**Comment by nschloe** [comment]
https://github.com/nschloe/pygmsh/discussions/510
