### ISSUE TITLE
Gmsh_executable under MacOs

### ISSUE THREAD

**Issue by beckerrh** [nschloe/pygmsh#51]
Gmsh could not be installed in /Applications, for example for brew-installed Gmsh.
Maybe we could have a check in 'helper.py':
"
if sys.platform == 'darwin':
    # likely there.
    gmsh_executable = '/Applications/Gmsh.app/Contents/MacOS/gmsh'
else:
    gmsh_executable = 'gmsh'
"

**Comment by nschloe** [comment]
Right on. I'm just fixing this via https://github.com/nschloe/pygmsh/pull/52.
