### ISSUE TITLE
flit build fails to detect gmsh

### ISSUE THREAD

**Issue by Schamschula** [nschloe/pygmsh#514]
It looks like the new build system fails to find gmsh.py on my machine.

I'm the MacPorts port maintainer for py-pygmsh, and the previous releases installed correctly.

I've updated the build to flit and adjusted the build dependencies.

However, gmsh does not install the python scripts in the "usual" place, i.e. under site-packages, but under $prefix/lib. Thus, the dependency check fails.

I locally worked around this issue by linking gmsh.py into the site-package folder for the chosen Python version. The wheel build still fails, as it is looking for the non-existent/redundant pypi module. I short circuited this in pyproject.toml and got a clean build.

I'm not familiar enough with flit to figure out how to lead it to the install path for gmsh.py.

At this point I can't push the update to MacPorts, as it's a kludge.

**Comment by Schamschula** [comment]
In the meantime, I've narrowed the issue down to the `gmsh` package.

MacPorts doesn't build the pypi wheel and nor is there a way to automate the build within the gmsh build. I manually managed to build the wheel, and copy the resulting `gmsh-4.9.3.dist-info` directory into `site-packages`.

This permits a clean build of pygmsh 7.1.15.

**Comment by nschloe** [comment]
Sounds like a gmsh issue then?

**Comment by Schamschula** [comment]
Yes. It proved to be that gmsh did not install the python components is the correct location.
