### ISSUE TITLE
generate_mesh raises two RuntimeWarnings for one-dimensional geometries

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#53]
The function `helper._sit_in_plane` added in #50 raises two `RuntimeWarnings`, first on trying to divide by the zero value of the squared-magnitude of the cross-product of two collinear vectors, second trying to compare the resulting quotient which is NaN to `tol`.
  To reproduce:

    g = Geometry()
    g.add_line(*(g.add_point((x, 0, 0), 1) for x in [0, 2]))
    print(generate_mesh(g))

The code runs fine and does generate correct one-dimensional meshes, but I wonder whether there isn't a yet more elegant test for planarity that would avoid these warnings.

**Comment by gdmcbain** [comment]
Maybe instead of normalizing `orth` in `helper._sit_in_plane`, just divide it by the magnitude of one of the difference-vectors? That shouldn't vanish.

    orth /= numpy.sqrt(numpy.dot(X[1] - X[0], X[1] - X[0]))

**Comment by nschloe** [comment]
Should be fixed by #54.
