### ISSUE TITLE
unicode labels for physical groups broken

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#65]
My code was broken I think by #47.  My code attempts to give unicode labels to physical entities.  Since pipupdating today, `geom.add_physical_point` now raises an `AssertionError` at `assert isinstance(label, str)`.

Short example:

    geom = Geometry()
    point = geom.add_point([0, 0, 0], 1)
    geom.add_physical_point(point, u'origin')

without the `u`, it works as before.

I think it should be a matter of accepting unicode or str rather than insisting on the latter?

**Comment by gdmcbain** [comment]
A fix might be to change `str` to `basestring` in the assertion.

https://docs.python.org/2.7/library/functions.html?highlight=basestring#basestring

**Comment by nschloe** [comment]
Fixed.
