### ISSUE TITLE
gmsh 3 features

### ISSUE THREAD

**Issue by capitalaslash** [nschloe/pygmsh#77]
Would you accept patches that work only with gmsh 3?
I am thinking about OpenCASCADE boolean operations.
Of course those would be properly guarded to avoid errors with gmsh 2.

**Comment by nschloe** [comment]
Is it about options to pass to `gmsh`?

**Comment by capitalaslash** [comment]
no, geometry generators similar to extrude, have a look here

http://gmsh.info/doc/texinfo/gmsh.html#Boolean-operations

**Comment by nschloe** [comment]
Ah okay, sure let's add those. Whoever doesn't use them only needs gmsh 2, so that's fine.

**Comment by capitalaslash** [comment]
ok, I will put up a couple of pull requests about this, I am trying to split it in more manageable patches.

**Comment by capitalaslash** [comment]
should I bump the patch or the minor version?
no interface is going to change, only additions

**Comment by nschloe** [comment]
Semantic versioning prescribes a minor version change in this case (x.X+1.x), and considering the fact that we're at patch level 10 or 11 for 1.8, why not bump it to 1.9.0.

**Comment by capitalaslash** [comment]
pygmsh is at version 3.1.0 (since my last patch that changed the extrude interface), I'll go for 3.2.0, maybe you were thinking about meshio.

**Comment by nschloe** [comment]
Ah, sure.

**Comment by nschloe** [comment]
I guess this can be closed now.
