### ISSUE TITLE
Translational extrusion of structured grids

### ISSUE THREAD

**Issue by SamMallinson** [nschloe/pygmsh#83]
As in the example t3.geo, we would like to be able to have pygmsh created extruded structured grids, eg. assuming you've created a sensible line-loop called `ll0`:
```
s0 = news;
Plane Surface(s0) = {ll0};
ex1[] = Extrude{10,0,0}{Surface{s0}; Layers{1}; Recombine;};
```
This would be useful for CFD codes which require 3d meshes which are one element thick to run 2d simulations (eg OpenFOAM).

This could be done by extending the extrude method:
1. change way function is called:
   ```python
    def extrude(
            self,
            input_entity,
            translation_axis=None,
            rotation_axis=None,
            point_on_axis=None,
            angle=None,
            layers=None,
            recombine=False,
            ):
    ```
2. then in the part of the code where the translation only part is described:
    ```python
        elif translation_axis is not None:
            # Only translation
            if layers is not None:
                self._GMSH_CODE.append(
                    '{}[] = Extrude{{{}}}{{{}; Layers{{{}}}; {}}};'.format(
                        name,
                        ','.join(repr(x) for x in translation_axis),
                        entity.id,
                        layers,
                        'Recombine;' if recombine else ''
                    ))
            else:
                self._GMSH_CODE.append(
                    '{}[] = Extrude{{{}}}{{{};}};'.format(
                        name,
                        ','.join(repr(x) for x in translation_axis),
                        entity.id
                    ))
    ```
3. in your python script:
    ```python
    surface = geom.add_plane_surface(line_loop)
    axis = [10, 0, 0]
    top, volume, lat = geom.extrude(surface, translation_axis=axis, layers=1, recombine=True)
    ```

**Comment by nschloe** [comment]
Sound good to me.

Would you like to submit a PR or do you want me to do it?

**Comment by SamMallinson** [comment]
Hi Nico,

I’ve just created a PR with a branch called translationalExtrude

Cheers,

Sam

**Comment by gdmcbain** [comment]
This is mostly covered by #109, but I wonder whether appending `Recombine;` is enough?  Isn't more needed to get quadrilateral elements on a surface and hexahedral elements in a volume?

**Comment by MacZel** [comment]
Actually it's not enough, especially when dealing with volumes. I'm currently writing an extension built on top of pygmsh that simplifies generating of structural meshes and postprocesses the mesh file for sfepy solver. Currently I've done the structural meshing part, now I'm working on simplifying using progression.  Once finished I'll post refs.

**Comment by gdmcbain** [comment]
Oh, O. K., great.  Look forwarding to that.  The only application that @SamMallinson & I have had thus far has been semistructured meshes, unstructured in two dimensions, structured by extrusion (with one layer) in the third.  Gmsh does of course have some facilities for fully structured meshes and it would be good to be able to access them where possible.

**Comment by nilswagner** [comment]
@MacZel und @gdmcbai Just out of curiosity, what is missing to close the ticket?

**Comment by gdmcbain** [comment]
Hi @nilswagner .  As [mentioned](https://github.com/nschloe/pygmsh/issues/83#issuecomment-350919717), the `extrude` method added in #109 sufficed for our immediate needs, so I didn't have anything on hand to test my [qualm](https://github.com/nschloe/pygmsh/issues/83#issuecomment-350592289) and I wasn't exactly sure what @MacZel was missing; however, I've just written a [`test/test_hex.py`](c0d7892) #138 which does extrude a line to get a structured rectangle of quadrilaterals and then extrude that to get a structured cuboid of hexahedra, so I think it looks good to me.

**Comment by nschloe** [comment]
Perfect, thank you all.
