### ISSUE TITLE
Issues when running using MPI

### ISSUE THREAD

**Issue by florianwechsung** [nschloe/pygmsh#84]
I use pygmsh at the beginning of some finite element code which is run in parallel using MPI. Since upgrading from 3.0.15 to the current version, the code aborts as soon as `pygmsh.Geometry()` is called. 
MPI Errorcode is 59, unfortunately that doesn't help me very much. 

Any idea what this might be? I'm running Ubuntu 17.04 with OpenMPI if that helps. 

Thanks!

**Comment by nschloe** [comment]
I've Never seen this kind of error. Given the geo-file, can you reproduce the error with a plain gmsh call on the command line? pygmsh should give you enough debug info to do that.

**Comment by florianwechsung** [comment]
How do I get debug info from pygmsh? 
Currently I just get 
```
Before calling Geometry()
Before calling Geometry()
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 59.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
``` 
when I run my code
```
from mpi4py import MPI
import pygmsh
comm = MPI.COMM_WORLD

[...]

print "Before calling Geometry()"
geom = pygmsh.Geometry()
print "After calling Geometry()"
p1 = geom.add_point(x=np.asarray([-2, +2, 0]), lcar=1)
[...]
```

**Comment by nschloe** [comment]
Ah, oh. That's not very verbose. Does this work without `mpi4py`?

**Comment by florianwechsung** [comment]
Mh, yeah it appears to be fine when I get rid of the `mpi4py` import

**Comment by nschloe** [comment]
Okay, then MPI seems to mess with Gmsh (or the other way around). As a workaround, can you put your mesh generation in a separate module that gets run _before_ importing mpi4py?

**Comment by florianwechsung** [comment]
Yeah I'll do that for now, thanks!

**Comment by nschloe** [comment]
Right on.
