### ISSUE TITLE
Structured mesh of a spherical lune

### ISSUE THREAD

**Issue by nilswagner** [nschloe/pygmsh#88]
Is it possible to create a structured mesh of a spherical lune using pygmsh ?

**Comment by nschloe** [comment]
No, pygmsh only does unstructured meshes (gmsh as well, afaik). The reason for this is the structured meshes can be constructed rather easily by hand. Check out [meshzoo](https://github.com/nschloe/meshzoo/blob/master/meshzoo/helpers.py) for example.

**Comment by gdmcbain** [comment]
Gmsh does have some facilities for structured grids; see [§6.3 ‘Structured grids’](http://gmsh.info/doc/texinfo/gmsh.html#Structured-grids).  (Not necessarily applicable to spherical lunes.)  The main facility is the `Layers` keyword in the `Extrude` command.  There's a proposal from  @SamMallinson which begins to add this to PyGmsh in #85 .
