### ISSUE TITLE
Set path to gmsh executable

### ISSUE THREAD

**Issue by r-maas** [nschloe/pygmsh#92]
The example didn't run right away as here the gmsh executable path is hardcoded for MacOS. Maybe add a seperate function that allows you to set the correct path manually?

https://github.com/nschloe/pygmsh/blob/fb10b7b475fc02b923e5b4021c0ab868df815ece/pygmsh/helper.py#L70

**Comment by nschloe** [comment]
The next line says ` if os.path.isfile(macos_gmsh_location): [...]` and if that file doesn't exist, it falls back to `gmsh`. If `gmsh` is in your path, that should work.

**Comment by r-maas** [comment]
I added a few more similar checks to my local helper.py file that looks at a few other usual suspect directories for the gmsh executable. Thanks!

**Comment by nschloe** [comment]
Putting gmsh in your `$PATH` should also suffice. Anyhow, good to see you've got it resolved!
