### ISSUE TITLE
3D boolean operation problem

### ISSUE THREAD

**Issue by ajconnolly** [nschloe/pygmsh#93]
It seems 3D boolean operations don't work properly. Try meshing the `geom` created by:

```python
def generate():
    geom = pg.Geometry()
    geom.set_factory('OpenCASCADE')
    lcar = 0.1
    ball=geom.add_ball([0.0, 0.0, 0.0], 0.5, lcar)
    box=geom.add_box(-1, 1, -1, 1, -1, 1, lcar)
    geom.boolean_difference([box.volume], [ball.volume])
    return geom
```
Or have I done something wrong?

**Comment by boerontour** [comment]
I have the same problem: 

`import pygmsh as pg

geom = pg.Geometry()
lcar = 0.1

box1 = geom.add_box(-1.0,1.0,-1.0,1.0,-1.0,1.0,lcar)
box2 = geom.add_box(-0.5,0.5,-0.5,0.5,-0.5,0.5,lcar)


geom.set_factory('OpenCASCADE')
_ = geom.boolean_difference(
    [box1.volume],
    [box2.volume]
    )

points, cells, point_data, cell_data, field_data = pg.generate_mesh(geom)`

Error:
`Traceback (most recent call last):
  File "TestBoolean.py", line 20, in <module>
    points, cells, point_data, cell_data, field_data = pg.generate_mesh(geom)
  File "/usr/local/lib/python3.6/site-packages/pygmsh/helper.py", line 131, in generate_mesh
    'Gmsh exited with error (return code {}).'.format(p.returncode)
AssertionError: Gmsh exited with error (return code 1).`

Logging (first part): 
`nfo    : Running 'gmsh -3 -bin /tmp/tmplbv5p5bz.geo -o /tmp/tmp4n0ede3h.msh -optimize_lloyd 10' [Gmsh 3.0.5, 1 node, max. 1
Info    : Started on Fri Sep 22 12:16:04 2017
Info    : Reading '/tmp/tmplbv5p5bz.geo'...
Info    : '/tmp/tmplbv5p5bz.geo', line 56 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 13
Error   : '/tmp/tmplbv5p5bz.geo', line 56 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 58 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 14
Error   : '/tmp/tmplbv5p5bz.geo', line 58 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 60 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 15
Error   : '/tmp/tmplbv5p5bz.geo', line 60 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 62 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 16
Error   : '/tmp/tmplbv5p5bz.geo', line 62 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 64 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 17
Error   : '/tmp/tmplbv5p5bz.geo', line 64 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 66 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 18
Error   : '/tmp/tmplbv5p5bz.geo', line 66 : Could not add surface
Error   : Unknown OpenCASCADE face with tag 19
Error   : '/tmp/tmplbv5p5bz.geo', line 68 : Could not add surface loop
Error   : Unknown OpenCASCADE surface loop with tag 19
Error   : '/tmp/tmplbv5p5bz.geo', line 70 : Could not add volume
Info    : '/tmp/tmplbv5p5bz.geo', line 124 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 31
Error   : '/tmp/tmplbv5p5bz.geo', line 124 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 126 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 32
Error   : '/tmp/tmplbv5p5bz.geo', line 126 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 128 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 33
Error   : '/tmp/tmplbv5p5bz.geo', line 128 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 130 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 34
Error   : '/tmp/tmplbv5p5bz.geo', line 130 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 132 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 35
Error   : '/tmp/tmplbv5p5bz.geo', line 132 : Could not add surface
Info    : '/tmp/tmplbv5p5bz.geo', line 134 : 'Ruled Surface' command is deprecated: use 'Surface' instead
Error   : Unknown line loop 36
Error   : '/tmp/tmplbv5p5bz.geo', line 134 : Could not add surface
Error   : Unknown OpenCASCADE face with tag 37
Error   : '/tmp/tmplbv5p5bz.geo', line 136 : Could not add surface loop
Error   : Unknown OpenCASCADE surface loop with tag 37
Error   : '/tmp/tmplbv5p5bz.geo', line 138 : Could not add volume
Error   : Unknown OpenCASCADE entity of dimension 3 with tag 19
Error   : '/tmp/tmplbv5p5bz.geo', line 138 : Could not apply boolean operator
Info    : Done reading '/tmp/tmplbv5p5bz.geo'
Info    : Finalized high order topology of periodic connections
Info    : Meshing 1D...
Info    : Meshing curve 1 (Line)
Info    : Meshing curve 2 (Line)
Info    : Meshing curve 3 (Line)
Info    : Meshing curve 4 (Line)`

**Comment by nschloe** [comment]
For a quick solution, I'd like you to refer to https://github.com/nschloe/frentos. It's based on CGAL and only supports 3D geomtries.

**Comment by ajconnolly** [comment]
OK Nico thanks. Does CGAL (& frentos) support subdomains like Gmsh?

**Comment by nschloe** [comment]
Not that I remember. That said, I wouldn't know that pygmsh supports subdomains either.

**Comment by ajconnolly** [comment]
I'll read further into CGALs capabilities. Your subdomains.py example works very well - I tested it and it extends to 3D also.

**Comment by boerontour** [comment]
Nico, thanks for your quick response. Do you think 3D boolean operations can be supported by PyGmsh in the near future? 
The rational behind this question: the example above is only a test case to show the problem. Changing to CGAL implies some additional porting work.

**Comment by nschloe** [comment]
> Do you think 3D boolean operations can be supported by PyGmsh in the near future?

I better not make promises here; I'm not too familiar with the OpenCascade factory yet. Another direction for you to push would be by looking at the `geo` file that pygmsh produces and see if you can spot an error here. If not, you'll find help on the gmsh mailing list.

Btw, the thing that kept me from running your example right away is the fact that Gmsh is a bit old in Debian/Ubuntu. I'm working on getting it updated now so there won't be such delays anymore in the future.

**Comment by ajconnolly** [comment]
I also have the same issues/requirements as boerontour - good luck with your fixes. I'm in the process of going through the Gmsh docs to see if I can diagnose the problem from the generated *.geo script.

Thanks for the suggestion about the mailing list.

**Comment by nschloe** [comment]
Okay, I've revamped and enhanced OpenCASCADE support. What should now work:
```python
geom = pygmsh.opencascade.Geometry(                                                                                                 
    characteristic_length_min=0.1,                                                                                                  
    characteristic_length_max=0.1,                                                                                                  
    )                                                                                                                               
                                                                                                                                        
rectangle = geom.add_rectangle(-1.0, -1.0, 0.0, 2.0, 2.0)                                                                           
disk_w = geom.add_disk(-1.0, 0.0, 0.0, 0.5)                                                                                         
disk_e = geom.add_disk(+1.0, 0.0, 0.0, 0.5)                                                                                         
geom.boolean_difference([rectangle], [disk_w, disk_e])                                                                              
                                                                                                                                       
points, cells, _, _, _ = pygmsh.generate_mesh(geom)
```
Check out the other new examples in `test/` for more inspiration.

Let me be optimistic and close this bug; feel free to reopen at any time of course.

**Comment by ajconnolly** [comment]
Thanks Nico for fixing this. Pygmsh now does *nearly* everything I need it to! Do you know how to specify different element edge-lengths in the domain? I can only see examples (in pygmsh and gmsh) where the element size is specified globally...

**Comment by nschloe** [comment]
No idea, sorry. Best try the gmsh mailing list.

**Comment by nschloe** [comment]
Wait, aren't you looking for `characteristic_length_min`/`_max`?

**Comment by ajconnolly** [comment]
Yes - I tried modifying this but it didn’t work. An example (trying to make the ball edges smaller):

----
geom = pg.opencascade.Geometry(                                                                                                 
geom = pg.opencascade.Geometry(                                                                                                 
        characteristic_length_min=0.05,                                                                                                  
        characteristic_length_max=0.2,                                                                                                  
        )
    ball=geom.add_ball([0.0, 0.0, 0.0], 0.5)
    
    ball.characteristic_length_min=0.05
    ball.characteristic_length_max=0.05
    
    box=geom.add_box([-1,-1,-1],[2,2,2])
    geom.boolean_difference([box], [ball])
----

But the generated *.geo code specifies the lengths globally:

----
Mesh.CharacteristicLengthMin = 0.05;
Mesh.CharacteristicLengthMax = 0.2;
etc
----

I’m not sure of the gmsh/openCASCADE syntax to specify the sizes locally...

Kind regards,
Adam

**Comment by nschloe** [comment]
> I’m not sure of the gmsh/openCASCADE syntax to specify the sizes locally...

Let me know if you find out more on this from the gmsh folks, we can add this to pygmsh then.

**Comment by ajconnolly** [comment]
I will do - have emailed Christophe Geuzaine as it seems he developed most of the openCASCADE functionality.

Kind regards,
Adam

**Comment by nschloe** [comment]
Btw, independently of what software we're talking about, I would always recommend to post such things in a public place rather than emailing the developer directly. This way, others may get the opportunity of reading it in case they have the same question or somebody else may even answer it.

**Comment by ajconnolly** [comment]
I will do - for some reason my gmsh mailing list activation code was filtered into my trash so I couldn’t before, but have found it now!

Kind regards,
Adam

**Comment by ajconnolly** [comment]
Hi Nico,

I stumbled across a solution. If the characteristic lengths are defined via points (Mesh.CharacteristicLengthFromPoints = 1;), then use Characteristic Length{ <points> } = XXX. For example:
------
SetFactory("OpenCASCADE”);

//This is needed:
Mesh.CharacteristicLengthFromPoints = 1;

v0 = newv;
Sphere(v0) = {0.0, 0.0, 0.0, 0.5};
p1() = PointsOf{ Volume{v0}; };

//In order to do this:
Characteristic Length{p1()} = 0.1;

v1 = newv;
Box(v1) = {-1, -1, -1, 2, 2, 2};
p2() = PointsOf{ Volume{v1}; };

//And this:
Characteristic Length{p2()} = 0.3;

bo1[] = BooleanDifference{Volume {v1}; Delete;} {Volume {v0}; Delete;};
———

Hopefully this shouldn’t be too hard to build into the pygmsh library.

Kind regards,
Adam

**Comment by ajconnolly** [comment]
Actually Mesh.CharacteristicLengthFromPoints is default 1

Kind regards,
Adam

**Comment by nschloe** [comment]
All OpenCASCADE priminives now have an optional `char_length` argument that you can use to specify the characteristic length.

**Comment by ajconnolly** [comment]
Nice work! Pygmsh will save me so much time!
